### ISSUE TITLE
uv pip install --prefix should search package in prefix path

### ISSUE THREAD

**Issue by Freed-Wu** [astral-sh/uv#10118]
```
❯ uv pip install --break-system-packages --prefix ~/.local hyuga
Using Python 3.12.7 environment at /nix/store/rmcswikkmjlp0rp5302dx8ydbqpgd14y-python3-3.12.7-env
Resolved 10 packages in 2.92s
error: Failed to prepare distributions
  Caused by: Failed to download and build `hyrule==0.7.0`
  Caused by: Build backend failed to determine requirements with `build_wheel()` (exit status: 1)

[stderr]
Traceback (most recent call last):
  File "<string>", line 8, in <module>
ModuleNotFoundError: No module named 'setuptools'
❯ uv pip install --break-system-packages --prefix ~/.local setuptools
Using Python 3.12.7 environment at /nix/store/rmcswikkmjlp0rp5302dx8ydbqpgd14y-python3-3.12.7-env
Resolved 1 package in 2ms
Installed 1 package in 8ms
 + setuptools==75.6.0
❯ uv pip install --break-system-packages --prefix ~/.local hyuga
Using Python 3.12.7 environment at /nix/store/rmcswikkmjlp0rp5302dx8ydbqpgd14y-python3-3.12.7-env
Resolved 10 packages in 3ms
error: Failed to prepare distributions
  Caused by: Failed to download and build `hy==1.0.0`
  Caused by: Build backend failed to determine requirements with `build_wheel()` (exit status: 1)

[stderr]
Traceback (most recent call last):
  File "<string>", line 8, in <module>
ModuleNotFoundError: No module named 'setuptools'
```

`pip install` will not have this bug.

**Comment by zanieb** [comment]
This looks like expected behavior from build isolation https://docs.astral.sh/uv/pip/compatibility/#pep-517-build-isolation

**Comment by Freed-Wu** [comment]
Oh, I note `--no-build-isolation`
