### ISSUE TITLE
Cannot install gevent==21.8.0 as a dependency

### ISSUE THREAD

**Issue by yajo** [astral-sh/uv#10233]
It seems that dependency [was requiring an alpha version of Cython](https://github.com/gevent/gevent/blob/7b2823e2c17b31ddc6234a26c4c324be6083c1bc/pyproject.toml#L25). Now there's a newer release and some alpha feature must have broken. See https://github.com/gevent/gevent/issues/1899.

Test the problem running `uv sync` with this `pyproject.toml` file:

```toml
[build-system]
requires = ['setuptools']

[project]
name = 'test1'
version = '1.0'
requires-python = '==3.10.*'
dependencies = [
    "gevent==21.8.0"
]
```

<details>
<summary>uv.lock</summary>

```toml
version = 1
requires-python = "==3.10.*"

[[package]]
name = "cffi"
version = "1.17.1"
source = { registry = "https://pypi.org/simple" }
dependencies = [
    { name = "pycparser" },
]
sdist = { url = "https://files.pythonhosted.org/packages/fc/97/c783634659c2920c3fc70419e3af40972dbaf758daa229a7d6ea6135c90d/cffi-1.17.1.tar.gz", hash = "sha256:1c39c6016c32bc48dd54561950ebd6836e1670f2ae46128f67cf49e789c52824", size = 516621 }
wheels = [
    { url = "https://files.pythonhosted.org/packages/f8/fe/4d41c2f200c4a457933dbd98d3cf4e911870877bd94d9656cc0fcb390681/cffi-1.17.1-cp310-cp310-win32.whl", hash = "sha256:c9c3d058ebabb74db66e431095118094d06abf53284d9c81f27300d0e0d8bc7c", size = 171804 },
    { url = "https://files.pythonhosted.org/packages/d1/b6/0b0f5ab93b0df4acc49cae758c81fe4e5ef26c3ae2e10cc69249dfd8b3ab/cffi-1.17.1-cp310-cp310-win_amd64.whl", hash = "sha256:0f048dcf80db46f0098ccac01132761580d28e28bc0f78ae0d58048063317e15", size = 181299 },
]

[[package]]
name = "gevent"
version = "21.8.0"
source = { registry = "https://pypi.org/simple" }
dependencies = [
    { name = "cffi", marker = "platform_python_implementation == 'CPython' and sys_platform == 'win32'" },
    { name = "greenlet", marker = "platform_python_implementation == 'CPython'" },
    { name = "setuptools" },
    { name = "zope-event" },
    { name = "zope-interface" },
]
sdist = { url = "https://files.pythonhosted.org/packages/33/2e/49317db0bbd846720ce15fd43641b17a208e6466c582ecbe845e35092ea2/gevent-21.8.0.tar.gz", hash = "sha256:43e93e1a4738c922a2416baf33f0afb0a20b22d3dba886720bc037cd02a98575", size = 6162938 }
wheels = [
    { url = "https://files.pythonhosted.org/packages/c4/42/eb6ccf5a71468470da9d91a4469ea20ab35cd0f7e34abdac6c4a3489538a/gevent-21.8.0-cp310-cp310-macosx_10_14_x86_64.whl", hash = "sha256:90131877d3ce1a05da1b718631860815b89ff44e93c42d168c9c9e8893b26318", size = 1860923 },
    { url = "https://files.pythonhosted.org/packages/06/fc/d27979f88453a2383eea42f3b56b9c4a749af9364f0d863f1152dcfcf15f/gevent-21.8.0-cp310-cp310-win_amd64.whl", hash = "sha256:3f5ba654bdd3c774079b553fef535ede5b52c7abd224cb235a15da90ae36251b", size = 1618039 },
    { url = "https://files.pythonhosted.org/packages/de/52/7c8e5e1588200ce441806a5c18d4858bb92e3e8a5a4a5042bc8fe6a3b267/gevent-21.8.0-pp27-pypy_73-win32.whl", hash = "sha256:b10c3326edb76ec3049646dc5131608d6d3733b5adfc75d34852028ecc67c52c", size = 850922 },
]

[[package]]
name = "greenlet"
version = "1.1.3.post0"
source = { registry = "https://pypi.org/simple" }
sdist = { url = "https://files.pythonhosted.org/packages/ea/37/e54ce453b298e890f59dba3db32461579328a07d5b65e3eabf80f971c099/greenlet-1.1.3.post0.tar.gz", hash = "sha256:f5e09dc5c6e1796969fd4b775ea1417d70e49a5df29aaa8e5d10675d9e11872c", size = 91784 }
wheels = [
    { url = "https://files.pythonhosted.org/packages/7c/c9/a4d77c0d9395a48560154470bbd79f14960ad4b6a16a10233881ca384d2d/greenlet-1.1.3.post0-cp310-cp310-macosx_10_15_x86_64.whl", hash = "sha256:f6661b58412879a2aa099abb26d3c93e91dedaba55a6394d1fb1512a77e85de9", size = 93996 },
    { url = "https://files.pythonhosted.org/packages/bf/a9/374f33142e3b6058f1403f15289f0b4ffd3fc067982c16fef5489a7f2e39/greenlet-1.1.3.post0-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl", hash = "sha256:2c6e942ca9835c0b97814d14f78da453241837419e0d26f7403058e8db3e38f8", size = 157440 },
    { url = "https://files.pythonhosted.org/packages/3c/19/ae42cfb96a20e3b5bc0ebb1a9ce42940de1b522414396bad1d5d1abfa93a/greenlet-1.1.3.post0-cp310-cp310-manylinux_2_17_ppc64le.manylinux2014_ppc64le.whl", hash = "sha256:a812df7282a8fc717eafd487fccc5ba40ea83bb5b13eb3c90c446d88dbdfd2be", size = 161005 },
    { url = "https://files.pythonhosted.org/packages/77/77/206360c55000e29c1509899df7b2edb9e9a1fa01bb013bdaebd0a9837252/greenlet-1.1.3.post0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl", hash = "sha256:83a7a6560df073ec9de2b7cb685b199dfd12519bc0020c62db9d1bb522f989fa", size = 156256 },
    { url = "https://files.pythonhosted.org/packages/af/3f/8c27cce2330959125cc707fa1c835d415dc45c1f566b2f8504cc3a6d266e/greenlet-1.1.3.post0-cp310-cp310-musllinux_1_1_aarch64.whl", hash = "sha256:17a69967561269b691747e7f436d75a4def47e5efcbc3c573180fc828e176d80", size = 699584 },
    { url = "https://files.pythonhosted.org/packages/5b/9f/ab2bb73975df5d234b5cc5283597cc773487f471f24f6646335660d36a12/greenlet-1.1.3.post0-cp310-cp310-musllinux_1_1_x86_64.whl", hash = "sha256:60839ab4ea7de6139a3be35b77e22e0398c270020050458b3d25db4c7c394df5", size = 711163 },
    { url = "https://files.pythonhosted.org/packages/85/9c/bbb5c8819434fe15b501ae767fed653534bfd281e11b98ea0b524640de59/greenlet-1.1.3.post0-cp310-cp310-win_amd64.whl", hash = "sha256:8926a78192b8b73c936f3e87929931455a6a6c6c385448a07b9f7d1072c19ff3", size = 101911 },
]

[[package]]
name = "pycparser"
version = "2.22"
source = { registry = "https://pypi.org/simple" }
sdist = { url = "https://files.pythonhosted.org/packages/1d/b2/31537cf4b1ca988837256c910a668b553fceb8f069bedc4b1c826024b52c/pycparser-2.22.tar.gz", hash = "sha256:491c8be9c040f5390f5bf44a5b07752bd07f56edf992381b05c701439eec10f6", size = 172736 }
wheels = [
    { url = "https://files.pythonhosted.org/packages/13/a3/a812df4e2dd5696d1f351d58b8fe16a405b234ad2886a0dab9183fb78109/pycparser-2.22-py3-none-any.whl", hash = "sha256:c3702b6d3dd8c7abc1afa565d7e63d53a1d0bd86cdc24edd75470f4de499cfcc", size = 117552 },
]

[[package]]
name = "setuptools"
version = "75.6.0"
source = { registry = "https://pypi.org/simple" }
sdist = { url = "https://files.pythonhosted.org/packages/43/54/292f26c208734e9a7f067aea4a7e282c080750c4546559b58e2e45413ca0/setuptools-75.6.0.tar.gz", hash = "sha256:8199222558df7c86216af4f84c30e9b34a61d8ba19366cc914424cdbd28252f6", size = 1337429 }
wheels = [
    { url = "https://files.pythonhosted.org/packages/55/21/47d163f615df1d30c094f6c8bbb353619274edccf0327b185cc2493c2c33/setuptools-75.6.0-py3-none-any.whl", hash = "sha256:ce74b49e8f7110f9bf04883b730f4765b774ef3ef28f722cce7c273d253aaf7d", size = 1224032 },
]

[[package]]
name = "test1"
version = "1.0"
source = { editable = "." }
dependencies = [
    { name = "gevent" },
]

[package.metadata]
requires-dist = [{ name = "gevent", specifier = "==21.8.0" }]

[[package]]
name = "zope-event"
version = "5.0"
source = { registry = "https://pypi.org/simple" }
dependencies = [
    { name = "setuptools" },
]
sdist = { url = "https://files.pythonhosted.org/packages/46/c2/427f1867bb96555d1d34342f1dd97f8c420966ab564d58d18469a1db8736/zope.event-5.0.tar.gz", hash = "sha256:bac440d8d9891b4068e2b5a2c5e2c9765a9df762944bda6955f96bb9b91e67cd", size = 17350 }
wheels = [
    { url = "https://files.pythonhosted.org/packages/fe/42/f8dbc2b9ad59e927940325a22d6d3931d630c3644dae7e2369ef5d9ba230/zope.event-5.0-py3-none-any.whl", hash = "sha256:2832e95014f4db26c47a13fdaef84cef2f4df37e66b59d8f1f4a8f319a632c26", size = 6824 },
]

[[package]]
name = "zope-interface"
version = "7.2"
source = { registry = "https://pypi.org/simple" }
dependencies = [
    { name = "setuptools" },
]
sdist = { url = "https://files.pythonhosted.org/packages/30/93/9210e7606be57a2dfc6277ac97dcc864fd8d39f142ca194fdc186d596fda/zope.interface-7.2.tar.gz", hash = "sha256:8b49f1a3d1ee4cdaf5b32d2e738362c7f5e40ac8b46dd7d1a65e82a4872728fe", size = 252960 }
wheels = [
    { url = "https://files.pythonhosted.org/packages/76/71/e6177f390e8daa7e75378505c5ab974e0bf59c1d3b19155638c7afbf4b2d/zope.interface-7.2-cp310-cp310-macosx_10_9_x86_64.whl", hash = "sha256:ce290e62229964715f1011c3dbeab7a4a1e4971fd6f31324c4519464473ef9f2", size = 208243 },
    { url = "https://files.pythonhosted.org/packages/52/db/7e5f4226bef540f6d55acfd95cd105782bc6ee044d9b5587ce2c95558a5e/zope.interface-7.2-cp310-cp310-macosx_11_0_arm64.whl", hash = "sha256:05b910a5afe03256b58ab2ba6288960a2892dfeef01336dc4be6f1b9ed02ab0a", size = 208759 },
    { url = "https://files.pythonhosted.org/packages/28/ea/fdd9813c1eafd333ad92464d57a4e3a82b37ae57c19497bcffa42df673e4/zope.interface-7.2-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl", hash = "sha256:550f1c6588ecc368c9ce13c44a49b8d6b6f3ca7588873c679bd8fd88a1b557b6", size = 254922 },
    { url = "https://files.pythonhosted.org/packages/3b/d3/0000a4d497ef9fbf4f66bb6828b8d0a235e690d57c333be877bec763722f/zope.interface-7.2-cp310-cp310-manylinux_2_5_i686.manylinux1_i686.manylinux_2_17_i686.manylinux2014_i686.whl", hash = "sha256:0ef9e2f865721553c6f22a9ff97da0f0216c074bd02b25cf0d3af60ea4d6931d", size = 249367 },
    { url = "https://files.pythonhosted.org/packages/3e/e5/0b359e99084f033d413419eff23ee9c2bd33bca2ca9f4e83d11856f22d10/zope.interface-7.2-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl", hash = "sha256:27f926f0dcb058211a3bb3e0e501c69759613b17a553788b2caeb991bed3b61d", size = 254488 },
    { url = "https://files.pythonhosted.org/packages/7b/90/12d50b95f40e3b2fc0ba7f7782104093b9fd62806b13b98ef4e580f2ca61/zope.interface-7.2-cp310-cp310-win_amd64.whl", hash = "sha256:144964649eba4c5e4410bb0ee290d338e78f179cdbfd15813de1a664e7649b3b", size = 211947 },
]
```

</details>

<details>
<summary>Error logs with `-v`</summary>

```
DEBUG uv 0.4.30
DEBUG Found project root: `/home/yajo/mydevel/test1`
DEBUG No workspace root found, using project root
DEBUG The virtual environment's Python version satisfies `Python ==3.10.*`
DEBUG Using request timeout of 30s
DEBUG Found static `pyproject.toml` for: test1 @ file:///home/yajo/mydevel/test1
DEBUG No workspace root found, using project root
DEBUG Existing `uv.lock` satisfies workspace requirements
Resolved 8 packages in 1ms
DEBUG Using request timeout of 30s
DEBUG Identified uncached distribution: gevent==21.8.0
DEBUG Requirement already cached: greenlet==1.1.3.post0
DEBUG Requirement already cached: setuptools==75.6.0
DEBUG Directory source requirement already cached: test1==1.0 (from file:///home/yajo/mydevel/test1)
DEBUG Requirement already cached: zope-event==5.0
DEBUG Requirement already cached: zope-interface==7.2
DEBUG Acquired lock for `/home/yajo/.cache/uv/sdists-v5/pypi/gevent/21.8.0`
DEBUG Found fresh response for: https://files.pythonhosted.org/packages/33/2e/49317db0bbd846720ce15fd43641b17a208e6466c582ecbe845e35092ea2/gevent-21.8.0.tar.gz
DEBUG Building: gevent==21.8.0
DEBUG Ignoring empty directory
DEBUG Resolving build requirements
DEBUG Solving with installed Python version: 3.10.16
DEBUG Solving with target Python version: >=3.10.16
DEBUG Adding direct dependency: setuptools>=40.8.0
DEBUG Adding direct dependency: wheel*
DEBUG Adding direct dependency: cython>=3.0a9
DEBUG Adding direct dependency: cffi{platform_python_implementation == 'CPython'}>=1.12.3
DEBUG Adding direct dependency: greenlet{platform_python_implementation == 'CPython'}>=0.4.17, <2.0
DEBUG Found fresh response for: https://pypi.org/simple/wheel/
DEBUG Found fresh response for: https://files.pythonhosted.org/packages/0b/2c/87f3254fd8ffd29e4c02732eee68a83a1d3c346ae39bc6822dcbcb697f2b/wheel-0.45.1-py3-none-any.whl.metadata
DEBUG Found fresh response for: https://pypi.org/simple/setuptools/
DEBUG Searching for a compatible version of setuptools (>=40.8.0)
DEBUG Selecting: setuptools==75.6.0 [compatible] (setuptools-75.6.0-py3-none-any.whl)
DEBUG Found fresh response for: https://files.pythonhosted.org/packages/55/21/47d163f615df1d30c094f6c8bbb353619274edccf0327b185cc2493c2c33/setuptools-75.6.0-py3-none-any.whl.metadata
DEBUG Searching for a compatible version of wheel (*)
DEBUG Selecting: wheel==0.45.1 [compatible] (wheel-0.45.1-py3-none-any.whl)
DEBUG Found fresh response for: https://pypi.org/simple/cffi/
DEBUG Found fresh response for: https://pypi.org/simple/greenlet/
DEBUG Found fresh response for: https://pypi.org/simple/cython/
DEBUG Searching for a compatible version of cython (>=3.0a9)
DEBUG Selecting: cython==3.1.0a1 [compatible] (Cython-3.1.0a1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl)
DEBUG Found fresh response for: https://files.pythonhosted.org/packages/e6/7e/6b5ba69f33563a56b3587dea3d44e3e822149c54bbeea6e9f57c73adb089/Cython-3.1.0a1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata
DEBUG Searching for a compatible version of cffi{platform_python_implementation == 'CPython'} (>=1.12.3)
DEBUG Selecting: cffi==1.17.1 [compatible] (cffi-1.17.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl)
DEBUG Adding transitive dependency for cffi==1.17.1: cffi==1.17.1
DEBUG Adding transitive dependency for cffi==1.17.1: cffi{platform_python_implementation == 'CPython'}==1.17.1
DEBUG Searching for a compatible version of cffi{platform_python_implementation == 'CPython'} (==1.17.1)
DEBUG Selecting: cffi==1.17.1 [compatible] (cffi-1.17.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl)
DEBUG Found fresh response for: https://files.pythonhosted.org/packages/8d/fb/4da72871d177d63649ac449aec2e8a29efe0274035880c7af59101ca2232/cffi-1.17.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata
DEBUG Adding transitive dependency for cffi==1.17.1: pycparser*
DEBUG Searching for a compatible version of cffi (==1.17.1)
DEBUG Selecting: cffi==1.17.1 [compatible] (cffi-1.17.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl)
DEBUG Found fresh response for: https://pypi.org/simple/pycparser/
DEBUG Adding transitive dependency for cffi==1.17.1: pycparser*
DEBUG Searching for a compatible version of greenlet{platform_python_implementation == 'CPython'} (>=0.4.17, <2.0)
DEBUG Found fresh response for: https://files.pythonhosted.org/packages/13/a3/a812df4e2dd5696d1f351d58b8fe16a405b234ad2886a0dab9183fb78109/pycparser-2.22-py3-none-any.whl.metadata
DEBUG Selecting: greenlet==1.1.3.post0 [compatible] (greenlet-1.1.3.post0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl)
DEBUG Adding transitive dependency for greenlet==1.1.3.post0: greenlet==1.1.3.post0
DEBUG Adding transitive dependency for greenlet==1.1.3.post0: greenlet{platform_python_implementation == 'CPython'}==1.1.3.post0
DEBUG Searching for a compatible version of greenlet{platform_python_implementation == 'CPython'} (==1.1.3.post0)
DEBUG Selecting: greenlet==1.1.3.post0 [compatible] (greenlet-1.1.3.post0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl)
DEBUG Found fresh response for: https://files.pythonhosted.org/packages/77/77/206360c55000e29c1509899df7b2edb9e9a1fa01bb013bdaebd0a9837252/greenlet-1.1.3.post0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata
DEBUG Searching for a compatible version of greenlet (==1.1.3.post0)
DEBUG Selecting: greenlet==1.1.3.post0 [compatible] (greenlet-1.1.3.post0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl)
DEBUG Searching for a compatible version of pycparser (*)
DEBUG Selecting: pycparser==2.22 [compatible] (pycparser-2.22-py3-none-any.whl)
DEBUG Tried 6 versions: cffi 1, cython 1, greenlet 1, pycparser 1, setuptools 1, wheel 1
DEBUG marker environment resolution took 0.005s
DEBUG Installing in cffi==1.17.1, cython==3.1.0a1, greenlet==1.1.3.post0, pycparser==2.22, setuptools==75.6.0, wheel==0.45.1 in /home/yajo/.cache/uv/builds-v0/.tmpaIVstF
DEBUG Requirement already cached: cffi==1.17.1
DEBUG Requirement already cached: cython==3.1.0a1
DEBUG Requirement already cached: greenlet==1.1.3.post0
DEBUG Requirement already cached: pycparser==2.22
DEBUG Requirement already cached: setuptools==75.6.0
DEBUG Requirement already cached: wheel==0.45.1
DEBUG Installing build requirements: cffi==1.17.1, cython==3.1.0a1, greenlet==1.1.3.post0, pycparser==2.22, setuptools==75.6.0, wheel==0.45.1
DEBUG Creating PEP 517 build environment
DEBUG Calling `setuptools.build_meta:__legacy__.get_requires_for_build_wheel()`
DEBUG performance hint: src/gevent/libev/corecext.pyx:1325:0: Exception check on '_syserr_cb' will always require the GIL to be acquired.
DEBUG Possible solutions:
DEBUG   1. Declare '_syserr_cb' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
DEBUG   2. Use an 'int' return type on '_syserr_cb' to allow an error code to be returned.
DEBUG 
DEBUG Error compiling Cython file:
DEBUG ------------------------------------------------------------
DEBUG ...
DEBUG cdef tuple integer_types
DEBUG 
DEBUG if sys.version_info[0] >= 3:
DEBUG     integer_types = int,
DEBUG else:
DEBUG     integer_types = (int, long)
DEBUG                           ^
DEBUG ------------------------------------------------------------
DEBUG 
DEBUG src/gevent/libev/corecext.pyx:60:26: undeclared name not builtin: long
DEBUG Traceback (most recent call last):
DEBUG   File "<string>", line 14, in <module>
DEBUG   File "/home/yajo/.cache/uv/builds-v0/.tmpaIVstF/lib/python3.10/site-packages/setuptools/build_meta.py", line 334, in get_requires_for_build_wheel
DEBUG     return self._get_build_requires(config_settings, requirements=[])
DEBUG   File "/home/yajo/.cache/uv/builds-v0/.tmpaIVstF/lib/python3.10/site-packages/setuptools/build_meta.py", line 304, in _get_build_requires
DEBUG     self.run_setup()
DEBUG   File "/home/yajo/.cache/uv/builds-v0/.tmpaIVstF/lib/python3.10/site-packages/setuptools/build_meta.py", line 522, in run_setup
DEBUG     super().run_setup(setup_script=setup_script)
DEBUG   File "/home/yajo/.cache/uv/builds-v0/.tmpaIVstF/lib/python3.10/site-packages/setuptools/build_meta.py", line 320, in run_setup
DEBUG     exec(code, locals())
DEBUG   File "<string>", line 50, in <module>
DEBUG   File "/home/yajo/.cache/uv/sdists-v5/pypi/gevent/21.8.0/_EzRJM4MiLuZu0_D360Ym/gevent-21.8.0.tar.gz/_setuputils.py", line 237, in cythonize1
DEBUG     new_ext = cythonize(
DEBUG   File "/home/yajo/.cache/uv/builds-v0/.tmpaIVstF/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 1109, in cythonize
DEBUG     cythonize_one(*args)
DEBUG   File "/home/yajo/.cache/uv/builds-v0/.tmpaIVstF/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 1256, in cythonize_one
DEBUG     raise CompileError(None, pyx_file)
DEBUG Cython.Compiler.Errors.CompileError: src/gevent/libev/corecext.pyx
DEBUG Compiling src/gevent/libev/corecext.pyx because it changed.
DEBUG [1/1] Cythonizing src/gevent/libev/corecext.pyx
DEBUG Released lock at `/home/yajo/.cache/uv/sdists-v5/pypi/gevent/21.8.0/.lock`
error: Failed to prepare distributions
  Caused by: Failed to download and build `gevent==21.8.0`
  Caused by: Build backend failed to determine requirements with `build_wheel()` (exit status: 1)

[stdout]
Compiling src/gevent/libev/corecext.pyx because it changed.
[1/1] Cythonizing src/gevent/libev/corecext.pyx

[stderr]
performance hint: src/gevent/libev/corecext.pyx:1325:0: Exception check on '_syserr_cb' will always require the GIL to be acquired.
Possible solutions:
        1. Declare '_syserr_cb' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
        2. Use an 'int' return type on '_syserr_cb' to allow an error code to be returned.

Error compiling Cython file:
------------------------------------------------------------
...
cdef tuple integer_types

if sys.version_info[0] >= 3:
    integer_types = int,
else:
    integer_types = (int, long)
                          ^
------------------------------------------------------------

src/gevent/libev/corecext.pyx:60:26: undeclared name not builtin: long
Traceback (most recent call last):
  File "<string>", line 14, in <module>
  File "/home/yajo/.cache/uv/builds-v0/.tmpaIVstF/lib/python3.10/site-packages/setuptools/build_meta.py", line 334, in get_requires_for_build_wheel
    return self._get_build_requires(config_settings, requirements=[])
  File "/home/yajo/.cache/uv/builds-v0/.tmpaIVstF/lib/python3.10/site-packages/setuptools/build_meta.py", line 304, in _get_build_requires
    self.run_setup()
  File "/home/yajo/.cache/uv/builds-v0/.tmpaIVstF/lib/python3.10/site-packages/setuptools/build_meta.py", line 522, in run_setup
    super().run_setup(setup_script=setup_script)
  File "/home/yajo/.cache/uv/builds-v0/.tmpaIVstF/lib/python3.10/site-packages/setuptools/build_meta.py", line 320, in run_setup
    exec(code, locals())
  File "<string>", line 50, in <module>
  File "/home/yajo/.cache/uv/sdists-v5/pypi/gevent/21.8.0/_EzRJM4MiLuZu0_D360Ym/gevent-21.8.0.tar.gz/_setuputils.py", line 237, in cythonize1
    new_ext = cythonize(
  File "/home/yajo/.cache/uv/builds-v0/.tmpaIVstF/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 1109, in cythonize
    cythonize_one(*args)
  File "/home/yajo/.cache/uv/builds-v0/.tmpaIVstF/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 1256, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: src/gevent/libev/corecext.pyx
```

</details>

@moduon MT-1075

**Comment by charliermarsh** [comment]
Is this a uv issue? It looks like a gevent issue.

**Comment by yajo** [comment]
Well, uv has a few tools to fix problems with dependencies. Examples:
- https://docs.astral.sh/uv/concepts/resolution/#dependency-overrides
- https://docs.astral.sh/uv/concepts/resolution/#dependency-metadata
- https://docs.astral.sh/uv/concepts/resolution/#reproducible-resolutions
- https://docs.astral.sh/uv/concepts/projects/build/#build-constraints

Those options can fix the problem for dependencies. But they cannot fix it for `build-system.requires` of the dependencies AFAIK.

Since you guys are covering those other cases in uv, I thought this case would be interesting to you.

This is probably related to #7052.

If I might suggest an expected solution, I'd love to be able to do something like this:

```toml
[build-system]
requires = ['setuptools']

[project]
name = 'test1'
version = '1.0'
requires-python = '==3.10.*'
dependencies = [
    "gevent==21.8.0"
]

[tool.uv.build-constraints]
dependencies.gevent = ["Cython==3.0a9"]
```

Since builds are isolated, it makes no sense for me to ask for that particular Cython version to build any other dependencies that need it.

**Comment by charliermarsh** [comment]
Why does `build-constraints` not solve the problem? Just trying to understand.

**Comment by yajo** [comment]
Because there's no way to apply constraints just to a _dependency_. If I had other dependencies that required Cython to build too, it wouldn't make sense to inject an alpha version of Cython into their isolated build environment just because gevent expects it.

Also because build-constraints is only a CLI flag, and cannot be configured in a shared way (AFAICS).
