### ISSUE TITLE
Improve display of conclusions after enumerating available versions

### ISSUE THREAD

**Issue by zanieb** [astral-sh/uv#1235]
e.g. in

```
recommenders>0.7
```
```
❯ cargo run -q -- pip compile --python-version 3.12 requirements.in
  × No solution found when resolving dependencies:
  ╰─▶ Because the requested Python version (3.12) does not satisfy Python>=3.6,<3.10 and recommenders==1.0.0 depends on Python>=3.6,<3.9, we can conclude that recommenders==1.0.0 cannot be used.
      And because only the following versions of recommenders are available:
          recommenders<=0.7
          recommenders==1.0.0
          recommenders==1.1.0
          recommenders==1.1.1
      we can conclude that recommenders>0.7,<1.1.0 cannot be used. (1)

      Because the requested Python version (3.12) does not satisfy Python>=3.6,<3.10 and recommenders>=1.1.0 depends on Python>=3.6,<3.10, we can conclude that recommenders>=1.1.0 cannot be used.
      And because we know from (1) that recommenders>0.7,<1.1.0 cannot be used, we can conclude that recommenders>0.7 cannot be used.
      And because you require recommenders>0.7, we can conclude that the requirements are unsatisfiable.
```

We list the available versions then conclude that a range cannot be used

```
      And because only the following versions of recommenders are available:
          recommenders<=0.7
          recommenders==1.0.0
          recommenders==1.1.0
          recommenders==1.1.1
      we can conclude that recommenders>0.7,<1.1.0 cannot be used. (1)
```

However, this would be clearer to read as

```
      And because only the following versions of recommenders are available:
          recommenders<=0.7
          recommenders==1.0.0
          recommenders==1.1.0
          recommenders==1.1.1
      we can conclude that recommenders cannot be used. (1)
```

This requires formatting of terms to know about the _previous_ term; I cannot determine a heuristic to use to determine when a compliment should be displayed here otherwise.

**Comment by konstin** [comment]
I can't reproduce this anymore, i'm getting:
```
cargo run -q -- pip compile --python-version 3.12 a.in --no-build-isolation
⠙ lightfm==1.17                                                                                      error: Failed to download and build `scikit-surprise==1.1.4`
  Caused by: Failed to build: `scikit-surprise==1.1.4`
  Caused by: Build backend failed to determine metadata through `prepare_metadata_for_build_wheel` with exit status: 1
--- stdout:

--- stderr:
Traceback (most recent call last):
  File "<string>", line 14, in <module>
  File "/home/konsti/projects/uv/.venv/lib/python3.12/site-packages/setuptools/build_meta.py", line 368, in prepare_metadata_for_build_wheel
    self.run_setup()
  File "/home/konsti/projects/uv/.venv/lib/python3.12/site-packages/setuptools/build_meta.py", line 313, in run_setup
    exec(code, locals())
  File "<string>", line 3, in <module>
ModuleNotFoundError: No module named 'numpy'
---
```

**Comment by zanieb** [comment]
I reproduced with a tweak

```
❯ echo 'recommenders>0.7\nlightfm<1.17' | uv pip compile --python-version 3.12 -
  × No solution found when resolving dependencies:
  ╰─▶ Because the requested Python version (3.12) does not satisfy Python>=3.6,<3.10 and recommenders==1.0.0 depends on
      Python>=3.6,<3.9, we can conclude that recommenders==1.0.0 cannot be used.
      And because only the following versions of recommenders are available:
          recommenders<=0.7
          recommenders==1.0.0
          recommenders==1.1.0
          recommenders==1.1.1
          recommenders==1.2.0
      we can conclude that recommenders>0.7,<1.1.0 cannot be used. (1)

      Because the requested Python version (3.12) does not satisfy Python>=3.6,<3.10 and recommenders>=1.1.0,<=1.1.1
      depends on Python>=3.6,<3.10, we can conclude that recommenders>=1.1.0,<=1.1.1 cannot be used.
      And because we know from (1) that recommenders>0.7,<1.1.0 cannot be used, we can conclude that
      recommenders>0.7,<1.2.0 cannot be used.
      And because recommenders==1.2.0 depends on lightfm>=1.17,<2, we can conclude that recommenders>0.7 depends on
      lightfm>=1.17,<2.
      And because you require recommenders>0.7 and lightfm<1.17, we can conclude that the requirements are unsatisfiable.
```

**Comment by zanieb** [comment]
and similarly

```
❯ echo 'recommenders>0.7' | uv pip compile --python-version 3.12 --only-binary :all: -
  × No solution found when resolving dependencies:
  ╰─▶ Because only the following versions of recommenders are available:
          recommenders<=0.7
          recommenders==1.0.0
          recommenders==1.1.0
          recommenders==1.1.1
          recommenders==1.2.0
      and recommenders==1.0.0 has no usable wheels and building from source is disabled, we can conclude that recommenders>0.7,<1.1.0 cannot be used.
      And because recommenders==1.1.0 has no usable wheels and building from source is disabled and recommenders==1.1.1 has no usable wheels and building from source is disabled, we can conclude that recommenders>0.7,<1.2.0 cannot be used. (1)
```

**Comment by konstin** [comment]
Different error, but still bad:

```
$ echo 'recommenders>0.7' | uv pip compile --python-version 3.12 --only-binary :all: - --exclude-newer 2024-06-27
  × No solution found when resolving dependencies:
  ╰─▶ Because only the following versions of cornac are available:
          cornac<=1.15.2
          cornac==1.15.3
          cornac==1.15.4
          cornac==1.16.0
          cornac==1.17.0
          cornac==1.18.0
          cornac>=2
      and cornac>=1.15.1,<=1.18.0 has no usable wheels, we can conclude that cornac>=1.15.1,<=1.18.0 cannot be used. (1)

      Because only the following versions of cornac are available:
          cornac<=1.1.2
          cornac==1.2.0
          cornac==1.2.1
          cornac==1.2.2
          cornac==1.3.0
          cornac==1.3.1
          cornac==1.4.0
          cornac==1.4.1
          cornac==1.5.0
          cornac==1.5.1
          cornac==1.5.2
          cornac==1.6.0
          cornac==1.6.1
          cornac==1.7.0
          cornac==1.7.1
          cornac==1.8.0
          cornac==1.9.0
          cornac==1.10.0
          cornac==1.11.0
          cornac==1.12.0
          cornac==1.13.0
          cornac==1.13.1
          cornac==1.13.2
          cornac==1.13.3
          cornac==1.13.4
          cornac==1.13.5
          cornac==1.14.0
          cornac==1.14.1
          cornac==1.14.2
          cornac==1.15.0
          cornac==1.15.1
          cornac>=1.15.2
      and cornac>=1.1.2,<=1.15.0 has no usable wheels, we can conclude that cornac>=1.1.2,<=1.15.0 cannot be used.
      And because we know from (1) that cornac>=1.15.1,<=1.18.0 cannot be used, we can conclude that cornac>=1.1.2,<2 cannot be used.
      And because recommenders>=1.0.0,<=1.1.1 depends on cornac>=1.1.2,<2, we can conclude that recommenders>=1.0.0,<=1.1.1 cannot be used. (2)

      Because only the following versions of cornac are available:
          cornac<=1.15.2
          cornac==1.15.3
          cornac==1.15.4
          cornac==1.16.0
          cornac==1.17.0
          cornac==1.18.0
          cornac>=2
      and cornac>=1.15.2,<=1.18.0 has no usable wheels, we can conclude that cornac>=1.15.2,<=1.18.0 cannot be used.
      And because recommenders>=1.2.0 depends on cornac>=1.15.2,<2, we can conclude that recommenders>=1.2.0 cannot be used.
      And because we know from (2) that recommenders>=1.0.0,<=1.1.1 cannot be used, we can conclude that recommenders>=1.0.0 cannot be used.
      And because you require recommenders>0.7, we can conclude that your requirements are unsatisfiable.

hint: Wheels are required for `cornac` because building from source is disabled for all packages (i.e., with `--no-build`)
```
