### ISSUE TITLE
internal error: entered unreachable code

### ISSUE THREAD

**Issue by Redoubts** [astral-sh/uv#1370]
First, very excited about this project.

I tried to use this to reproduce my pip-tools lock file, and got 
```
⠇ Resolving dependencies...                                                                                                                                                    thread 'tokio-runtime-worker' panicked at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async_http_range_reader-0.5.0/src/lib.rs:510:19:
range end index 306866 out of range for slice of length 291903
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async_http_range_reader-0.5.0/src/lib.rs:610:25:
internal error: entered unreachable code
```

invocation was 

```
uv pip compile --index-url https://pypi.<internal>.com --extra-index-url https://pypi.python.org/simple --output-file venv_lockfile.txt venv_requirements.txt
```

Using Python 3.10.13 uv 0.1.0 on debian 11.7. Installed via pip to my venv

`RUST_BACKTRACE=full`
```
RUST_BACKTRACE=full uv pip compile ...

⠇ Resolving dependencies...                                                                                                                                                    thread 'tokio-runtime-worker' panicked at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async_http_range_reader-0.5.0/src/lib.rs:510:19:
range end index 306866 out of range for slice of length 291903
stack backtrace:
   0:     0x5649a795d29c - <unknown>
   1:     0x5649a79903b0 - <unknown>
   2:     0x5649a79591bf - <unknown>
   3:     0x5649a795d084 - <unknown>
   4:     0x5649a795eee7 - <unknown>
   5:     0x5649a795ec4f - <unknown>
   6:     0x5649a795f368 - <unknown>
   7:     0x5649a795f24e - <unknown>
   8:     0x5649a795d766 - <unknown>
   9:     0x5649a795efb2 - <unknown>
  10:     0x5649a69cf6b5 - <unknown>
  11:     0x5649a69cfcf2 - <unknown>
  12:     0x5649a6afde7b - <unknown>
  13:     0x5649a6afccac - <unknown>
  14:     0x5649a6b124f0 - <unknown>
  15:     0x5649a788e3bb - <unknown>
  16:     0x5649a788d2ec - <unknown>
  17:     0x5649a7894248 - <unknown>
  18:     0x5649a788cd68 - <unknown>
  19:     0x5649a789b7d3 - <unknown>
  20:     0x5649a78a5187 - <unknown>
  21:     0x5649a787aa2a - <unknown>
  22:     0x5649a789aa6b - <unknown>
  23:     0x5649a7889597 - <unknown>
  24:     0x5649a78a2da9 - <unknown>
  25:     0x5649a7966835 - <unknown>
⠋ Resolving dependencies...                                                                                                                                                      26:     0x7fe282166f07 - start_thread
                               at ./nptl/pthread_create.c:477:8
thread 'tokio-runtime-worker' panicked at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async_http_range_reader-0.5.0/src/lib.rs:510:19:
range end index 17780 out of range for slice of length 17082
  27:     0x7fe281ad9cff - __clone
                               at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:95
  28:                0x0 - <unknown>
stack backtrace:
   0:     0x5649a795d29c - <unknown>
   1:     0x5649a79903b0 - <unknown>
   2:     0x5649a79591bf - <unknown>
   3:     0x5649a795d084 - <unknown>
   4:     0x5649a795eee7 - <unknown>
   5:     0x5649a795ec4f - <unknown>
   6:     0x5649a795f368 - <unknown>
   7:     0x5649a795f24e - <unknown>
   8:     0x5649a795d766 - <unknown>
   9:     0x5649a795efb2 - <unknown>
  10:     0x5649a69cf6b5 - <unknown>
  11:     0x5649a69cfcf2 - <unknown>
  12:     0x5649a6afde7b - <unknown>
  13:     0x5649a6afccac - <unknown>
  14:     0x5649a6b124f0 - <unknown>
  15:     0x5649a788e28e - <unknown>
  16:     0x5649a788d685 - <unknown>
  17:     0x5649a7894248 - <unknown>
  18:     0x5649a788cd68 - <unknown>
  19:     0x5649a789b7d3 - <unknown>
  20:     0x5649a78a5187 - <unknown>
  21:     0x5649a787aa2a - <unknown>
  22:     0x5649a789aa6b - <unknown>
  23:     0x5649a7889597 - <unknown>
  24:     0x5649a78a2da9 - <unknown>
  25:     0x5649a7966835 - <unknown>
  26:     0x7fe282166f07 - start_thread
                               at ./nptl/pthread_create.c:477:8
  27:     0x7fe281ad9cff - __clone
                               at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:95
  28:                0x0 - <unknown>
thread 'main' panicked at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async_http_range_reader-0.5.0/src/lib.rs:610:25:
internal error: entered unreachable code
stack backtrace:
   0:     0x5649a795d29c - <unknown>
   1:     0x5649a79903b0 - <unknown>
   2:     0x5649a79591bf - <unknown>
   3:     0x5649a795d084 - <unknown>
   4:     0x5649a795eee7 - <unknown>
   5:     0x5649a795ec4f - <unknown>
   6:     0x5649a795f368 - <unknown>
   7:     0x5649a795f219 - <unknown>
   8:     0x5649a795d766 - <unknown>
   9:     0x5649a795efb2 - <unknown>
  10:     0x5649a69cf6b5 - <unknown>
  11:     0x5649a69cf753 - <unknown>
  12:     0x5649a70bbef9 - <unknown>
  13:     0x5649a6d38ede - <unknown>
  14:     0x5649a6d342f7 - <unknown>
  15:     0x5649a6a0dd39 - <unknown>
  16:     0x5649a6d30e33 - <unknown>
  17:     0x5649a6db6fcb - <unknown>
  18:     0x5649a6db06f1 - <unknown>
  19:     0x5649a6daf7a2 - <unknown>
  20:     0x5649a6b37e84 - <unknown>
  21:     0x5649a6badf10 - <unknown>
  22:     0x5649a6c85341 - <unknown>
  23:     0x5649a6c510dc - <unknown>
  24:     0x5649a6c3c5bc - <unknown>
  25:     0x5649a6acb71f - <unknown>
  26:     0x5649a6bf7e87 - <unknown>
  27:     0x5649a6c1dd87 - <unknown>
  28:     0x5649a6c38fd2 - <unknown>
  29:     0x5649a6c13c16 - <unknown>
  30:     0x5649a6c63e56 - <unknown>
  31:     0x5649a6cd8151 - <unknown>
  32:     0x5649a6b3f0a3 - <unknown>
  33:     0x5649a6c00f69 - <unknown>
  34:     0x5649a794eba7 - <unknown>
  35:     0x5649a6c00f5e - <unknown>
  36:     0x7fe281a01d0a - __libc_start_main
                               at ./csu/../csu/libc-start.c:308:16
  37:     0x5649a69cff09 - <unknown>
  38:                0x0 - <unknown>
```

**Comment by charliermarsh** [comment]
Oooh thank you. I'm worried that this will be hard to solve without having access to the index (since it looks somewhat specific to behavior of the index), but will of course take a look and see what we can do!

**Comment by jimhendy** [comment]
+1 on this, I also experience this error when repointing `UV_INDEX_URL` to our internal artifactory pypi index.
```
range end index 339002 out of range for slice of length 335716
```

Thanks for your hard work on this awesome project!

**Comment by charliermarsh** [comment]
If anyone has a _public_ index that exhibits this behavior I'd be super grateful. It looks like maybe the index is reporting a length that doesn't match the content-length header.

**Comment by killjoy1221** [comment]
I started a free trial of artifactory and added a remote pypi repository. I've confirmed the bug is reproduced on it.

```
% uv pip install requests -i https://killjoyuvbug.jfrog.io/artifactory/api/pypi/pypi/simple 
⠦ requests==2.31.0
thread 'tokio-runtime-worker' panicked at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async_http_range_reader-0.5.0/src/lib.rs:510:19:
range end index 64965 out of range for slice of length 62574
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async_http_range_reader-0.5.0/src/lib.rs:610:25:
internal error: entered unreachable code
```

The trial has a period of 14 days and I've enabled anonymous access. You can use it to debug the issue.

Repository: https://killjoyuvbug.jfrog.io/artifactory/api/pypi/pypi/simple

**Comment by charliermarsh** [comment]
This is perfect, thank you so much!

**Comment by charliermarsh** [comment]
So far, the only thing I notice is that the server does return `"accept-ranges": "bytes"`, but then it seems to totally ignore the passed-in byte ranges? Like I can pass _anything_ for the range header, and the server gives me the same response (200, arbitrary ranges).

**Comment by charliermarsh** [comment]
Ok, it looks like Artifactory may not support range requests despite the response headers claiming to do so:

- https://github.com/pypa/pip/issues/8723
- https://jfrog.atlassian.net/browse/RTFACT-23108

That's a bummer, it'll make things much slower for Artifactory users. We'll need to update the HTTP parser to correctly error here. (Then we'll automatically fall back to downloading the entire wheel.)

**Comment by zanieb** [comment]
Related context on why range requests matter:

- https://github.com/devpi/devpi/issues/1021

Previous work on this here:

- https://github.com/astral-sh/uv/pull/702
