### ISSUE TITLE
problems building wheel for dlib

### ISSUE THREAD

**Issue by starenka** [astral-sh/uv#1475]
```
(tmp) starenka /tmp % uv pip install 'dlib==19.24.2'                                                                         
Resolved 1 package in 2ms
error: Failed to download distributions
  Caused by: Failed to fetch wheel: dlib==19.24.2
  Caused by: Failed to build: dlib==19.24.2
  Caused by: Build backend failed to build wheel through `build_wheel()`:
--- stdout:
running bdist_wheel
running build
running build_ext
Building extension for Python 3.12.2 (main, Feb  7 2024, 20:47:03) [GCC 13.2.0]
Invoking CMake setup: 'cmake /home/starenka/.cache/uv/built-wheels-v0/pypi/dlib/19.24.2/E852f7Unij9FdSd1uh9s-/dlib-19.24.2.tar.gz/tools/python -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/starenka/.cache/uv/built-wheels-v0/pypi/dlib/19.24.2/E852f7Unij9FdSd1uh9s-/dlib-19.24.2.tar.gz/build/lib.linux-x86_64-cpython-312 -DPYTHON_EXECUTABLE=/tmp/.tmpPJiyRY/.venv/bin/python -DCMAKE_BUILD_TYPE=Release'
-- pybind11 v2.10.0 
-- Found PythonInterp: /tmp/.tmpPJiyRY/.venv/bin/python (found suitable version "3.12.2", minimum required is "3.6") 
-- Found PythonLibs: python3.12
-- Using CMake version: 3.28.3
-- Compiling dlib version: 19.24.2
-- SSE4 instructions can be executed by the host processor.
-- AVX instructions can be executed by the host processor.
-- Enabling AVX instructions
-- Found system copy of libpng: /usr/lib/x86_64-linux-gnu/libpng.so;/usr/lib/x86_64-linux-gnu/libz.so
-- Found system copy of libjpeg: /usr/lib/x86_64-linux-gnu/libjpeg.so
-- Configuring done (0.8s)
-- Generating done (0.0s)
-- Build files have been written to: /home/starenka/.cache/uv/built-wheels-v0/pypi/dlib/19.24.2/E852f7Unij9FdSd1uh9s-/dlib-19.24.2.tar.gz/build/temp.linux-x86_64-cpython-312
Invoking CMake build: 'cmake --build . --config Release -- -j8'
[  1%] Linking CXX static library libdlib.a
[ 70%] Built target dlib
[ 71%] Building CXX object CMakeFiles/_dlib_pybind11.dir/src/dlib.cpp.o
[ 72%] Building CXX object CMakeFiles/_dlib_pybind11.dir/src/matrix.cpp.o
[ 73%] Building CXX object CMakeFiles/_dlib_pybind11.dir/src/vector.cpp.o
[ 75%] Building CXX object CMakeFiles/_dlib_pybind11.dir/src/svm_c_trainer.cpp.o
[ 75%] Building CXX object CMakeFiles/_dlib_pybind11.dir/src/svm_rank_trainer.cpp.o
[ 76%] Building CXX object CMakeFiles/_dlib_pybind11.dir/src/decision_functions.cpp.o
[ 77%] Building CXX object CMakeFiles/_dlib_pybind11.dir/src/other.cpp.o
[ 78%] Building CXX object CMakeFiles/_dlib_pybind11.dir/src/basic.cpp.o
--- stderr:
<string>:208: SyntaxWarning: invalid escape sequence '\('
<string>:209: SyntaxWarning: invalid escape sequence '\('
<string>:210: SyntaxWarning: invalid escape sequence '\('
CMake Deprecation Warning at /home/starenka/.cache/uv/built-wheels-v0/pypi/dlib/19.24.2/E852f7Unij9FdSd1uh9s-/dlib-19.24.2.tar.gz/dlib/external/pybind11/CMakeLists.txt:8 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


CMake Warning (dev) at /home/starenka/.cache/uv/built-wheels-v0/pypi/dlib/19.24.2/E852f7Unij9FdSd1uh9s-/dlib-19.24.2.tar.gz/dlib/external/pybind11/tools/FindPythonLibsNew.cmake:98 (find_package):
  Policy CMP0148 is not set: The FindPythonInterp and FindPythonLibs modules
  are removed.  Run "cmake --help-policy CMP0148" for policy details.  Use
  the cmake_policy command to set the policy and suppress this warning.

Call Stack (most recent call first):
  /home/starenka/.cache/uv/built-wheels-v0/pypi/dlib/19.24.2/E852f7Unij9FdSd1uh9s-/dlib-19.24.2.tar.gz/dlib/external/pybind11/tools/pybind11Tools.cmake:50 (find_package)
  /home/starenka/.cache/uv/built-wheels-v0/pypi/dlib/19.24.2/E852f7Unij9FdSd1uh9s-/dlib-19.24.2.tar.gz/dlib/external/pybind11/tools/pybind11Common.cmake:180 (include)
  /home/starenka/.cache/uv/built-wheels-v0/pypi/dlib/19.24.2/E852f7Unij9FdSd1uh9s-/dlib-19.24.2.tar.gz/dlib/external/pybind11/CMakeLists.txt:200 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

In file included from /home/starenka/.cache/uv/built-wheels-v0/pypi/dlib/19.24.2/E852f7Unij9FdSd1uh9s-/dlib-19.24.2.tar.gz/dlib/external/pybind11/include/pybind11/attr.h:13,
                 from /home/starenka/.cache/uv/built-wheels-v0/pypi/dlib/19.24.2/E852f7Unij9FdSd1uh9s-/dlib-19.24.2.tar.gz/dlib/external/pybind11/include/pybind11/detail/class.h:12,
                 from /home/starenka/.cache/uv/built-wheels-v0/pypi/dlib/19.24.2/E852f7Unij9FdSd1uh9s-/dlib-19.24.2.tar.gz/dlib/external/pybind11/include/pybind11/pybind11.h:13,
                 from /home/starenka/.cache/uv/built-wheels-v0/pypi/dlib/19.24.2/E852f7Unij9FdSd1uh9s-/dlib-19.24.2.tar.gz/dlib/../dlib/python/pybind_utils.h:6,
                 from /home/starenka/.cache/uv/built-wheels-v0/pypi/dlib/19.24.2/E852f7Unij9FdSd1uh9s-/dlib-19.24.2.tar.gz/dlib/../dlib/python.h:6,
                 from /home/starenka/.cache/uv/built-wheels-v0/pypi/dlib/19.24.2/E852f7Unij9FdSd1uh9s-/dlib-19.24.2.tar.gz/tools/python/src/opaque_types.h:6,
                 from /home/starenka/.cache/uv/built-wheels-v0/pypi/dlib/19.24.2/E852f7Unij9FdSd1uh9s-/dlib-19.24.2.tar.gz/tools/python/src/decision_functions.cpp:4:
/home/starenka/.cache/uv/built-wheels-v0/pypi/dlib/19.24.2/E852f7Unij9FdSd1uh9s-/dlib-19.24.2.tar.gz/dlib/external/pybind11/include/pybind11/detail/common.h:212:10: fatal error: Python.h: No such file or directory
  212 | #include <Python.h>
      |          ^~~~~~~~~~
In file included from /home/starenka/.cache/uv/built-wheels-v0/pypi/dlib/19.24.2/E852f7Unij9FdSd1uh9s-/dlib-19.24.2.tar.gz/dlib/external/pybind11/include/pybind11/attr.h:13,
                 from /home/starenka/.cache/uv/built-wheels-v0/pypi/dlib/19.24.2/E852f7Unij9FdSd1uh9s-/dlib-19.24.2.tar.gz/dlib/external/pybind11/include/pybind11/detail/class.h:12,
                 from /home/starenka/.cache/uv/built-wheels-v0/pypi/dlib/19.24.2/E852f7Unij9FdSd1uh9s-/dlib-19.24.2.tar.gz/dlib/external/pybind11/include/pybind11/pybind11.h:13,
                 from /home/starenka/.cache/uv/built-wheels-v0/pypi/dlib/19.24.2/E852f7Unij9FdSd1uh9s-/dlib-19.24.2.tar.gz/dlib/../dlib/python/pybind_utils.h:6,
                 from /home/starenka/.cache/uv/built-wheels-v0/pypi/dlib/19.24.2/E852f7Unij9FdSd1uh9s-/dlib-19.24.2.tar.gz/dlib/../dlib/python.h:6,
                 from /home/starenka/.cache/uv/built-wheels-v0/pypi/dlib/19.24.2/E852f7Unij9FdSd1uh9s-/dlib-19.24.2.tar.gz/tools/python/src/opaque_types.h:6,
                 from /home/starenka/.cache/uv/built-wheels-v0/pypi/dlib/19.24.2/E852f7Unij9FdSd1uh9s-/dlib-19.24.2.tar.gz/tools/python/src/svm_rank_trainer.cpp:4:
/home/starenka/.cache/uv/built-wheels-v0/pypi/dlib/19.24.2/E852f7Unij9FdSd1uh9s-/dlib-19.24.2.tar.gz/dlib/external/pybind11/include/pybind11/detail/common.h:212:10: fatal error: Python.h: No such file or directory
  212 | #include <Python.h>
      |          ^~~~~~~~~~
In file included from /home/starenka/.cache/uv/built-wheels-v0/pypi/dlib/19.24.2/E852f7Unij9FdSd1uh9s-/dlib-19.24.2.tar.gz/dlib/external/pybind11/include/pybind11/attr.h:13,
                 from /home/starenka/.cache/uv/built-wheels-v0/pypi/dlib/19.24.2/E852f7Unij9FdSd1uh9s-/dlib-19.24.2.tar.gz/dlib/external/pybind11/include/pybind11/detail/class.h:12,
                 from /home/starenka/.cache/uv/built-wheels-v0/pypi/dlib/19.24.2/E852f7Unij9FdSd1uh9s-/dlib-19.24.2.tar.gz/dlib/external/pybind11/include/pybind11/pybind11.h:13,
                 from /home/starenka/.cache/uv/built-wheels-v0/pypi/dlib/19.24.2/E852f7Unij9FdSd1uh9s-/dlib-19.24.2.tar.gz/dlib/../dlib/python/pybind_utils.h:6,
                 from /home/starenka/.cache/uv/built-wheels-v0/pypi/dlib/19.24.2/E852f7Unij9FdSd1uh9s-/dlib-19.24.2.tar.gz/dlib/../dlib/python.h:6,
                 from /home/starenka/.cache/uv/built-wheels-v0/pypi/dlib/19.24.2/E852f7Unij9FdSd1uh9s-/dlib-19.24.2.tar.gz/tools/python/src/opaque_types.h:6,
                 from /home/starenka/.cache/uv/built-wheels-v0/pypi/dlib/19.24.2/E852f7Unij9FdSd1uh9s-/dlib-19.24.2.tar.gz/tools/python/src/svm_c_trainer.cpp:4:
/home/starenka/.cache/uv/built-wheels-v0/pypi/dlib/19.24.2/E852f7Unij9FdSd1uh9s-/dlib-19.24.2.tar.gz/dlib/external/pybind11/include/pybind11/detail/common.h:212:10: fatal error: Python.h: No such file or directory
  212 | #include <Python.h>
      |          ^~~~~~~~~~
In file included from /home/starenka/.cache/uv/built-wheels-v0/pypi/dlib/19.24.2/E852f7Unij9FdSd1uh9s-/dlib-19.24.2.tar.gz/dlib/external/pybind11/include/pybind11/attr.h:13,
                 from /home/starenka/.cache/uv/built-wheels-v0/pypi/dlib/19.24.2/E852f7Unij9FdSd1uh9s-/dlib-19.24.2.tar.gz/dlib/external/pybind11/include/pybind11/detail/class.h:12,
                 from /home/starenka/.cache/uv/built-wheels-v0/pypi/dlib/19.24.2/E852f7Unij9FdSd1uh9s-/dlib-19.24.2.tar.gz/dlib/external/pybind11/include/pybind11/pybind11.h:13,
                 from /home/starenka/.cache/uv/built-wheels-v0/pypi/dlib/19.24.2/E852f7Unij9FdSd1uh9s-/dlib-19.24.2.tar.gz/dlib/../dlib/python/pybind_utils.h:6,
                 from /home/starenka/.cache/uv/built-wheels-v0/pypi/dlib/19.24.2/E852f7Unij9FdSd1uh9s-/dlib-19.24.2.tar.gz/dlib/../dlib/python.h:6,
                 from /home/starenka/.cache/uv/built-wheels-v0/pypi/dlib/19.24.2/E852f7Unij9FdSd1uh9s-/dlib-19.24.2.tar.gz/tools/python/src/opaque_types.h:6,
                 from /home/starenka/.cache/uv/built-wheels-v0/pypi/dlib/19.24.2/E852f7Unij9FdSd1uh9s-/dlib-19.24.2.tar.gz/tools/python/src/vector.cpp:4:
/home/starenka/.cache/uv/built-wheels-v0/pypi/dlib/19.24.2/E852f7Unij9FdSd1uh9s-/dlib-19.24.2.tar.gz/dlib/external/pybind11/include/pybind11/detail/common.h:212:10: fatal error: Python.h: No such file or directory
  212 | #include <Python.h>
      |          ^~~~~~~~~~
compilation terminated.
compilation terminated.
compilation terminated.
compilation terminated.
In file included from /home/starenka/.cache/uv/built-wheels-v0/pypi/dlib/19.24.2/E852f7Unij9FdSd1uh9s-/dlib-19.24.2.tar.gz/dlib/external/pybind11/include/pybind11/attr.h:13,
                 from /home/starenka/.cache/uv/built-wheels-v0/pypi/dlib/19.24.2/E852f7Unij9FdSd1uh9s-/dlib-19.24.2.tar.gz/dlib/external/pybind11/include/pybind11/detail/class.h:12,
                 from /home/starenka/.cache/uv/built-wheels-v0/pypi/dlib/19.24.2/E852f7Unij9FdSd1uh9s-/dlib-19.24.2.tar.gz/dlib/external/pybind11/include/pybind11/pybind11.h:13,
                 from /home/starenka/.cache/uv/built-wheels-v0/pypi/dlib/19.24.2/E852f7Unij9FdSd1uh9s-/dlib-19.24.2.tar.gz/dlib/../dlib/python/pybind_utils.h:6,
                 from /home/starenka/.cache/uv/built-wheels-v0/pypi/dlib/19.24.2/E852f7Unij9FdSd1uh9s-/dlib-19.24.2.tar.gz/dlib/../dlib/python.h:6,
                 from /home/starenka/.cache/uv/built-wheels-v0/pypi/dlib/19.24.2/E852f7Unij9FdSd1uh9s-/dlib-19.24.2.tar.gz/tools/python/src/basic.cpp:3:
/home/starenka/.cache/uv/built-wheels-v0/pypi/dlib/19.24.2/E852f7Unij9FdSd1uh9s-/dlib-19.24.2.tar.gz/dlib/external/pybind11/include/pybind11/detail/common.h:212:10: fatal error: Python.h: No such file or directory
  212 | #include <Python.h>
      |          ^~~~~~~~~~
compilation terminated.
In file included from /home/starenka/.cache/uv/built-wheels-v0/pypi/dlib/19.24.2/E852f7Unij9FdSd1uh9s-/dlib-19.24.2.tar.gz/dlib/external/pybind11/include/pybind11/attr.h:13,
                 from /home/starenka/.cache/uv/built-wheels-v0/pypi/dlib/19.24.2/E852f7Unij9FdSd1uh9s-/dlib-19.24.2.tar.gz/dlib/external/pybind11/include/pybind11/detail/class.h:12,
                 from /home/starenka/.cache/uv/built-wheels-v0/pypi/dlib/19.24.2/E852f7Unij9FdSd1uh9s-/dlib-19.24.2.tar.gz/dlib/external/pybind11/include/pybind11/pybind11.h:13,
                 from /home/starenka/.cache/uv/built-wheels-v0/pypi/dlib/19.24.2/E852f7Unij9FdSd1uh9s-/dlib-19.24.2.tar.gz/dlib/../dlib/python/pybind_utils.h:6,
                 from /home/starenka/.cache/uv/built-wheels-v0/pypi/dlib/19.24.2/E852f7Unij9FdSd1uh9s-/dlib-19.24.2.tar.gz/dlib/../dlib/python.h:6,
                 from /home/starenka/.cache/uv/built-wheels-v0/pypi/dlib/19.24.2/E852f7Unij9FdSd1uh9s-/dlib-19.24.2.tar.gz/tools/python/src/opaque_types.h:6,
                 from /home/starenka/.cache/uv/built-wheels-v0/pypi/dlib/19.24.2/E852f7Unij9FdSd1uh9s-/dlib-19.24.2.tar.gz/tools/python/src/other.cpp:4:
/home/starenka/.cache/uv/built-wheels-v0/pypi/dlib/19.24.2/E852f7Unij9FdSd1uh9s-/dlib-19.24.2.tar.gz/dlib/external/pybind11/include/pybind11/detail/common.h:212:10: fatal error: Python.h: No such file or directory
  212 | #include <Python.h>
      |          ^~~~~~~~~~
compilation terminated.
In file included from /home/starenka/.cache/uv/built-wheels-v0/pypi/dlib/19.24.2/E852f7Unij9FdSd1uh9s-/dlib-19.24.2.tar.gz/dlib/external/pybind11/include/pybind11/attr.h:13,
                 from /home/starenka/.cache/uv/built-wheels-v0/pypi/dlib/19.24.2/E852f7Unij9FdSd1uh9s-/dlib-19.24.2.tar.gz/dlib/external/pybind11/include/pybind11/detail/class.h:12,
                 from /home/starenka/.cache/uv/built-wheels-v0/pypi/dlib/19.24.2/E852f7Unij9FdSd1uh9s-/dlib-19.24.2.tar.gz/dlib/external/pybind11/include/pybind11/pybind11.h:13,
                 from /home/starenka/.cache/uv/built-wheels-v0/pypi/dlib/19.24.2/E852f7Unij9FdSd1uh9s-/dlib-19.24.2.tar.gz/dlib/../dlib/python/pybind_utils.h:6,
                 from /home/starenka/.cache/uv/built-wheels-v0/pypi/dlib/19.24.2/E852f7Unij9FdSd1uh9s-/dlib-19.24.2.tar.gz/dlib/../dlib/python.h:6,
                 from /home/starenka/.cache/uv/built-wheels-v0/pypi/dlib/19.24.2/E852f7Unij9FdSd1uh9s-/dlib-19.24.2.tar.gz/tools/python/src/opaque_types.h:6,
                 from /home/starenka/.cache/uv/built-wheels-v0/pypi/dlib/19.24.2/E852f7Unij9FdSd1uh9s-/dlib-19.24.2.tar.gz/tools/python/src/matrix.cpp:4:
/home/starenka/.cache/uv/built-wheels-v0/pypi/dlib/19.24.2/E852f7Unij9FdSd1uh9s-/dlib-19.24.2.tar.gz/dlib/external/pybind11/include/pybind11/detail/common.h:212:10: fatal error: Python.h: No such file or directory
  212 | #include <Python.h>
      |          ^~~~~~~~~~
compilation terminated.
gmake[2]: *** [CMakeFiles/_dlib_pybind11.dir/build.make:132: CMakeFiles/_dlib_pybind11.dir/src/svm_rank_trainer.cpp.o] Error 1
gmake[2]: *** Waiting for unfinished jobs....
gmake[2]: *** [CMakeFiles/_dlib_pybind11.dir/build.make:104: CMakeFiles/_dlib_pybind11.dir/src/vector.cpp.o] Error 1
gmake[2]: *** [CMakeFiles/_dlib_pybind11.dir/build.make:118: CMakeFiles/_dlib_pybind11.dir/src/svm_c_trainer.cpp.o] Error 1
gmake[2]: *** [CMakeFiles/_dlib_pybind11.dir/build.make:146: CMakeFiles/_dlib_pybind11.dir/src/decision_functions.cpp.o] Error 1
gmake[2]: *** [CMakeFiles/_dlib_pybind11.dir/build.make:174: CMakeFiles/_dlib_pybind11.dir/src/basic.cpp.o] Error 1
gmake[2]: *** [CMakeFiles/_dlib_pybind11.dir/build.make:160: CMakeFiles/_dlib_pybind11.dir/src/other.cpp.o] Error 1
gmake[2]: *** [CMakeFiles/_dlib_pybind11.dir/build.make:90: CMakeFiles/_dlib_pybind11.dir/src/matrix.cpp.o] Error 1
In file included from /home/starenka/.cache/uv/built-wheels-v0/pypi/dlib/19.24.2/E852f7Unij9FdSd1uh9s-/dlib-19.24.2.tar.gz/dlib/external/pybind11/include/pybind11/attr.h:13,
                 from /home/starenka/.cache/uv/built-wheels-v0/pypi/dlib/19.24.2/E852f7Unij9FdSd1uh9s-/dlib-19.24.2.tar.gz/dlib/external/pybind11/include/pybind11/detail/class.h:12,
                 from /home/starenka/.cache/uv/built-wheels-v0/pypi/dlib/19.24.2/E852f7Unij9FdSd1uh9s-/dlib-19.24.2.tar.gz/dlib/external/pybind11/include/pybind11/pybind11.h:13,
                 from /home/starenka/.cache/uv/built-wheels-v0/pypi/dlib/19.24.2/E852f7Unij9FdSd1uh9s-/dlib-19.24.2.tar.gz/dlib/../dlib/python/pybind_utils.h:6,
                 from /home/starenka/.cache/uv/built-wheels-v0/pypi/dlib/19.24.2/E852f7Unij9FdSd1uh9s-/dlib-19.24.2.tar.gz/dlib/../dlib/python.h:6,
                 from /home/starenka/.cache/uv/built-wheels-v0/pypi/dlib/19.24.2/E852f7Unij9FdSd1uh9s-/dlib-19.24.2.tar.gz/tools/python/src/opaque_types.h:6,
                 from /home/starenka/.cache/uv/built-wheels-v0/pypi/dlib/19.24.2/E852f7Unij9FdSd1uh9s-/dlib-19.24.2.tar.gz/tools/python/src/dlib.cpp:4:
/home/starenka/.cache/uv/built-wheels-v0/pypi/dlib/19.24.2/E852f7Unij9FdSd1uh9s-/dlib-19.24.2.tar.gz/dlib/external/pybind11/include/pybind11/detail/common.h:212:10: fatal error: Python.h: No such file or directory
  212 | #include <Python.h>
      |          ^~~~~~~~~~
compilation terminated.
gmake[2]: *** [CMakeFiles/_dlib_pybind11.dir/build.make:76: CMakeFiles/_dlib_pybind11.dir/src/dlib.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:118: CMakeFiles/_dlib_pybind11.dir/all] Error 2
gmake: *** [Makefile:91: all] Error 2
Traceback (most recent call last):
  File "<string>", line 6, in <module>
  File "/tmp/.tmpPJiyRY/.venv/lib/python3.12/site-packages/setuptools/build_meta.py", line 404, in build_wheel
    return self._build_with_temp_dir(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/.tmpPJiyRY/.venv/lib/python3.12/site-packages/setuptools/build_meta.py", line 389, in _build_with_temp_dir
    self.run_setup()
  File "/tmp/.tmpPJiyRY/.venv/lib/python3.12/site-packages/setuptools/build_meta.py", line 311, in run_setup
    exec(code, locals())
  File "<string>", line 218, in <module>
  File "/tmp/.tmpPJiyRY/.venv/lib/python3.12/site-packages/setuptools/__init__.py", line 103, in setup
    return distutils.core.setup(**attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/.tmpPJiyRY/.venv/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
           ^^^^^^^^^^^^^^^^^^
  File "/tmp/.tmpPJiyRY/.venv/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/tmp/.tmpPJiyRY/.venv/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/tmp/.tmpPJiyRY/.venv/lib/python3.12/site-packages/setuptools/dist.py", line 963, in run_command
    super().run_command(command)
  File "/tmp/.tmpPJiyRY/.venv/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/tmp/.tmpPJiyRY/.venv/lib/python3.12/site-packages/wheel/bdist_wheel.py", line 368, in run
    self.run_command("build")
  File "/tmp/.tmpPJiyRY/.venv/lib/python3.12/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/tmp/.tmpPJiyRY/.venv/lib/python3.12/site-packages/setuptools/dist.py", line 963, in run_command
    super().run_command(command)
  File "/tmp/.tmpPJiyRY/.venv/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/tmp/.tmpPJiyRY/.venv/lib/python3.12/site-packages/setuptools/_distutils/command/build.py", line 131, in run
    self.run_command(cmd_name)
  File "/tmp/.tmpPJiyRY/.venv/lib/python3.12/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/tmp/.tmpPJiyRY/.venv/lib/python3.12/site-packages/setuptools/dist.py", line 963, in run_command
    super().run_command(command)
  File "/tmp/.tmpPJiyRY/.venv/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "<string>", line 130, in run
  File "<string>", line 170, in build_extension
  File "/usr/lib/python3.12/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '-j8']' returned non-zero exit status 2.
```

**Comment by akx** [comment]
Did you try the same build with a plain `pip install 'dlib==19.24.2'`? By the looks of it, you don't have the Python development files installed.

**Comment by starenka** [comment]
my bad, debian seems to have sneakily uninstalled my `python3.12-dev` package, sorry. I haven't tried it before submitting as i already have env with this installed so i knew it worked back then with pip.
