### ISSUE TITLE
uv pip install is unable to locate wheels built with pip wheel --no-binary

### ISSUE THREAD

**Issue by radupotop** [astral-sh/uv#1706]
I have a private wheelhouse where wheels are compiled with:

```
pip wheel  -r requirements.txt --no-binary psycopg2,uwsgi
```

In order to compile `psycopg2` and `uwsgi`  for the target system, and not use the prebuilt binaries.

My issue is that `uv` is unable to locate the wheels for `psycopg2` and `uwsgi` and insists on compiling them every time.  
That fails because there's no gcc on the running system (only on the build system).

<details>
<summary><b>Error message below</b></summary>

```
2.364 Resolved 199 packages in 1.93s                                                                                          
5.957 error: Failed to download distributions                                                                                 
5.957   Caused by: Failed to fetch wheel: uwsgi==2.0.20                                                                       
5.957   Caused by: Failed to build: uwsgi==2.0.20                                                                             
5.957   Caused by: Build backend failed to build wheel through `build_wheel()`:
5.957 --- stdout:
5.957 running bdist_wheel
5.957 running build
5.957 running build_py
5.957 creating build
5.957 creating build/lib
5.957 copying uwsgidecorators.py -> build/lib
5.957 installing to build/bdist.linux-x86_64/wheel
5.957 running install
5.957 using profile: buildconf/default.ini
5.957 detected include path: ['/usr/include', '/usr/local/include']
5.957 --- stderr:
5.957 /root/.cache/uv/.tmpJQFW30/.venv/lib/python3.10/site-packages/setuptools/_distutils/dist.py:265: UserWarning: Unknown distribution option: 'descriptions'
5.957   warnings.warn(msg)
5.957 Traceback (most recent call last):
5.957   File "/root/.cache/uv/built-wheels-v0/pypi/uwsgi/2.0.20/xUKlaAbW3ViL6rzb5viBY/uwsgi-2.0.20.tar.gz/uwsgiconfig.py", line 750, in __init__
5.957     gcc_version_components = gcc_version.split('.')
5.957 AttributeError: 'NoneType' object has no attribute 'split'
5.957 
5.957 During handling of the above exception, another exception occurred:
5.957 
5.957 Traceback (most recent call last):
5.957   File "<string>", line 6, in <module>
5.957   File "/root/.cache/uv/.tmpJQFW30/.venv/lib/python3.10/site-packages/setuptools/build_meta.py", line 404, in build_wheel
5.957     return self._build_with_temp_dir(
5.957   File "/root/.cache/uv/.tmpJQFW30/.venv/lib/python3.10/site-packages/setuptools/build_meta.py", line 389, in _build_with_temp_dir
5.957     self.run_setup()
5.957   File "/root/.cache/uv/.tmpJQFW30/.venv/lib/python3.10/site-packages/setuptools/build_meta.py", line 480, in run_setup
5.957     super().run_setup(setup_script=setup_script)
5.957   File "/root/.cache/uv/.tmpJQFW30/.venv/lib/python3.10/site-packages/setuptools/build_meta.py", line 311, in run_setup
5.957     exec(code, locals())
5.957   File "<string>", line 117, in <module>
5.957   File "/root/.cache/uv/.tmpJQFW30/.venv/lib/python3.10/site-packages/setuptools/__init__.py", line 103, in setup
5.957     return distutils.core.setup(**attrs)
5.957   File "/root/.cache/uv/.tmpJQFW30/.venv/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
5.957     return run_commands(dist)
5.957   File "/root/.cache/uv/.tmpJQFW30/.venv/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
5.957     dist.run_commands()
5.957   File "/root/.cache/uv/.tmpJQFW30/.venv/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
5.957     self.run_command(cmd)
5.957   File "/root/.cache/uv/.tmpJQFW30/.venv/lib/python3.10/site-packages/setuptools/dist.py", line 963, in run_command
5.957     super().run_command(command)
5.957   File "/root/.cache/uv/.tmpJQFW30/.venv/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
5.957     cmd_obj.run()
5.957   File "/root/.cache/uv/.tmpJQFW30/.venv/lib/python3.10/site-packages/wheel/bdist_wheel.py", line 403, in run
5.957     self.run_command("install")
5.957   File "/root/.cache/uv/.tmpJQFW30/.venv/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
5.957     self.distribution.run_command(command)
5.957   File "/root/.cache/uv/.tmpJQFW30/.venv/lib/python3.10/site-packages/setuptools/dist.py", line 963, in run_command
5.957     super().run_command(command)
5.957   File "/root/.cache/uv/.tmpJQFW30/.venv/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
5.957     cmd_obj.run()
5.957   File "<string>", line 77, in run
5.957   File "/root/.cache/uv/built-wheels-v0/pypi/uwsgi/2.0.20/xUKlaAbW3ViL6rzb5viBY/uwsgi-2.0.20.tar.gz/uwsgiconfig.py", line 758, in __init__
5.957     raise Exception("you need a C compiler to build uWSGI")
5.957 Exception: you need a C compiler to build uWSGI
5.957 ---
------
```
</details>

But it works fine when I do:

```
uv pip install psycopg2@https://wheelhouse.example.org/psycopg2-2.9.x-cp310-cp310-linux_x86_64.whl
```

Any ideas how i could sort this out? Thanks

**Comment by zanieb** [comment]
How are you pointing uv to your private wheelhouse?

**Comment by radupotop** [comment]
So the wheelhouse is a flat list of links (i.e. a folder with an `index.html` page) to be used with  
`pip install --find-links`.

I tried the following and it works fine:

```
uv pip install --verbose --find-links $INDEX_URL --no-index -r requirements.txt
```

For some reason i was expecting the `PIP_FIND_LINKS` and `PIP_NO_INDEX` env vars to be picked up.
