### ISSUE TITLE
Workspace package name clash with builtins - when uv is enabled

### ISSUE THREAD

**Issue by mihalikv** [astral-sh/uv#1972]
### Steps to Reproduce

1. clone repository https://github.com/mihalikv/improved-umbrella
2. run `rye sync`

### Expected Result

**With uv**: successful installation

### Actual Result

When **uv** is disabled: it just works.

When **uv** is enabled:
```
vilo@Vilo:~/test_project$ rye sync
Reusing already existing virtualenv
Generating production lockfile: /home/vilo/test_project/requirements.lock
error: Failed to build editables
  Caused by: Failed to build editable: file:///home/vilo/test_project/nested_lib
  Caused by: Build backend failed to build wheel through `build_editable()`:
--- stdout:

--- stderr:
Traceback (most recent call last):
  File "<string>", line 6, in <module>
  File "/home/vilo/.cache/uv/.tmp30t7GI/.venv/lib/python3.11/site-packages/hatchling/build.py", line 82, in build_editable
    return os.path.basename(next(builder.build(directory=wheel_directory, versions=['editable'])))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vilo/.cache/uv/.tmp30t7GI/.venv/lib/python3.11/site-packages/hatchling/builders/plugin/interface.py", line 90, in build
    self.metadata.validate_fields()
  File "/home/vilo/.cache/uv/.tmp30t7GI/.venv/lib/python3.11/site-packages/hatchling/metadata/core.py", line 244, in validate_fields
    self.core.validate_fields()
  File "/home/vilo/.cache/uv/.tmp30t7GI/.venv/lib/python3.11/site-packages/hatchling/metadata/core.py", line 1334, in validate_fields
    getattr(self, attribute)
  File "/home/vilo/.cache/uv/.tmp30t7GI/.venv/lib/python3.11/site-packages/hatchling/metadata/core.py", line 1207, in dependencies
    self._dependencies = list(self.dependencies_complex)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vilo/.cache/uv/.tmp30t7GI/.venv/lib/python3.11/site-packages/hatchling/metadata/core.py", line 1158, in dependencies_complex
    from packaging.requirements import InvalidRequirement, Requirement
  File "/home/vilo/.cache/uv/.tmp30t7GI/.venv/lib/python3.11/site-packages/packaging/requirements.py", line 7, in <module>
    from ._parser import parse_requirement as _parse_requirement
  File "/home/vilo/.cache/uv/.tmp30t7GI/.venv/lib/python3.11/site-packages/packaging/_parser.py", line 10, in <module>
    from ._tokenizer import DEFAULT_RULES, Tokenizer
  File "/home/vilo/.cache/uv/.tmp30t7GI/.venv/lib/python3.11/site-packages/packaging/_tokenizer.py", line 6, in <module>    from .specifiers import Specifier
  File "/home/vilo/.cache/uv/.tmp30t7GI/.venv/lib/python3.11/site-packages/packaging/specifiers.py", line 26, in <module>
    from .utils import canonicalize_version
  File "/home/vilo/.cache/uv/.tmp30t7GI/.venv/lib/python3.11/site-packages/packaging/utils.py", line 8, in <module>
    from .tags import Tag, parse_tag
  File "/home/vilo/.cache/uv/.tmp30t7GI/.venv/lib/python3.11/site-packages/packaging/tags.py", line 27, in <module>
    logger = logging.getLogger(__name__)
             ^^^^^^^^^^^^^^^^^
AttributeError: module 'logging' has no attribute 'getLogger'
---
error: could not write production lockfile for workspace

Caused by:
    failed to generate lockfile
```

### Version Info

```
rye 0.26.0
commit: 0.26.0 (d245f625e 2024-02-23)
platform: linux (x86_64)
self-python: cpython@3.12
symlink support: true
uv enabled: false
```

**Comment by charliermarsh** [comment]
Thanks!

**Comment by charliermarsh** [comment]
Not clear to me yet why this works with `pip`. The hook is called with `./improved-umbrella/nested_lib` as the current working directory, and Python adds the current working directory to the path.

**Comment by charliermarsh** [comment]
@henryiii -- do you know have an understanding of why this works? `./improved-umbrella/nested_lib` contains a module called `logging`, which the build backend is importing while building.

`python -m build .` fails in that directory, but `python -m build nested_lib` succeeds from the parent.

**Comment by charliermarsh** [comment]
I see some code in `pip` to avoid adding the current working directory:

```python
# Remove '' and current working directory from the first entry
# of sys.path, if present to avoid using current directory
# in pip commands check, freeze, install, list and show,
# when invoked as python -m pip <command>
if sys.path[0] in ("", os.getcwd()):
    sys.path.pop(0)
```

I guess that would end up affecting pip's PEP 517 builds, assuming they happen in the same process?

**Comment by henryiii** [comment]
The current directory should not be present unless the build backend adds it. Setuptools.build_meta does not, while setuptools.build_meta.__legacy__ does.

I believe you can't stop Python from adding the current directory (before/without PYTHONSAFEPATH) in module mode, so you'd probably need a hack like pip's, which build might miss. But I'd have to check the package build backend first (on phone).

**Comment by charliermarsh** [comment]
This makes sense. So we need to set the current directory, but avoid adding it to the path. (I’m not totally sure how pip avoids this since that code is in __main__.py, which I thought only ran when invoked via python -m.)

**Comment by henryiii** [comment]
If you run “pytest”, then the current directory is not added to the path. But if you run `python -m pytest`, it is there (added by Python). You can try it out, pytest does not try to filter it. Pretty sure we don’t in build either.

**Comment by henryiii** [comment]
This is an extremely rare issue for building packages, since most tools would expect to install “logging” as a top level package, which would clash with the std lib. A subpackage logging is fine, but not a top level one (in a wheel).

**Comment by henryiii** [comment]
Easiest way to fix this actually is to run `python -Im build`.
