### ISSUE TITLE
uv pip install halo fails

### ISSUE THREAD

**Issue by marvin8** [astral-sh/uv#2290]
I am unable to install the package `halo` in my docker image based on Alpine linux

When I try to run `uv pip install halo` in my docker image based on Alpine linux, the install fails with the error message below:

```
Resolved 6 packages in 1.10s
error: Failed to download distributions
  Caused by: Failed to fetch wheel: halo==0.0.31
  Caused by: Failed to build: halo==0.0.31
  Caused by: Build backend failed to build wheel through `build_wheel()`:
--- stdout:

--- stderr:
/root/.cache/uv/.tmpf8murB/.venv/lib/python3.12/site-packages/setuptools/dist.py:472: SetuptoolsDeprecationWarning: Invalid dash-separated options
!!

        ********************************************************************************
        Usage of dash-separated 'description-file' will not be supported in future
        versions. Please use the underscore name 'description_file' instead.

        By 2024-Sep-26, you need to update your project and remove deprecated calls
        or your builds will no longer be supported.

        See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
        ********************************************************************************

!!
  opt = self.warn_dash_deprecation(opt, section)
Traceback (most recent call last):
  File "<string>", line 11, in <module>
  File "/root/.cache/uv/.tmpf8murB/.venv/lib/python3.12/site-packages/setuptools/build_meta.py", line 410, in build_wheel
    return self._build_with_temp_dir(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/uv/.tmpf8murB/.venv/lib/python3.12/site-packages/setuptools/build_meta.py", line 395, in _build_with_temp_dir
    self.run_setup()
  File "/root/.cache/uv/.tmpf8murB/.venv/lib/python3.12/site-packages/setuptools/build_meta.py", line 487, in run_setup
    super().run_setup(setup_script=setup_script)
  File "/root/.cache/uv/.tmpf8murB/.venv/lib/python3.12/site-packages/setuptools/build_meta.py", line 311, in run_setup
    exec(code, locals())
  File "<string>", line 16, in <module>
  File "/root/.cache/uv/.tmpf8murB/.venv/lib/python3.12/site-packages/setuptools/__init__.py", line 103, in setup
    return distutils.core.setup(**attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/uv/.tmpf8murB/.venv/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 172, in setup
    ok = dist.parse_command_line()
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/uv/.tmpf8murB/.venv/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 475, in parse_command_line
    args = self._parse_command_opts(parser, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/uv/.tmpf8murB/.venv/lib/python3.12/site-packages/setuptools/dist.py", line 865, in _parse_command_opts
    nargs = _Distribution._parse_command_opts(self, parser, args)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/uv/.tmpf8murB/.venv/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 534, in _parse_command_opts
    cmd_class = self.get_command_class(command)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/uv/.tmpf8murB/.venv/lib/python3.12/site-packages/setuptools/dist.py", line 710, in get_command_class
    self.cmdclass[command] = cmdclass = ep.load()
                                        ^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/metadata/__init__.py", line 205, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/root/.cache/uv/.tmpf8murB/.venv/lib/python3.12/site-packages/wheel/bdist_wheel.py", line 27, in <module>
    from .macosx_libfile import calculate_macosx_platform_tag
  File "/root/.cache/uv/.tmpf8murB/.venv/lib/python3.12/site-packages/wheel/macosx_libfile.py", line 43, in <module>
    import ctypes
  File "/usr/local/lib/python3.12/ctypes/__init__.py", line 8, in <module>
    from _ctypes import Union, Structure, Array
ModuleNotFoundError: No module named '_ctypes'
---
```

Is this something I need to take up with the maintainers of [`halo`](https://github.com/manrajgrover/halo) or is this something `uv` can fix?

Maybe I am missing some dependency in my Alpine based image?

**Comment by charliermarsh** [comment]
@konstin - Do you mind taking a look at this one?

**Comment by marvin8** [comment]
As I was typing I noticed a new version of `uv` has been release. I can confirm that the new version 0.1.16 is failing in the same way.

**Comment by charliermarsh** [comment]
Just to confirm, is `pip` able to install the package without error?

**Comment by marvin8** [comment]
Actually... no, `python3 -m pip install halo` does not install either with very similar error.

Must be an issue with the package then.

I'll close this issue, doesn't seem to be `uv` related... sorry for the bother.
