### ISSUE TITLE
`uv run` fails on centos 7

### ISSUE THREAD

**Issue by konstin** [astral-sh/uv#3371]
We need to exit early if the python version is lower than 3.7.

```
$ uv run
warning: `uv run` is experimental and may change without warning.
error: Querying Python at `/usr/bin/python3` failed with status exit status: 1 with exit status: 1
--- stdout:

--- stderr:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/user/.cache/uv/.tmp9nBPgP/python/get_interpreter_info.py", line 536, in main
    "platform": get_operating_system_and_architecture(),
  File "/home/user/.cache/uv/.tmp9nBPgP/python/get_interpreter_info.py", line 439, in get_operating_system_and_architecture
    from .packaging._manylinux import _get_glibc_version
  File "/home/user/.cache/uv/.tmp9nBPgP/python/packaging/_manylinux.py", line 1
    from __future__ import annotations
    ^
SyntaxError: future feature annotations is not defined
---
```

`/usr/bin/python3 --version`: `Python 3.6.8`

**Comment by charliermarsh** [comment]
Not really sure what the right behavior is here -- just a better error message?

**Comment by zanieb** [comment]
Yeah I think interpreter queries should fail with a better error message.

**Comment by samypr100** [comment]
Note Centos 7 will be EOL soon (June 2024)
To install modern versions of python on it I've had resort to building from source.
