### ISSUE TITLE
AttributeError: '_BuildMetaLegacyBackend' object has no attribute 'build_editable'

### ISSUE THREAD

**Issue by adminy** [astral-sh/uv#3459]
I have a pyproject.toml with a couple of optional dependencies.

When running:
```bash
uv pip install -e '.[dep1,dep2,dep3,dep4]' --exclude-newer 2020-12-02

error: Failed to build editables
  Caused by: Failed to build editable: file:///root/repos/MyProject
  Caused by: Build backend failed to build wheel through `build_editable()` with exit status: 1
--- stdout:

--- stderr:
Traceback (most recent call last):
  File "<string>", line 11, in <module>
AttributeError: '_BuildMetaLegacyBackend' object has no attribute 'build_editable'
```

**Comment by charliermarsh** [comment]
@konstin - do you know what the root cause is here?

**Comment by konstin** [comment]
I'm pretty sure the backend doesn't not support editable builds (PEP 660). We should catch this and show a better error message. We may also need to implement extra behavior for setuptools, needs to be investigated

**Comment by charliermarsh** [comment]
@adminy - Do you know what build backend this is using?

**Comment by kimdwkimdw** [comment]
Any updates?

**Comment by scotgopal** [comment]
I faced this issue as well. The build backend is `setuptools`.

**Comment by konstin** [comment]
What version of setuptools are you using?

**Comment by scotgopal** [comment]
> What version of setuptools are you using? What does your `pyproject.toml` look like?

I am currently using `setup.py`, not a pyproject.toml. The version of setuptools is v59.8.0. I don't have the setup.py with me, atm. Will update this comment when available.

**Comment by ayjayt** [comment]
nb I'm also having issues with this, can't reproduce, only occurs for one project where i tried to run mypy w/ an editable source (using the LEGACY env var that doesn't work anymore), and now no sync works at all... doing a full re-install

**Comment by scotgopal** [comment]
Ah a full year it has been.. and I am finally coming back to this topic. Here is the `setup.py` content of my project. To give you context, it is a package built with/for ROS1 (Noetic) based software stack. The following also describes some other (possibly) relevant information.

- Python 3.8.10
- Ubuntu 20.04
- uv 0.10.8
- setuptools 59.8.0
- Not using `pyproject.toml`

```python
from setuptools import setup, find_packages
from catkin_pkg.python_setup import generate_distutils_setup


PACKAGE_NAME = "data_management"

with open("requirements.txt", "r", encoding="utf-8") as f:
    install_deps = [line.strip() for line in f if line.strip()]

setup_args = generate_distutils_setup(
    package_xml_path="package.xml",
    packages=find_packages(where="src"),
    package_dir={"": "src"},
    python_requires=">=3.8",
    data_files=[
        (f"share/{PACKAGE_NAME}", ["package.xml", "requirements.txt"])
    ],
    install_requires=install_deps,
)

setup(**setup_args)
```

This error is seen especially when I use `--no-build-isolation` flag.

```bash
# uv self version
uv 0.10.8

# uv pip install -e data_management/ --dry-run --no-build-isolation
Using Python 3.8.10 environment at: /venv
  × Failed to build `data-management @ file:///data_management`
  ├─▶ The build backend returned an error
  ╰─▶ Call to `setuptools.build_meta:__legacy__.build_editable` failed (exit
      status: 1)

      [stderr]
      Traceback (most recent call last):
        File "<string>", line 11, in <module>
      AttributeError: '_BuildMetaLegacyBackend' object has no attribute
      'build_editable'

      hint: This usually indicates a problem with the package or the build
      environment.
```

**Comment by konstin** [comment]
You're requesting an editable build with `-e`, but the build backend setup you're using doesn't support editable installs. Updating to more recent versions of Python and setuptools and well as using a `pyproject.toml` with a `[build-system]` table should solve this.

**Comment by scotgopal** [comment]
> You're requesting an editable build with `-e`, but the build backend setup you're using doesn't support editable installs. Updating to more recent versions of Python and setuptools and well as using a `pyproject.toml` with a `[build-system]` table should solve this.

Ah so, I didn't know that. But editable installs seems to work with `pip>=24,<=25.0.1`.
