### ISSUE TITLE
Improve message when distutil is not available on legacy python. 

### ISSUE THREAD

**Issue by mgaitan** [astral-sh/uv#4204]
I use a local venv in python3.10 but compile requirements for python 3.8 (requirements used for dockerized apps) . I have both versions (along the default python 3.12) installed. 

Even when I have no my 3.10 venv active uv reports the following 

`warning: The requested Python version 3.8 is not available. 3.10.14 will be used` . But if I run `python3.8` it works. 

```
tin@morocha:~/lab/Project-API$ make dependencies 
UV_CUSTOM_COMPILE_COMMAND="make dependencies" uv pip compile --python-version 3.8 --generate-hashes --output-file app/requirements/requirements-dev.txt app/requirements/requirements-dev.in
warning: The requested Python version 3.8 is not available; 3.10.14 will be used to build dependencies instead.
⠙ aiohttp==3.9.5                                                                                                                                                                              ^Cmake: *** [Makefile:17: app/requirements/requirements-dev.txt] Interrupción

tin@morocha:~/lab/Project-API$ python3.8
Python 3.8.19 (default, Apr 27 2024, 21:20:48) 
[GCC 13.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 
tin@morocha:~/lab/Project-API$ which python3.8
/usr/bin/python3.8
tin@morocha:~/lab/Project-API$ python
Python 3.12.3 (main, Apr 10 2024, 05:33:47) [GCC 13.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 
tin@morocha:~/lab/Project-API$ which python3.10
/usr/bin/python3.10
tin@morocha:~/lab/Project-API$ python3.10
Python 3.10.14 (main, Apr 27 2024, 21:17:55) [GCC 13.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 
```

Debugging with `--verbose` I found the cause 

```
DEBUG Starting interpreter discovery for Python 3.8
DEBUG Looking for exact match for request Python 3.8
DEBUG Searching for Python 3.8 in all sources
DEBUG Found CPython 3.10.14 at `/home/tin/lab/Project-API/.venv/bin/python3` (virtual environment)
DEBUG Querying Python at `/usr/bin/python3.8` failed with exit status exit status: 1
--- stdout:

--- stderr:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/tin/.cache/uv/.tmpy3nPfq/python/get_interpreter_info.py", line 555, in main
    "scheme": get_scheme(),
  File "/home/tin/.cache/uv/.tmpy3nPfq/python/get_interpreter_info.py", line 415, in get_scheme
    return get_distutils_scheme()
  File "/home/tin/.cache/uv/.tmpy3nPfq/python/get_interpreter_info.py", line 357, in get_distutils_scheme
    from distutils.dist import Distribution
ModuleNotFoundError: No module named 'distutils.dist'
---
DEBUG Found CPython 3.12.3 at `/usr/bin/python3` (search path)
DEBUG Found CPython 3.12.3 at `/usr/bin/python` (search path)
DEBUG Querying Python at `/bin/python3.8` failed with exit status exit status: 1
--- stdout:
```

so after installing  `sudo apt install python3.8-distutils` it works. 

The error message could be clearer and indicate the exact issue, such as the missing distutils module, to help users resolve the problem more efficiently.

**Comment by zanieb** [comment]
Thanks for the report. It should be relatively straight-forward to add a try/except with a better message in `get_interpreter_info` if someone is interested.

**Comment by mgaitan** [comment]
is this fixed in https://github.com/astral-sh/uv/pull/7239 ?

**Comment by acarapetis** [comment]
> is this fixed in #7239 ?

Nope, ran into this today with uv 0.5.1.

**Comment by KyeRussell** [comment]
Hi. Just wanted to note that I've also hit this (on uv `0.5.20`). I don't mean to uselessly "+1!" 😁. I thought that it'd be worth noting my experience, both for prioritisation purposes and to hopefully help anyone else.

- I'm a seasoned Python developer (but evidently not one that does enough monkeying around with internals!), and I had little to no idea what was going on here.
- Google didn't help very much. I only ended up here after sifting through uv's GH issues.

I ran into this when 'moving' from Ubuntu (server) 20.04 to 24.04. To be clear, I mean a fresh install (well, really, changing my `Dockerfile`'s `FROM`). Not an actual system 'upgrade'!

In both cases, I'm using Python 3.9 (via the 'deadsnakes' PPA). `uv`'s Python binaries aren't suitable for our purposes.

- On Ubuntu 20.04, I can _just_ install the `python3.9` package, install `uv`, and set up a new environment pointing at my installed `python3.9` binary.
- On Ubuntu 24.04, I _also_ need to install the `python3.9-distutils` package. If I don't do so, I get the aforementioned very cryptic error implying that the interpreter (whose path I explicitly provide) doesn't actually exist.

This is all easily reproducible in a fresh Ubuntu Server 24.04 installation, FWIW.

**Comment by zanieb** [comment]
I can look into adding better messaging here.

I don't really understand why the Python distributions aren't coming with distutils though? It was only removed from the Python standard library in 3.12, why is it missing from older Python versions here? Are the distributions stripping it from the standard library, or am I misunderstanding?

A brief Dockerfile reproduction would be helpful.

**Comment by zanieb** [comment]
This seems like some bespoke deadsnakes packaging. I tried to reproduce but I can't seem to configure deadsnakes. If someone procures a containerized reproduction, I'll fix it.

**Comment by KyeRussell** [comment]
Working on it now :)

**Comment by KyeRussell** [comment]
Heh, OK. So, it's a little different to what I thought / described.

When I previously isolated this, I showed the issue occurring in Ubuntu 24.04 + deadsnakes' `python3.9`.

In reality, this _also_ happens in Ubuntu 20.04 + deadsnakes' `python3.9`. It didn't affect me until now as I was unknowingly installing the [`python3-distutils` Ubuntu package](https://launchpad.net/ubuntu/focal/+package/python3-distutils) (_not_ a deadsnakes package) as a transient dependency of something else I had installed. In 24.04, I'm no longer installing this package. In fact, it seems to longer exist at all. Ubuntu 24.04's system Python is 3.12.

So, seemingly, `python3-distutils` was available to uv / deadsnakes' Python 3.9. Which...seems a little scary. I don't know. I really know next to nothing about how Python is typically packaged.

Anyway, I've created a reproduction repository here: https://github.com/KyeRussell/uv-4204-reproduction. it contains:
- A series of Dockerfiles showing working and not-working scenarios for both Ubuntu 20.04 and 24.04.
- An [operational GitHub Actions workflow](https://github.com/KyeRussell/uv-4204-reproduction/actions) that tries to build each Dockerfile.

**Comment by zanieb** [comment]
Thank you!

I need to figure out if we _should_ be failing or if we should just switchover to sysconfig when distutils is not installed.

**Comment by zanieb** [comment]
@RomainBrault I'm not sure how this could have changed from that pull request.

**Comment by zanieb** [comment]
Thanks @RomainBrault ! That should be resolved in #10819 — I can't reproduce to confirm.

@KyeRussell the error message should be visible once https://github.com/astral-sh/uv/pull/10716 is merged.

**Comment by dimaqq** [comment]
I wonder if I'm hitting the same issue or different.

I've added `license = "MIT"` in my fresh project, and I'm getting:

```
ValueError: invalid pyproject.toml config: `project.license`.
configuration error: `project.license` must be valid exactly by one definition (2 matches found):

    - keys:
        'file': {type: string}
      required: ['file']
    - keys:
        'text': {type: string}
      required: ['text']

  × Failed to build `/code/otlp-json`
  ├─▶ The build backend returned an error
  ╰─▶ Call to `setuptools.build_meta:__legacy__.build_sdist` failed (exit status: 1)
      hint: This usually indicates a problem with the package or the build environment.
```

I was trying to follow https://packaging.python.org/en/latest/guides/writing-pyproject-toml/

uv 0.6.1 (Homebrew 2025-02-17)

**Comment by charliermarsh** [comment]
(Just for clarity, that’s not a uv issue. That’s setuptools enforcing a certain schema on your project.)

**Comment by dimaqq** [comment]
I figured as much, my uv project with maturin backend is not affected.

Is there perhaps some solution? Maybe a better backend for simple projects?

**Comment by zanieb** [comment]
We're working on it! #3957
