### ISSUE TITLE
`crates/uv/tests/toolchain_find.rs` fails on Gentoo Linux

### ISSUE THREAD

**Issue by mgorny** [astral-sh/uv#4376]
To be honest, I can't really figure out what the test is supposed to do.

In our "standard" test setup that exposes Python 3.12 as the "default" version and that used to satisfy tests so far, it fails with:

```
     Running `/var/tmp/portage/dev-python/uv-0.2.12/work/uv-0.2.12/target/debug/deps/toolchain_find-8ef0a312fec15b41`

running 1 test
test toolchain_find ... FAILED^O

failures:

---- toolchain_find stdout ----
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ Snapshot Summary ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Snapshot: toolchain_find
Source: crates/uv/tests/toolchain_find.rs:13
────────────────────────────────────────────────────────────────────────────────
Expression: snapshot
────────────────────────────────────────────────────────────────────────────────
-old snapshot
+new results
────────────┬───────────────────────────────────────────────────────────────────
    0     0 │ success: true
    1     1 │ exit_code: 0
    2     2 │ ----- stdout -----
    3       │-[PYTHON-3.11]
          3 │+/usr/lib/python-exec/python3.12/python3
    4     4 │ 
    5     5 │ ----- stderr -----
────────────┴───────────────────────────────────────────────────────────────────
To update snapshots run `cargo insta review`
Stopped on the first failure. Run `cargo insta test` to run all snapshots.
thread 'toolchain_find' panicked at /var/tmp/portage/dev-python/uv-0.2.12/work/cargo_home/gentoo/insta-1.39.0/src/runtime.rs:562:9:
snapshot assertion for 'toolchain_find' failed in line 13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    toolchain_find

test result: FAILED^O. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 1.34s

error: test failed, to rerun pass `--test toolchain_find`
```

If I change the setup to expose 3.11 instead, it fails as well (and this setup also makes `create_venv_ignores_virtual_env_variable` test fail):

```
     Running `/var/tmp/portage/dev-python/uv-0.2.12/work/uv-0.2.12/target/debug/deps/toolchain_find-8ef0a312fec15b41`

running 1 test
test toolchain_find ... FAILED^O

failures:

---- toolchain_find stdout ----
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ Snapshot Summary ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Snapshot: toolchain_find
Source: crates/uv/tests/toolchain_find.rs:13
────────────────────────────────────────────────────────────────────────────────
Expression: snapshot
────────────────────────────────────────────────────────────────────────────────
-old snapshot
+new results
────────────┬───────────────────────────────────────────────────────────────────
    0     0 │ success: true
    1     1 │ exit_code: 0
    2     2 │ ----- stdout -----
    3       │-[PYTHON-3.11]
          3 │+/usr/lib/python-exec/python[PYTHON-3.11]
    4     4 │ 
    5     5 │ ----- stderr -----
────────────┴───────────────────────────────────────────────────────────────────
To update snapshots run `cargo insta review`
Stopped on the first failure. Run `cargo insta test` to run all snapshots.
thread 'toolchain_find' panicked at /var/tmp/portage/dev-python/uv-0.2.12/work/cargo_home/gentoo/insta-1.39.0/src/runtime.rs:562:9:
snapshot assertion for 'toolchain_find' failed in line 13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    toolchain_find

test result: FAILED^O. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.55s

error: test failed, to rerun pass `--test toolchain_find`
     Running `/var/tmp/portage/dev-python/uv-0.2.12/work/uv-0.2.12/target/debug/deps/venv-895a2f90bedd3361`
```

For the purpose of testing, we're putting a directory with the following wrappers on top of `PATH`:

```
==> /var/tmp/portage/dev-python/uv-0.2.12/temp/python3.12/bin/python <==
#!/bin/sh
exec "/usr/bin/python3.12" "${@}"

==> /var/tmp/portage/dev-python/uv-0.2.12/temp/python3.12/bin/python-config <==
#!/bin/sh
exec "/usr/bin/python3.12-config" "${@}"

==> /var/tmp/portage/dev-python/uv-0.2.12/temp/python3.12/bin/python2 <==
#!/bin/sh
echo ": _python_wrapper_setup: python2 is not supported by python3.12 (PYTHON_COMPAT)" >&2
exit 127

==> /var/tmp/portage/dev-python/uv-0.2.12/temp/python3.12/bin/python2-config <==
#!/bin/sh
echo ": _python_wrapper_setup: python2-config is not supported by python3.12 (PYTHON_COMPAT)" >&2
exit 127

==> /var/tmp/portage/dev-python/uv-0.2.12/temp/python3.12/bin/python3 <==
#!/bin/sh
exec "/usr/bin/python3.12" "${@}"

==> /var/tmp/portage/dev-python/uv-0.2.12/temp/python3.12/bin/python3-config <==
#!/bin/sh
exec "/usr/bin/python3.12-config" "${@}"
```

`/usr/bin/python3.11` and `/usr/bin/python3.12` as the actual executables installed by respective Python versions. However, `/usr/bin/python` and `/usr/bin/python3` (that shouldn't have been called because of `PATH` set) are C wrappers that effectively calls `/usr/lib/python-exec/python3.12/python` or `/python3` in that setup, which in turns are symlinks leading to `/usr/bin/python3.12`.

**Comment by zanieb** [comment]
Hi! Regarding `toolchain_find`, this test provides coverage for our toolchain discovery command e.g. `uv toolchain find` should give the path to an interpreter that meets the given request. During each test, we create a test context with the requested interpreters. We discover the required interpreters and place their paths into a special `PATH` variable so the tests are properly isolated from the rest of the system. We then filter these paths with dedicated snapshot filters (e.g. `[PYTHON-<VERSION>]`) so that the test snapshots are independent of the system you're running on. It looks like here, the `toolchain find` output contains a path that doesn't match our expected filters. Probably because of the shims you're using? 

We display the `sys.executable` of the found interpreter at https://github.com/astral-sh/uv/blob/accbb9b695418318e136f628fe366e845bc224f2/crates/uv/src/commands/toolchain/find.rs#L39 but our filtering is applied to the executable we find on the path https://github.com/astral-sh/uv/blob/b22ee82f0d3af607cc49d3f3870805769ea0b6e6/crates/uv/tests/common/mod.rs#L146-L150

**Comment by zanieb** [comment]
Though actually it looks like that executable path should also be the `sys.executable`

https://github.com/astral-sh/uv/blob/b22ee82f0d3af607cc49d3f3870805769ea0b6e6/crates/uv/tests/common/mod.rs#L702

**Comment by mgorny** [comment]
The matched path aside, the first problem is why is it finding Python 3.12 when it's looking for Python 3.11? `python` and `python3` here are 3.12, and explicit `python3.11` and `python3.12` executables are available on `PATH`.

**Comment by zanieb** [comment]
Yeah sounds weird. I don't have any ideas — but the way I debug things like this is to add the `-v` flag to the command invocation in the test. `RUST_LOG=uv=trace` will also be really helpful for toolchain discovery debugging too.

**Comment by mgorny** [comment]
With unmangled `PATH`:

```
$ echo $PATH
/home/mgorny/perl5/bin:/home/mgorny/node_modules/.bin/:/home/mgorny/bin:/usr/i686-pc-linux-gnu/gcc-bin/4.9.2:/usr/local/sbin:/usr/local/bin:/usr/bin:/opt/bin:/usr/sbin:/sbin:/usr/lib/llvm/19/bin:/usr/lib/llvm/18/bin:/usr/lib/llvm/17/bin:/usr/lib/llvm/9/bin:/etc/eselect/wine/bin:/home/mgorny/.local/bin
$ RUST_LOG=uv=trace cargo test -p uv --test toolchain_find
    Finished `test` profile [unoptimized + debuginfo] target(s) in 0.32s
     Running tests/toolchain_find.rs (target/debug/deps/toolchain_find-ad7d4b038b9c38d8)

running 1 test
test toolchain_find ... FAILED

failures:

---- toolchain_find stdout ----
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ Snapshot Summary ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Snapshot: toolchain_find
Source: crates/uv/tests/toolchain_find.rs:13
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Expression: snapshot
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
-old snapshot
+new results
────────────┬──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
    0     0 │ success: true
    1     1 │ exit_code: 0
    2     2 │ ----- stdout -----
    3       │-[PYTHON-3.11]
          3 │+/usr/lib/python-exec/python3.12/python3
    4     4 │ 
    5       │------ stderr -----
          5 │+----- stderr -----
          6 │+DEBUG uv 0.2.13 (e486eb86b 2024-06-18)
          7 │+DEBUG Only considering search path, provided path, and active environments due to `UV_TEST_PYTHON_PATH`
          8 │+DEBUG Searching for Python interpreter in provided path, active virtual environment, or search path
          9 │+TRACE Searching PATH for executables: python3, python
         10 │+DEBUG Python interpreter not found at `[VENV]/bin/python3`
         11 │+TRACE Skipping missing interpreter at [VENV]/bin/python3
         12 │+TRACE Checking `PATH` directory for interpreters: /usr/bin
         13 │+TRACE Found possible Python executable: [PYTHON-3.11]
         14 │+TRACE Querying interpreter executable at [PYTHON-3.11]
         15 │+DEBUG Found cpython 3.12.[X] at `[PYTHON-3.11]
────────────┴──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
To update snapshots run `cargo insta review`
Stopped on the first failure. Run `cargo insta test` to run all snapshots.
thread 'toolchain_find' panicked at /home/mgorny/.cargo/registry/src/index.crates.io-6f17d22bba15001f/insta-1.39.0/src/runtime.rs:562:9:
snapshot assertion for 'toolchain_find' failed in line 13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    toolchain_find

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.45s

error: test failed, to rerun pass `-p uv --test toolchain_find`
```

**Comment by zanieb** [comment]
It looks like when we setup the test context we think the Python 3.12 executable is Python 3.11? Or I mangled the filtering somehow. Weird. I'll probably have to try to reproduce and resolve on my end unless you want to dig into the dark world of our test context tooling.

**Comment by mgorny** [comment]
Yeah, I'm totally confused what assumptions are being made here. Thanks for looking into it. I don't think I have the energy to try figuring out all of this right now, but if you need more details about the system, or need me to test anything, please let me know.

**Comment by zanieb** [comment]
I believe I've found the problem at https://github.com/astral-sh/uv/pull/4443

**Comment by mgorny** [comment]
Ehh, I'm sorry to say but it seems that I didn't test the patch sufficiently, and it only works for a very specific setting of `PATH=/usr/lib/python-exec/python3.12`. However, it still fails if the first `python*` on `PATH` is not that directory, e.g. with plain `/usr/bin`, I'm getting:

```
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ Snapshot Summary ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Snapshot: toolchain_find-10
Source: crates/uv/tests/toolchain_find.rs:111
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Expression: snapshot
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
-old snapshot
+new results
────────────┬──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
    0     0 │ success: true
    1     1 │ exit_code: 0
    2     2 │ ----- stdout -----
    3       │-[PYTHON-3.12]
          3 │+/usr/lib/python-exec/python3.13/python3
    4     4 │ 
    5     5 │ ----- stderr -----
────────────┴──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
```

After stripping away previous tests, the debug log gives:

```
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ Snapshot Summary ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Snapshot: toolchain_find
Source: crates/uv/tests/toolchain_find.rs:16
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Expression: snapshot
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
-old snapshot
+new results
────────────┬───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
    0     0 │ success: true
    1     1 │ exit_code: 0
    2     2 │ ----- stdout -----
    3       │-[PYTHON-3.12]
          3 │+/usr/lib/python-exec/python3.13/python3
    4     4 │ 
    5       │------ stderr -----
          5 │+----- stderr -----
          6 │+DEBUG uv [VERSION] ([COMMIT] DATE)
          7 │+DEBUG Searching for Python interpreter in system toolchains
          8 │+TRACE Searching PATH for executables: python3, python
          9 │+TRACE Checking `PATH` directory for interpreters: /usr/bin
         10 │+TRACE Found possible Python executable: /usr/bin/python3
         11 │+TRACE Querying interpreter executable at /usr/bin/python3
         12 │+DEBUG Found cpython 3.13.0b2 at `/usr/bin/python3` (search path)
────────────┴───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
```


Can you reopen the bug, or should I file a new one?
