### ISSUE TITLE
[Error] uv pip install -e .

### ISSUE THREAD

**Issue by 17Reset** [astral-sh/uv#4954]
```
(llm_venv_autoawq) xlab@xlab:/mnt/Model/Qwen/AutoAWQ$ uv pip install -e .
error: Failed to build: `file:///mnt/Model/Qwen/AutoAWQ`
  Caused by: Build backend failed to determine extra requires with `build_editable()` with exit status: 1
--- stdout:

--- stderr:
Traceback (most recent call last):
  File "<string>", line 14, in <module>
  File "/home/xlab/.cache/uv/builds-v0/.tmpUx9Z0A/lib/python3.10/site-packages/setuptools/build_meta.py", line 458, in get_requires_for_build_editable
    return self.get_requires_for_build_wheel(config_settings)
  File "/home/xlab/.cache/uv/builds-v0/.tmpUx9Z0A/lib/python3.10/site-packages/setuptools/build_meta.py", line 327, in get_requires_for_build_wheel
    return self._get_build_requires(config_settings, requirements=[])
  File "/home/xlab/.cache/uv/builds-v0/.tmpUx9Z0A/lib/python3.10/site-packages/setuptools/build_meta.py", line 297, in _get_build_requires
    self.run_setup()
  File "/home/xlab/.cache/uv/builds-v0/.tmpUx9Z0A/lib/python3.10/site-packages/setuptools/build_meta.py", line 497, in run_setup
    super().run_setup(setup_script=setup_script)
  File "/home/xlab/.cache/uv/builds-v0/.tmpUx9Z0A/lib/python3.10/site-packages/setuptools/build_meta.py", line 313, in run_setup
    exec(code, locals())
  File "<string>", line 2, in <module>
ModuleNotFoundError: No module named 'torch'
---
(llm_venv_autoawq) xlab@xlab:/mnt/Model/Qwen/AutoAWQ$ uv pip install torch requests
Resolved 27 packages in 1.89s
Prepared 9 packages in 3m 08s
Installed 27 packages in 237ms
 + certifi==2024.7.4
 + charset-normalizer==3.3.2
 + filelock==3.15.4
 + fsspec==2024.6.1
 + idna==3.7
 + jinja2==3.1.4
 + markupsafe==2.1.5
 + mpmath==1.3.0
 + networkx==3.3
 + nvidia-cublas-cu12==12.1.3.1
 + nvidia-cuda-cupti-cu12==12.1.105
 + nvidia-cuda-nvrtc-cu12==12.1.105
 + nvidia-cuda-runtime-cu12==12.1.105
 + nvidia-cudnn-cu12==8.9.2.26
 + nvidia-cufft-cu12==11.0.2.54
 + nvidia-curand-cu12==10.3.2.106
 + nvidia-cusolver-cu12==11.4.5.107
 + nvidia-cusparse-cu12==12.1.0.106
 + nvidia-nccl-cu12==2.20.5
 + nvidia-nvjitlink-cu12==12.5.82
 + nvidia-nvtx-cu12==12.1.105
 + requests==2.32.3
 + sympy==1.13.0
 + torch==2.3.1
 + triton==2.3.1
 + typing-extensions==4.12.2
 + urllib3==2.2.2
(llm_venv_autoawq) xlab@xlab:/mnt/Model/Qwen/AutoAWQ$ uv pip install -e .
error: Failed to build: `file:///mnt/Model/Qwen/AutoAWQ`
  Caused by: Build backend failed to determine extra requires with `build_editable()` with exit status: 1
--- stdout:

--- stderr:
Traceback (most recent call last):
  File "<string>", line 14, in <module>
  File "/home/xlab/.cache/uv/builds-v0/.tmpbqqDM9/lib/python3.10/site-packages/setuptools/build_meta.py", line 458, in get_requires_for_build_editable
    return self.get_requires_for_build_wheel(config_settings)
  File "/home/xlab/.cache/uv/builds-v0/.tmpbqqDM9/lib/python3.10/site-packages/setuptools/build_meta.py", line 327, in get_requires_for_build_wheel
    return self._get_build_requires(config_settings, requirements=[])
  File "/home/xlab/.cache/uv/builds-v0/.tmpbqqDM9/lib/python3.10/site-packages/setuptools/build_meta.py", line 297, in _get_build_requires
    self.run_setup()
  File "/home/xlab/.cache/uv/builds-v0/.tmpbqqDM9/lib/python3.10/site-packages/setuptools/build_meta.py", line 497, in run_setup
    super().run_setup(setup_script=setup_script)
  File "/home/xlab/.cache/uv/builds-v0/.tmpbqqDM9/lib/python3.10/site-packages/setuptools/build_meta.py", line 313, in run_setup
    exec(code, locals())
  File "<string>", line 2, in <module>
ModuleNotFoundError: No module named 'torch'
---

```

**Comment by charliermarsh** [comment]
My guess is that you need `--no-build-isolation`?

**Comment by 17Reset** [comment]
if I use --no-build-isolation, why need to install setuptools?

```
(llm_venv_autoawq) xlab@xlab:/mnt/Model/Qwen/AutoAWQ$ uv pip install --no-build-isolation -e .
error: Failed to build: `file:///mnt/Model/Qwen/AutoAWQ`
  Caused by: Build backend failed to determine metadata through `prepare_metadata_for_build_editable` with exit status: 1
--- stdout:

--- stderr:
Traceback (most recent call last):
  File "<string>", line 8, in <module>
ModuleNotFoundError: No module named 'setuptools'
---
(llm_venv_autoawq) xlab@xlab:/mnt/Model/Qwen/AutoAWQ$ uv pip install setuptools
Resolved 1 package in 686ms
Installed 1 package in 30ms
 + setuptools==70.3.0
(llm_venv_autoawq) a0@a0:/mnt/Model/Qwen/AutoAWQ$ uv pip install --no-build-isolation -e .
Resolved 59 packages in 9.66s
   Built autoawq @ file:///mnt/Model/Qwen/AutoAWQ
Prepared 14 packages in 11.90s
Uninstalled 1 package in 3ms
Installed 33 packages in 229ms
 + accelerate==0.32.1
 + aiohttp==3.9.5
 + aiosignal==1.3.1
 + async-timeout==4.0.3
 + attrs==23.2.0
 + autoawq==0.2.5+cpu (from file:///mnt/Model/Qwen/AutoAWQ)
 + autoawq-kernels==0.0.6
 + datasets==2.20.0
 + dill==0.3.8
 + frozenlist==1.4.1
 - fsspec==2024.6.1
 + fsspec==2024.5.0
 + huggingface-hub==0.23.4
 + multidict==6.0.5
 + multiprocess==0.70.16
 + numpy==1.26.4
 + packaging==24.1
 + pandas==2.2.2
 + psutil==6.0.0
 + pyarrow==16.1.0
 + pyarrow-hotfix==0.6
 + python-dateutil==2.9.0.post0
 + pytz==2024.1
 + pyyaml==6.0.1
 + regex==2024.5.15
 + safetensors==0.4.3
 + six==1.16.0
 + tokenizers==0.19.1
 + tqdm==4.66.4
 + transformers==4.42.3
 + tzdata==2024.1
 + xxhash==3.4.1
 + yarl==1.9.4
 + zstandard==0.22.0
```

**Comment by charliermarsh** [comment]
`--no-build-isolation` means that you're responsible for installing all of your build-time dependencies in advance. If a package has build-time dependencies that aren't declared (like `torch`, in this case), then you have to use `--no-build-isolation` to access them. I assume the same package would fail to install with `pip install --use-pep517`.

**Comment by 17Reset** [comment]
But if I use the native pip command as shown below instead of using uv, it works fine and doesn't require me to install these dependent `pip install -e .` ahead of time.

**Comment by charliermarsh** [comment]
I assume it fails, though, if you run `pip install --use-pep517 -e .`, which will eventually be pip's default?

**Comment by 17Reset** [comment]
Yes, without installing the torch, use the commands `pip install -e . ` and `pip install --use-pep517 -e . ` will still give an error
```
xlab@xlab:/mnt/Model/Qwen$ python3 -m venv llm_venv_autoawq && source llm_venv_autoawq/bin/activate
(llm_venv_autoawq) xlab@xlab:/mnt/Model/Qwen$ git clone https://github.com/casper-hansen/AutoAWQ
Cloning into 'AutoAWQ'...
remote: Enumerating objects: 3306, done.
remote: Counting objects: 100% (203/203), done.
remote: Compressing objects: 100% (98/98), done.
remote: Total 3306 (delta 111), reused 185 (delta 102), pack-reused 3103
Receiving objects: 100% (3306/3306), 7.58 MiB | 1.86 MiB/s, done.
Resolving deltas: 100% (2048/2048), done.
(llm_venv_autoawq) xlab@xlab:/mnt/Model/Qwen$ cd AutoAWQ/
(llm_venv_autoawq) xlab@xlab:/mnt/Model/Qwen/AutoAWQ$ pip install -e .
Obtaining file:///mnt/Model/Qwen/AutoAWQ
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/mnt/Model/Qwen/AutoAWQ/setup.py", line 2, in <module>
          import torch
      ModuleNotFoundError: No module named 'torch'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
(llm_venv_autoawq) xlab@xlab:/mnt/Model/Qwen/AutoAWQ$ pip install --use-pep517 -e .
Obtaining file:///mnt/Model/Qwen/AutoAWQ
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... error
  error: subprocess-exited-with-error

  × Getting requirements to build editable did not run successfully.
  │ exit code: 1
  ╰─> [19 lines of output]
      Traceback (most recent call last):
        File "/mnt/Model/Qwen/llm_venv_autoawq/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/mnt/Model/Qwen/llm_venv_autoawq/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/mnt/Model/Qwen/llm_venv_autoawq/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 144, in get_requires_for_build_editable
          return hook(config_settings)
        File "/tmp/pip-build-env-g_o04e1p/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 458, in get_requires_for_build_editable
          return self.get_requires_for_build_wheel(config_settings)
        File "/tmp/pip-build-env-g_o04e1p/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 327, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
        File "/tmp/pip-build-env-g_o04e1p/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 297, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-g_o04e1p/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 497, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-g_o04e1p/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 313, in run_setup
          exec(code, locals())
        File "<string>", line 2, in <module>
      ModuleNotFoundError: No module named 'torch'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build editable did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by 17Reset** [comment]
Using `uv pip install --no-build-isolation -e . ` will also encounter the error
```
xlab@xlab:/mnt/Model/Qwen$ uv venv llm_venv_autoawq && source llm_venv_autoawq/bin/activate
Using Python 3.10.12 interpreter at: /usr/bin/python3
Creating virtualenv at: llm_venv_autoawq
Activate with: source llm_venv_autoawq/bin/activate
(llm_venv_autoawq) xlab@xlab:/mnt/Model/Qwen$ git clone https://github.com/casper-hansen/AutoAWQ
Cloning into 'AutoAWQ'...
remote: Enumerating objects: 3306, done.
remote: Counting objects: 100% (203/203), done.
remote: Compressing objects: 100% (98/98), done.
remote: Total 3306 (delta 111), reused 185 (delta 102), pack-reused 3103
Receiving objects: 100% (3306/3306), 7.58 MiB | 5.40 MiB/s, done.
Resolving deltas: 100% (2048/2048), done.
(llm_venv_autoawq) xlab@xlab:/mnt/Model/Qwen$ cd AutoAWQ/
(llm_venv_autoawq) xlab@xlab:/mnt/Model/Qwen/AutoAWQ$ uv pip install --no-build-isolation -e .
error: Failed to build: `file:///mnt/Model/Qwen/AutoAWQ`
  Caused by: Build backend failed to determine metadata through `prepare_metadata_for_build_editable` with exit status: 1
--- stdout:

--- stderr:
Traceback (most recent call last):
  File "<string>", line 8, in <module>
ModuleNotFoundError: No module named 'setuptools'
---
(llm_venv_autoawq) xlab@xlab:/mnt/Model/Qwen/AutoAWQ$ uv pip install setuptools
Resolved 1 package in 416ms
Installed 1 package in 13ms
 + setuptools==70.3.0
(llm_venv_autoawq) xlab@xlab:/mnt/Model/Qwen/AutoAWQ$ uv pip install --no-build-isolation -e .
error: Failed to build: `file:///mnt/Model/Qwen/AutoAWQ`
  Caused by: Build backend failed to determine metadata through `prepare_metadata_for_build_editable` with exit status: 1
--- stdout:

--- stderr:
Traceback (most recent call last):
  File "<string>", line 14, in <module>
  File "/mnt/Model/Qwen/llm_venv_autoawq/lib/python3.10/site-packages/setuptools/build_meta.py", line 463, in prepare_metadata_for_build_editable
    return self.prepare_metadata_for_build_wheel(
  File "/mnt/Model/Qwen/llm_venv_autoawq/lib/python3.10/site-packages/setuptools/build_meta.py", line 368, in prepare_metadata_for_build_wheel
    self.run_setup()
  File "/mnt/Model/Qwen/llm_venv_autoawq/lib/python3.10/site-packages/setuptools/build_meta.py", line 497, in run_setup
    super().run_setup(setup_script=setup_script)
  File "/mnt/Model/Qwen/llm_venv_autoawq/lib/python3.10/site-packages/setuptools/build_meta.py", line 313, in run_setup
    exec(code, locals())
  File "<string>", line 2, in <module>
ModuleNotFoundError: No module named 'torch'
---
```

**Comment by 17Reset** [comment]
Thanks for the answer, it looks like it's necessary to install all build-time dependencies in advance

**Comment by zanieb** [comment]
Thanks for confirming :)
