### ISSUE TITLE
Can't install wheel in working directory without specifying `./`

### ISSUE THREAD

**Issue by ilkersigirci** [astral-sh/uv#6052]
- I want to use  `uv` inside docker to install wheel packages. Unfortunately it doesn't work and gives following error
```
No solution found when resolving dependencies:
  ╰─▶ Because python-dotenv-1-0-1-py3-none-any-whl was not found in the package registry and you require
    python-dotenv-1-0-1-py3-none-any-whl, we can conclude that the requirements are unsatisfiable. 
```
- I have used python-dotenv wheel as an example. It doesn't work on any wheel files.
- BTW, this behaviour is only inside Docker, outside the Docker, everything works as expected.

- Example Dockerfile
```yaml
ARG PYTHON_VERSION=3.11
FROM python:${PYTHON_VERSION}-slim-bookworm as production

ENV \
    PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PYTHONFAULTHANDLER=1 \
    PIP_ROOT_USER_ACTION=ignore \
    UV_SYSTEM_PYTHON=1 \
    UV_NO_CONFIG=1 \
    UV_NO_CACHE=1

WORKDIR /app

RUN \
    apt-get update -y \
    && apt-get install -y --no-install-recommends \
    curl \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /var/cache/apt/archives

ADD --chmod=755 https://astral.sh/uv/install.sh /install.sh
RUN /install.sh && rm /install.sh

ENV PATH="/root/.cargo/bin/:$PATH"

RUN curl \
    https://files.pythonhosted.org/packages/6a/3e/b68c118422ec867fa7ab88444e1274aa40681c606d59ac27de5a5588f082/python_dotenv-1.0.1-py3-none-any.whl \
    --output python_dotenv-1.0.1-py3-none-any.whl


# NOTE: Gives error
RUN uv pip install python_dotenv-1.0.1-py3-none-any.whl
```

**Comment by zanieb** [comment]
Hi! I think you just need to disambiguate that it's a file path and not a package name, e.g. with `./python_dotenv-1.0.1-py3-none-any.whl`.

@charliermarsh I wonder if we should detect this automatically for names ending in `.whl`?

**Comment by zanieb** [comment]
I think we should also add a hint to resolver errors when the package is not found in the registry but the name exists in the working directory.

**Comment by ilkersigirci** [comment]
> Hi! I think you just need to disambiguate that it's a file path and not a package name, e.g. with `./python_dotenv-1.0.1-py3-none-any.whl`.
> 
> @charliermarsh I wonder if we should detect this automatically for names ending in `.whl`?

Thank you, this resolves the issue. I agree with you on the error message part. It would be nice if the error message can be more clear

**Comment by zanieb** [comment]
I'll leave this open until we know what we want to do for improvements.

**Comment by lexiconlp** [comment]
> BTW, this behaviour is only inside Docker, outside the Docker, everything works as expected.


I test in a Mac ( not in docker ) m1 and this fail ( I would like to know why and how to solve it )


```shell
$ uv --version
$ uv init test-project --python 3.12
$ cd test-project 
$ uv add dotenv
💥 💥 
```
All details here: 

```shell
$ uv --version
uv 0.4.3 (47f4ca24b 2024-09-02)
$ uv init test-project --python 3.12
Initialized project `test-project` at `/Users/my-user/Documents/test-project`
$ cd test-project 
$ uv add dotenv
Using Python 3.12.0 interpreter at: /opt/homebrew/opt/python@3.12/bin/python3.12
Creating virtualenv at: .venv
⠸ dotenv==0.0.5                                                                 error: Failed to download and build `dotenv==0.0.5`
  Caused by: Failed to install requirements from `build-system.requires` (resolve)
  Caused by: No solution found when resolving: setuptools>=40.8.0, distribute
  Caused by: Failed to download and build `distribute==0.6.49`
  Caused by: Build backend failed to determine extra requires with `build_wheel()` with exit status: 1
--- stdout:

--- stderr:
Traceback (most recent call last):
  File "<string>", line 14, in <module>
  File "/Users/my-user/.cache/uv/builds-v0/.tmpzAmVk8/lib/python3.12/site-packages/setuptools/build_meta.py", line 332, in get_requires_for_build_wheel
    return self._get_build_requires(config_settings, requirements=[])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/my-user.cache/uv/builds-v0/.tmpzAmVk8/lib/python3.12/site-packages/setuptools/build_meta.py", line 302, in _get_build_requires
    self.run_setup()
  File "/Users/my-user/.cache/uv/builds-v0/.tmpzAmVk8/lib/python3.12/site-packages/setuptools/build_meta.py", line 503, in run_setup
    super().run_setup(setup_script=setup_script)
  File "/Users/my-user/.cache/uv/builds-v0/.tmpzAmVk8/lib/python3.12/site-packages/setuptools/build_meta.py", line 318, in run_setup
    exec(code, locals())
  File "<string>", line 34, in <module>
AttributeError: module 'distutils.util' has no attribute 'run_2to3'
---

```

**Comment by zanieb** [comment]
@lexiconlp I think you're looking for `uv add python-dotenv`.

**Comment by nibbledeez** [comment]
@zanieb - I also get the same issue on Ubutnu 22.04 with python-dotenv:

❯ uv add python-dotenv
⠹ distribute==0.6.49                                                                                                                                                                                                                        error: Failed to download and build `distribute==0.6.49`
  Caused by: Build backend failed to determine extra requires with `build_wheel()` with exit status: 1
--- stdout:

--- stderr:
Traceback (most recent call last):
  File "<string>", line 14, in <module>
  File "/home/my-user/.cache/uv/builds-v0/.tmpLivn31/lib/python3.12/site-packages/setuptools/build_meta.py", line 332, in get_requires_for_build_wheel
    return self._get_build_requires(config_settings, requirements=[])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/my-user/.cache/uv/builds-v0/.tmpLivn31/lib/python3.12/site-packages/setuptools/build_meta.py", line 302, in _get_build_requires
    self.run_setup()
  File "/home/my-user/.cache/uv/builds-v0/.tmpLivn31/lib/python3.12/site-packages/setuptools/build_meta.py", line 503, in run_setup
    super().run_setup(setup_script=setup_script)
  File "/home/my-user/.cache/uv/builds-v0/.tmpLivn31/lib/python3.12/site-packages/setuptools/build_meta.py", line 318, in run_setup
    exec(code, locals())
  File "<string>", line 34, in <module>
AttributeError: module 'distutils.util' has no attribute 'run_2to3'

**Comment by charliermarsh** [comment]
That looks like a legitimate error with the package itself?

**Comment by nibbledeez** [comment]
Perhaps the issue is 'dependency' as I get the same with bs4 as below. Both bs4 and python-dotenv install fine using pip and the same env.

❯ uv add bs4
⠹ distribute==0.6.49                                                                                                                                                                                                                        error: Failed to download and build `distribute==0.6.49`
  Caused by: Build backend failed to determine extra requires with `build_wheel()` with exit status: 1
--- stdout:

--- stderr:
Traceback (most recent call last):
  File "<string>", line 14, in <module>
  File "/home/my-user/.cache/uv/builds-v0/.tmpI7wM21/lib/python3.12/site-packages/setuptools/build_meta.py", line 332, in get_requires_for_build_wheel
    return self._get_build_requires(config_settings, requirements=[])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/my-user/.cache/uv/builds-v0/.tmpI7wM21/lib/python3.12/site-packages/setuptools/build_meta.py", line 302, in _get_build_requires
    self.run_setup()
  File "/home/my-user/.cache/uv/builds-v0/.tmpI7wM21/lib/python3.12/site-packages/setuptools/build_meta.py", line 503, in run_setup
    super().run_setup(setup_script=setup_script)
  File "/home/my-user/.cache/uv/builds-v0/.tmpI7wM21/lib/python3.12/site-packages/setuptools/build_meta.py", line 318, in run_setup
    exec(code, locals())
  File "<string>", line 34, in <module>
AttributeError: module 'distutils.util' has no attribute 'run_2to3'

**Comment by notatallshaw** [comment]
Yeah, I wouldn't expect `distribute` to work with modern package requirements, it's very old: https://pypi.org/project/distribute/#history

Where is distribute coming from? It shouldn't be a dependency of any modern package. It's project description is "Distribute - legacy package. This package is a simple compatibility layer that installs Setuptools 0.7+."

**Comment by nibbledeez** [comment]
> Yeah, I wouldn't expect `distribute` to work with modern package requirements, it's very old: https://pypi.org/project/distribute/#history
> 
> Where is distribute coming from? It shouldn't be a dependency of any modern package. It's project description is "Distribute - legacy package. This package is a simple compatibility layer that installs Setuptools 0.7+."

Hmm - not sure but perhaps this is germane?

```
error: Failed to download and build `dotenv==0.0.5`
  Caused by: Failed to install requirements from `build-system.requires` (resolve)
  Caused by: **No solution found when resolving: setuptools>=40.8.0, distribute**
  Caused by: Failed to download and build `distribute==0.6.49`
  Caused by: Build backend failed to determine extra requires with `build_wheel()` with exit status: 1
```

**Comment by charliermarsh** [comment]
Apologies, do you mean to be installing `dotenv==0.0.5`? You might be intending to do `uv add python-dotenv` instead.

**Comment by nibbledeez** [comment]
Ok - so I had tried python-dotenv as well as thought perhaps I had the wrong package - that also failed. However,  manually deleting the dotenv dir and files from .venv from the first attempt has worked. Guess this one can be closed.
