### ISSUE TITLE
uv fails to install pytorch3d, while pip succedes

### ISSUE THREAD

**Issue by RafailFridman** [astral-sh/uv#6079]
I'm trying to install pytorch3d on Mac, following [these instructions.](https://github.com/facebookresearch/pytorch3d/blob/main/INSTALL.md)
I have created an environment and already installed torch:
```
uv venv p3d -p 3.10 --seed
uv pip install torch torchvision torchaudio
```
I'm running this command:
```
MACOSX_DEPLOYMENT_TARGET=10.14 CC=clang CXX=clang++ uv pip install "git+https://github.com/facebookresearch/pytorch3d.git" --verbose
```
and get the following:
```
DEBUG uv 0.2.36 (Homebrew 2024-08-13)
DEBUG Searching for Python interpreter in system path
DEBUG Found `cpython-3.10.14-macos-aarch64-none` at `/Users/rafailf/Documents/projects/envs/p3d/bin/python3` (active virtual environment)
DEBUG Using Python 3.10.14 environment at p3d/bin/python3
DEBUG Acquired lock for `p3d`
DEBUG At least one requirement is not satisfied: git+https://github.com/facebookresearch/pytorch3d.git
DEBUG Using request timeout of 30s
DEBUG Fetching source distribution from Git: https://github.com/facebookresearch/pytorch3d.git
DEBUG Acquired lock for `https://github.com/facebookresearch/pytorch3d`
DEBUG Updating git source `Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("github.com")), port: None, path: "/facebookresearch/pytorch3d.git", query: None, fragment: None }`
DEBUG Attempting GitHub fast path for: https://api.github.com/repos/facebookresearch/pytorch3d/commits/HEAD
DEBUG Performing a Git fetch for: https://github.com/facebookresearch/pytorch3d.git
DEBUG Acquired lock for `/Users/rafailf/Library/Caches/uv/built-wheels-v3/git/0c0d4c037a64738f/38afdcfc6826bb41`
DEBUG Preparing metadata for: git+https://github.com/facebookresearch/pytorch3d.git
DEBUG No static `PKG-INFO` available for: git+https://github.com/facebookresearch/pytorch3d.git (MissingPkgInfo)
DEBUG No static `pyproject.toml` available for: git+https://github.com/facebookresearch/pytorch3d.git (MissingPyprojectToml)
INFO Ignoring empty directory
DEBUG Solving with installed Python version: 3.10.14
DEBUG Adding direct dependency: setuptools>=40.8.0
DEBUG Found fresh response for: https://pypi.org/simple/setuptools/
DEBUG Searching for a compatible version of setuptools (>=40.8.0)
DEBUG Selecting: setuptools==72.2.0 [compatible] (setuptools-72.2.0-py3-none-any.whl)
DEBUG Found fresh response for: https://files.pythonhosted.org/packages/6e/ec/06715d912351edc453e37f93f3fc80dcffd5ca0e70386c87529aca296f05/setuptools-72.2.0-py3-none-any.whl.metadata
DEBUG Tried 1 versions: setuptools 1
DEBUG Split specific environment resolution took 0.001s
DEBUG Installing in setuptools==72.2.0 in /Users/rafailf/Library/Caches/uv/builds-v0/.tmpKz5wsx
DEBUG Requirement already cached: setuptools==72.2.0
DEBUG Installing build requirement: setuptools==72.2.0
DEBUG Calling `setuptools.build_meta:__legacy__.get_requires_for_build_wheel()`
error: Failed to build: `git+https://github.com/facebookresearch/pytorch3d.git`
  Caused by: Build backend failed to determine extra requires with `build_wheel()` with exit status: 1
--- stdout:

--- stderr:
Traceback (most recent call last):
  File "<string>", line 14, in <module>
  File "/Users/rafailf/Library/Caches/uv/builds-v0/.tmpKz5wsx/lib/python3.10/site-packages/setuptools/build_meta.py", line 327, in get_requires_for_build_wheel
    return self._get_build_requires(config_settings, requirements=[])
  File "/Users/rafailf/Library/Caches/uv/builds-v0/.tmpKz5wsx/lib/python3.10/site-packages/setuptools/build_meta.py", line 297, in _get_build_requires
    self.run_setup()
  File "/Users/rafailf/Library/Caches/uv/builds-v0/.tmpKz5wsx/lib/python3.10/site-packages/setuptools/build_meta.py", line 497, in run_setup
    super().run_setup(setup_script=setup_script)
  File "/Users/rafailf/Library/Caches/uv/builds-v0/.tmpKz5wsx/lib/python3.10/site-packages/setuptools/build_meta.py", line 313, in run_setup
    exec(code, locals())
  File "<string>", line 15, in <module>
ModuleNotFoundError: No module named 'torch'
---
  Caused by: This error likely indicates that git+https://github.com/facebookresearch/pytorch3d.git depends on torch, but doesn't declare it as a build dependency. If git+https://github.com/facebookresearch/pytorch3d.git is a first-party package, consider adding torch to its `build-system.requires`. Otherwise, `uv pip install torch` into the environment and re-run with `--no-build-isolation`.
---
```

While running the same command, but with `pip install ` instead of ` uv pip install` works:
```
MACOSX_DEPLOYMENT_TARGET=10.14 CC=clang CXX=clang++ pip install "git+https://github.com/facebookresearch/pytorch3d.git"
```
with output:
```
Collecting git+https://github.com/facebookresearch/pytorch3d.git
  Cloning https://github.com/facebookresearch/pytorch3d.git to /private/var/folders/hw/0k21gtlx6k5_2mtjy3_mf2jh0000gp/T/pip-req-build-kps4ilpm
  Running command git clone --filter=blob:none --quiet https://github.com/facebookresearch/pytorch3d.git /private/var/folders/hw/0k21gtlx6k5_2mtjy3_mf2jh0000gp/T/pip-req-build-kps4ilpm
  Resolved https://github.com/facebookresearch/pytorch3d.git to commit 38afdcfc6826bb41bbc414404937fab58dc24e85
  Preparing metadata (setup.py) ... done
Collecting iopath (from pytorch3d==0.7.7)
  Downloading iopath-0.1.10.tar.gz (42 kB)
  Preparing metadata (setup.py) ... done
Collecting tqdm (from iopath->pytorch3d==0.7.7)
  Downloading tqdm-4.66.5-py3-none-any.whl.metadata (57 kB)
Requirement already satisfied: typing_extensions in ./p3d/lib/python3.10/site-packages (from iopath->pytorch3d==0.7.7) (4.12.2)
Collecting portalocker (from iopath->pytorch3d==0.7.7)
  Downloading portalocker-2.10.1-py3-none-any.whl.metadata (8.5 kB)
Downloading portalocker-2.10.1-py3-none-any.whl (18 kB)
Downloading tqdm-4.66.5-py3-none-any.whl (78 kB)
Building wheels for collected packages: pytorch3d, iopath
  Building wheel for pytorch3d (setup.py) ... done
  Created wheel for pytorch3d: filename=pytorch3d-0.7.7-cp310-cp310-macosx_14_0_arm64.whl size=929835 sha256=77d9144c4eda7ef3ff2be1422ef786ff25472b4c582cd9f8b060c90cd41bb20c
  Stored in directory: /private/var/folders/hw/0k21gtlx6k5_2mtjy3_mf2jh0000gp/T/pip-ephem-wheel-cache-jch7vouh/wheels/dd/74/cc/b9266c863f19026f796e59a04e1cd9eb3754474a52ce1b66ce
  Building wheel for iopath (setup.py) ... done
  Created wheel for iopath: filename=iopath-0.1.10-py3-none-any.whl size=31528 sha256=e3a30ad2c9ba029c5fe04b6a448745088f10d1bbbe7f3d8267a53b74e8e334c1
  Stored in directory: /Users/rafailf/Library/Caches/pip/wheels/9a/a3/b6/ac0fcd1b4ed5cfeb3db92e6a0e476cfd48ed0df92b91080c1d
Successfully built pytorch3d iopath
Installing collected packages: tqdm, portalocker, iopath, pytorch3d
Successfully installed iopath-0.1.10 portalocker-2.10.1 pytorch3d-0.7.7 tqdm-4.66.5
```

Version of uv:
`0.2.36 (Homebrew 2024-08-13)`

**Comment by RafailFridman** [comment]
After actually reading the error until the end and adding `--no-build-isolation,` I was able to install pytorch3d :)

**Comment by charliermarsh** [comment]
Thanks for following up!
