### ISSUE TITLE
`uv pip install open3d` installs python3 package but has python2 init file

### ISSUE THREAD

**Issue by robert1003** [astral-sh/uv#6186]
Hi, when I tried to use uv to install open3d (and other packages), I encountered a weird issue which I got a python2 [__init__.py](https://github.com/isl-org/Open3D/blob/v0.3.0/util/pip_package/open3d/__init__.py) file while the whole package is in python3. Basically I can fix the package by copying [this](https://github.com/isl-org/Open3D/blob/v0.18.0/python/open3d/__init__.py) file to `lib/python3.11/site-packages/open3d/__init__.py`.

I couldn't reproduce this result consistently, so it is really hard to debug :\ Wonder if anyone has encountered similar issue before? Thanks!

**Comment by charliermarsh** [comment]
I would love to help but would need something that's more easily reproducible.

**Comment by robert1003** [comment]
Resulting package list:
```
❯ pip list
Package                        Version
------------------------------ ------------------
absl-py                        2.1.0
addict                         2.4.0
altair                         5.4.0
asttokens                      2.4.1
attrs                          24.2.0
backports.tarfile              1.2.0
blinker                        1.8.2
cachetools                     5.5.0
certifi                        2024.7.4
cffi                           1.17.0
chardet                        5.2.0
charset-normalizer             3.3.2
click                          8.1.7
colorama                       0.4.6
comm                           0.2.2
ConfigArgParse                 1.7
construct                      2.10.70
contourpy                      1.2.1
cryptography                   43.0.0
cycler                         0.12.1
Cython                         3.0.11
dash                           2.17.1
dash-core-components           2.0.0
dash-html-components           2.0.0
dash-table                     5.0.0
decorator                      5.1.1
distlib                        0.3.8
docutils                       0.21.2
executing                      2.0.1
fastjsonschema                 2.20.0
filelock                       3.15.4
Flask                          3.0.3
fonttools                      4.53.1
freetype-py                    2.4.0
fsspec                         2024.6.1
gitdb                          4.0.11
GitPython                      3.1.43
google-auth                    1.6.3
google-auth-oauthlib           0.4.6
grpcio                         1.65.5
idna                           3.7
imageio                        2.35.1
importlib-metadata             6.11.0
infraprotos                    1.2.2
iniconfig                      2.0.0
ipydatawidgets                 4.3.5
ipython                        8.26.0
ipywidgets                     8.1.3
itsdangerous                   2.2.0
jaraco.classes                 3.4.0
jaraco.context                 5.3.0
jaraco.functools               4.0.2
jedi                           0.19.1
jeepney                        0.8.0
Jinja2                         3.1.4
joblib                         1.4.2
jobqueue                       3.0.4
jsonschema                     4.23.0
jsonschema-specifications      2023.12.1
jupyter_core                   5.7.2
jupyterlab_widgets             3.0.11
keyring                        25.3.0
kiwisolver                     1.4.5
Markdown                       3.7
markdown-it-py                 3.0.0
MarkupSafe                     2.1.5
matplotlib                     3.9.2
matplotlib-inline              0.1.7
mdurl                          0.1.2
more-itertools                 10.4.0
mpmath                         1.3.0
msgpack                        1.0.8
mypy-extensions                1.0.0
narwhals                       1.4.2
nbformat                       5.10.4
nest-asyncio                   1.6.0
networkx                       3.3
nh3                            0.2.18
numpy                          1.23.5
nvidia-cublas-cu12             12.1.3.1
nvidia-cuda-cupti-cu12         12.1.105
nvidia-cuda-nvrtc-cu12         12.1.105
nvidia-cuda-runtime-cu12       12.1.105
nvidia-cudnn-cu12              9.1.0.70
nvidia-cufft-cu12              11.0.2.54
nvidia-curand-cu12             10.3.2.106
nvidia-cusolver-cu12           11.4.5.107
nvidia-cusparse-cu12           12.1.0.106
nvidia-nccl-cu12               2.20.5
nvidia-nvjitlink-cu12          12.6.20
nvidia-nvtx-cu12               12.1.105
oauthlib                       3.2.2
open3d                         0.18.0
open3d-python                  0.3.0.0
opencv-contrib-python-headless 4.6.0.66
opencv-python                  4.7.0
packaging                      23.2
pandas                         2.2.2
parso                          0.8.4
pexpect                        4.9.0
Pillow                         9.5.0
pip                            24.2
pkginfo                        1.10.0
platformdirs                   4.2.2
plotly                         5.23.0
pluggy                         1.5.0
prompt_toolkit                 3.0.47
protobuf                       4.25.4
psycopg2                       2.9.6
ptyprocess                     0.7.0
pure_eval                      0.2.3
py4j                           0.10.9.7
pyarrow                        17.0.0
pyasn1                         0.6.0
pyasn1_modules                 0.4.0
pybind11                       2.13.4
pybind11_global                2.13.4
pycparser                      2.22
pydeck                         0.9.1
pyftdi                         0.13.4
pyglet                         2.0.17
Pygments                       2.18.0
pylibftdi                      0.22.0
Pympler                        1.1
PyOpenGL                       3.1.7
PyOpenGL-accelerate            3.1.7
pyparsing                      3.1.2
pyproject-api                  1.6.1
pyquaternion                   0.9.9
pyrender                       0.1.45+ap.f7ccfa4b
pyserial                       3.5
pyspark                        3.5.0
pytest                         8.3.2
python-dateutil                2.9.0.post0
python-geohash                 0.8.5
pythreejs                      2.4.2
PyTurboJPEG                    1.7.5
pytz                           2024.1
pytz-deprecation-shim          0.1.0.post0
pyusb                          1.2.1
PyYAML                         6.0.2
pyzmq                          26.1.1
readme_renderer                44.0
referencing                    0.35.1
requests                       2.32.3
requests-oauthlib              2.0.0
requests-toolbelt              1.0.0
retrying                       1.3.4
rfc3986                        2.0.0
rich                           13.7.1
rpds-py                        0.20.0
rsa                            4.9
Rtree                          1.3.0
sbp                            6.0.1
scikit-learn                   1.5.1
scipy                          1.10.0
SecretStorage                  3.3.3
sentry-sdk                     1.30.0
setuptools                     72.1.0
shapely                        2.0.5
six                            1.16.0
smmap                          5.0.1
smplx                          0.1.28
splines                        0.3.0
stack-data                     0.6.3
streamlit                      1.23.0
sympy                          1.13.2
syrupy                         4.6.1
tb-nightly                     2.5.0a20210402
tenacity                       8.5.0
tensorboard-data-server        0.6.1
tensorboard-plugin-wit         1.8.1
threadpoolctl                  3.5.0
toml                           0.10.2
torch                          2.4.0
torchfile                      0.1.0
tornado                        6.4.1
tox                            4.15.1
tqdm                           4.66.5
traitlets                      5.14.3
traittypes                     0.2.1
trimesh                        4.4.6
triton                         3.0.0
twine                          5.1.1
typing_extensions              4.12.2
typing-inspect                 0.9.0
tzdata                         2024.1
tzlocal                        4.3.1
urllib3                        2.2.2
uv                             0.2.37
validators                     0.33.0
virtualenv                     20.26.3
visdom                         0.1.8.3
warp-lang                      1.3.1
watchdog                       4.0.2
wcwidth                        0.2.13
websocket-client               1.8.0
Werkzeug                       3.0.3
wheel                          0.44.0
widgetsnbextension             4.0.11
zipp                           3.20.0
```

**Comment by charliermarsh** [comment]
Thanks! I'll take a look (but probably not today -- prepping for a release).

**Comment by robert1003** [comment]
Thank you! The error message is:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/robert1003/.conda/envs/test_uv2/lib/python3.11/site-packages/open3d/__init__.py", line 9, in <module>
    from open3d.linux import *
  File "/home/robert1003/.conda/envs/test_uv2/lib/python3.11/site-packages/open3d/linux/__init__.py", line 7, in <module>
    globals().update(importlib.import_module('open3d.linux.open3d').__dict__)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/robert1003/.conda/envs/test_uv2/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: /home/robert1003/.conda/envs/test_uv2/lib/python3.11/site-packages/open3d/linux/open3d.so: undefined symbol: _Py_ZeroStruct
```

**Comment by samypr100** [comment]
What is your open3d version inside `/home/robert1003/.conda/envs/test_uv2/lib/python3.11/site-packages` when this happens? Is it `0.3.0` (what you linked to) since https://pypi.org/project/open3d/0.3.0/ does not seem to exist in the pypi (maybe some other registry?).

I also wonder if you're hitting some kind of edge case that ends up getting your the oldest open3d available, e.g. something like (but not exactly the same) the case described in https://github.com/astral-sh/uv/issues/6141

Do you have logs using e.g. `RUST_LOG=trace` or `--verbose` when the error occurs.

**Comment by robert1003** [comment]
the version is 0.18.0:
```bash
❯ pip list | grep open3d
pip is now uv; running uv pip...
open3d                         0.18.0
open3d-python                  0.3.0.0
❯ which python3
/home/robert1003/.conda/envs/test_uv2/bin/python3
❯ python3 -c 'import open3d as o3d'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/robert1003/.conda/envs/test_uv2/lib/python3.11/site-packages/open3d/__init__.py", line 9, in <module>
    from open3d.linux import *
  File "/home/robert1003/.conda/envs/test_uv2/lib/python3.11/site-packages/open3d/linux/__init__.py", line 7, in <module>
    globals().update(importlib.import_module('open3d.linux.open3d').__dict__)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/robert1003/.conda/envs/test_uv2/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: /home/robert1003/.conda/envs/test_uv2/lib/python3.11/site-packages/open3d/linux/open3d.so: undefined symbol: _Py_ZeroStruct
```

yeah I am very confused that it fetched that specific init file, it took me a while to find where is that file from...

**Comment by samypr100** [comment]
```
❯ pip list | grep open3d
pip is now uv; running uv pip...
open3d                         0.18.0
open3d-python                  0.3.0.0
```

Ok, this helped a lot.

It seems having both `open3d==0.18.0` and `open3d-python=0.3.0.0` is incompatible as they overwrite each other's namespaces. Depending on the order of installation, you could end up with files from one or the other in the same `site-packages/open3d` location.

Here's on [open3d-python=0.3.0.0](https://pypi.org/project/open3d-python/0.3.0.0/) on PyPI. The sdist shows me it uses `open3d` namespace with a very old build of open3d (2018).

It's possible one of your dependencies is introducing `open3d-python`, worth finding out which one it is. Avoid installing `open3d-python` as it's incompatible with `open3d==0.18.0`. It's either one or the other 😅

**Comment by robert1003** [comment]
Thank you for figuring this out! It appears that `smplx[all]` is the one pulling in `open3d-python`. I just removed that and it works. Thank you for your help!
