### ISSUE TITLE
`--no-build-isolation` has no effect in `uv add `

### ISSUE THREAD

**Issue by kabouzeid** [astral-sh/uv#6367]
The following works.
```
uv add torch
uv pip install --no-build-isolation "git+https://github.com/facebookresearch/pytorch3d.git"
```

While the following does **not** work. It seems like `--no-build-isolation` has no effect for the `add` subcommand.
```
uv add torch
uv add --no-build-isolation "git+https://github.com/facebookresearch/pytorch3d.git"
```

---

Here is the complete log:
```
➜ uv --version
uv 0.3.0 (Homebrew 2024-08-20)

➜ uv add torch
Resolved 33 packages in 511ms
   Built test @ file:///private/tmp/test
Prepared 1 package in 198ms
Installed 1 package in 0.71ms
 + test==0.1.0 (from file:///private/tmp/test)

➜ uv add --no-build-isolation "git+https://github.com/facebookresearch/pytorch3d.git"
 Updated https://github.com/facebookresearch/pytorch3d.git (05cbea1)
error: Build backend failed to determine extra requires with `build_wheel()` with exit status: 1
--- stdout:

--- stderr:
Traceback (most recent call last):
  File "<string>", line 14, in <module>
  File "/Users/karim/.cache/uv/builds-v0/.tmpqoAL9a/lib/python3.12/site-packages/setuptools/build_meta.py", line 332, in get_requires_for_build_wheel
    return self._get_build_requires(config_settings, requirements=[])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/karim/.cache/uv/builds-v0/.tmpqoAL9a/lib/python3.12/site-packages/setuptools/build_meta.py", line 302, in _get_build_requires
    self.run_setup()
  File "/Users/karim/.cache/uv/builds-v0/.tmpqoAL9a/lib/python3.12/site-packages/setuptools/build_meta.py", line 502, in run_setup
    super().run_setup(setup_script=setup_script)
  File "/Users/karim/.cache/uv/builds-v0/.tmpqoAL9a/lib/python3.12/site-packages/setuptools/build_meta.py", line 318, in run_setup
    exec(code, locals())
  File "<string>", line 15, in <module>
ModuleNotFoundError: No module named 'torch'
---
  Caused by: This error likely indicates that git+https://github.com/facebookresearch/pytorch3d.git depends on torch, but doesn't declare it as a build dependency. If git+https://github.com/facebookresearch/pytorch3d.git is a first-party package, consider adding torch to its `build-system.requires`. Otherwise, `uv pip install torch` into the environment and re-run with `--no-build-isolation`.
```

**Comment by charliermarsh** [comment]
Gah sorry, this is just an oversight.
