### ISSUE TITLE
Flaking Windows workspace tests

### ISSUE THREAD

**Issue by zanieb** [astral-sh/uv#6789]
I've seen a few new flakes on Windows. Maybe since https://github.com/astral-sh/uv/pull/6680

e.g. [here](https://github.com/astral-sh/uv/actions/runs/10607440812/job/29399888848?pr=6784)

```
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ Snapshot Summary ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Snapshot: uv_run_isolate
Source: E:\uv:533
───────────────────────────────────────────────────────────────────────────────
Expression: snapshot
───────────────────────────────────────────────────────────────────────────────
-old snapshot
+new results
────────────┬──────────────────────────────────────────────────────────────────
    0       │-success: true
    1       │-exit_code: 0
          0 │+success: false
          1 │+exit_code: 2
    2     2 │ ----- stdout -----
    3       │-Success
    4     3 │ 
    5     4 │ ----- stderr -----
    6     5 │ Using Python 3.12.[X] interpreter at: [PYTHON-3.12]
    7     6 │ Creating virtualenv at: .venv
    8     7 │ Resolved 8 packages in [TIME]
    9       │-Prepared 7 packages in [TIME]
   10       │-Installed 7 packages in [TIME]
   11       │- + albatross==0.1.0 (from file://[TEMP_DIR]/albatross-root-workspace)
   12       │- + anyio==4.3.0
   13       │- + bird-feeder==1.0.0 (from file://[TEMP_DIR]/albatross-root-workspace/packages/bird-feeder)
   14       │- + idna==3.6
   15       │- + seeds==1.0.0 (from file://[TEMP_DIR]/albatross-root-workspace/packages/seeds)
   16       │- + sniffio==1.3.1
   17       │- + tqdm==4.66.2
          8 │+error: Failed to prepare distributions
          9 │+  Caused by: Failed to fetch wheel: bird-feeder @ file://[TEMP_DIR]/albatross-root-workspace/packages/bird-feeder
         10 │+  Caused by: Build backend failed to build wheel through `build_editable()` with exit code: 1
         11 │+--- stdout:
         12 │+
         13 │+--- stderr:
         14 │+Traceback (most recent call last):
         15 │+  File "<string>", line 11, in <module>
         16 │+  File "[CACHE_DIR]/builds-v0/[TMP]/build.py", line 83, in build_editable
         17 │+    return os.path.basename(next(builder.build(directory=wheel_directory, versions=['editable'])))
         18 │+                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
         19 │+  File "[CACHE_DIR]/builds-v0/[TMP]/interface.py", line 90, in build
         20 │+    self.metadata.validate_fields()
         21 │+  File "[CACHE_DIR]/builds-v0/[TMP]/core.py", line 260, in validate_fields
         22 │+    self.core.validate_fields()
         23 │+  File "[CACHE_DIR]/builds-v0/[TMP]/core.py", line 1352, in validate_fields
         24 │+    getattr(self, attribute)
         25 │+  File "[CACHE_DIR]/builds-v0/[TMP]/core.py", line 1223, in dependencies
         26 │+    self._dependencies = list(self.dependencies_complex)
         27 │+                              ^^^^^^^^^^^^^^^^^^^^^^^^^
         28 │+  File "[CACHE_DIR]/builds-v0/[TMP]/core.py", line 1174, in dependencies_complex
         29 │+    from packaging.requirements import InvalidRequirement, Requirement
         30 │+  File "[CACHE_DIR]/builds-v0/[TMP]/requirements.py", line 7, in <module>
         31 │+    from ._parser import parse_requirement as _parse_requirement
         32 │+  File "[CACHE_DIR]/builds-v0/[TMP]/_parser.py", line 10, in <module>
         33 │+    from ._tokenizer import DEFAULT_RULES, Tokenizer
         34 │+  File "[CACHE_DIR]/builds-v0/[TMP]/_tokenizer.py", line 6, in <module>
         35 │+    from .specifiers import Specifier
         36 │+  File "[CACHE_DIR]/builds-v0/[TMP]/specifiers.py", line 16, in <module>
         37 │+    from .utils import canonicalize_version
         38 │+  File "[CACHE_DIR]/builds-v0/[TMP]/utils.py", line 8, in <module>
         39 │+    from .tags import Tag, parse_tag
         40 │+  File "[CACHE_DIR]/builds-v0/[TMP]/tags.py", line 26, in <module>
         41 │+    from . import _manylinux, _musllinux
         42 │+  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
         43 │+  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
         44 │+  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
         45 │+  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
         46 │+  File "<frozen importlib._bootstrap_external>", line 1128, in get_code
         47 │+  File "<frozen importlib._bootstrap_external>", line 1186, in get_data
         48 │+PermissionError: [Errno 13] Permission denied: 'E:\/tmp-uv\/[TMP]/_musllinux.py'
         49 │+---
────────────┴──────────────────────────────────────────────────────────────────
Stopped on the first failure. Run `cargo insta test` to run all snapshots.
test test_uv_run_isolate ... FAILED

failures:

failures:
    test_uv_run_isolate
```

**Comment by zanieb** [comment]
Closing in favor of #6940
