### ISSUE TITLE
If `pip install visidata` works, shouldn't `uvx visidata`?

### ISSUE THREAD

**Issue by reagle** [astral-sh/uv#8184]
Hi, I'm new to uv, and the first thing I tested what if I can [use the visidata cli](https://github.com/saulpw/visidata/issues/2560).

```
❯ uvx visidata
Traceback (most recent call last):
  File "/Users/reagle/.cache/uv/archive-v0/M2Rslfs0mZFGrNRElBxLC/bin/visidata", line 7, in <module>
    from visidata.main import vd_cli
  File "/Users/reagle/.cache/uv/archive-v0/M2Rslfs0mZFGrNRElBxLC/lib/python3.12/site-packages/visidata/__init__.py", line 157, in <module>
    importFeatures()
  File "/Users/reagle/.cache/uv/archive-v0/M2Rslfs0mZFGrNRElBxLC/lib/python3.12/site-packages/visidata/__init__.py", line 139, in importFeatures
    vd.importSubmodules('visidata.features')
  File "/Users/reagle/.cache/uv/archive-v0/M2Rslfs0mZFGrNRElBxLC/lib/python3.12/site-packages/visidata/settings.py", line 508, in importSubmodules
    vd.importModule(pkgname + '.' + module.name)
  File "/Users/reagle/.cache/uv/archive-v0/M2Rslfs0mZFGrNRElBxLC/lib/python3.12/site-packages/visidata/settings.py", line 491, in importModule
    r = importlib.import_module(pkgname)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reagle/.pyenv/versions/3.12.7/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reagle/.cache/uv/archive-v0/M2Rslfs0mZFGrNRElBxLC/lib/python3.12/site-packages/visidata/features/errors_guide.py", line 1, in <module>
    from visidata import GuideSheet, vd
ImportError: cannot import name 'GuideSheet' from partially initialized module 'visidata' (most likely due to a circular import) (/Users/reagle/.cache/uv/archive-v0/M2Rslfs0mZFGrNRElBxLC/lib/python3.12/site-packages/visidata/__init__.py)
```

My system:

```
macOS 14.6.1 23G93 arm64
❯ brin uv
==> uv: stable 0.4.20 (bottled), HEAD
Extremely fast Python package installer and resolver, written in Rust
https://github.com/astral-sh/uv
Installed
/opt/homebrew/Cellar/uv/0.4.20 (17 files, 25MB) *
  Poured from bottle using the formulae.brew.sh API on 2024-10-14 at 08:09:14
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/u/uv.rb
License: Apache-2.0 OR MIT
==> Dependencies
Build: pkg-config ✔, rust ✔
==> Options
--HEAD
	Install HEAD version
==> Caveats
zsh completions have been installed to:
  /opt/homebrew/share/zsh/site-functions
==> Analytics
install: 12,631 (30 days), 32,454 (90 days), 57,182 (365 days)
install-on-request: 11,833 (30 days), 29,824 (90 days), 52,612 (365 days)
build-error: 2 (30 days)
```

**Comment by zanieb** [comment]
This looks like a problem with `pip` as well?

```
❯ uv venv --seed
Using CPython 3.12.6
Creating virtual environment with seed packages at: .venv
 + pip==24.2
Activate with: source .venv/bin/activate
❯ source .venv/bin/activate
❯ pip install visidata
Collecting visidata
  Downloading visidata-3.1-py3-none-any.whl.metadata (5.3 kB)
Collecting python-dateutil (from visidata)
  Downloading python_dateutil-2.9.0.post0-py2.py3-none-any.whl.metadata (8.4 kB)
Collecting importlib-metadata>=3.6 (from visidata)
  Downloading importlib_metadata-8.5.0-py3-none-any.whl.metadata (4.8 kB)
Collecting zipp>=3.20 (from importlib-metadata>=3.6->visidata)
  Downloading zipp-3.20.2-py3-none-any.whl.metadata (3.7 kB)
Collecting six>=1.5 (from python-dateutil->visidata)
  Downloading six-1.16.0-py2.py3-none-any.whl.metadata (1.8 kB)
Downloading visidata-3.1-py3-none-any.whl (529 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 529.5/529.5 kB 6.9 MB/s eta 0:00:00
Downloading importlib_metadata-8.5.0-py3-none-any.whl (26 kB)
Downloading python_dateutil-2.9.0.post0-py2.py3-none-any.whl (229 kB)
Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Downloading zipp-3.20.2-py3-none-any.whl (9.2 kB)
Installing collected packages: zipp, six, python-dateutil, importlib-metadata, visidata
Successfully installed importlib-metadata-8.5.0 python-dateutil-2.9.0.post0 six-1.16.0 visidata-3.1 zipp-3.20.2
❯ visidata
Traceback (most recent call last):
  File "/Users/zb/workspace/uv/.venv/bin/visidata", line 5, in <module>
    from visidata.main import vd_cli
  File "/Users/zb/workspace/uv/.venv/lib/python3.12/site-packages/visidata/__init__.py", line 157, in <module>
    importFeatures()
  File "/Users/zb/workspace/uv/.venv/lib/python3.12/site-packages/visidata/__init__.py", line 139, in importFeatures
    vd.importSubmodules('visidata.features')
  File "/Users/zb/workspace/uv/.venv/lib/python3.12/site-packages/visidata/settings.py", line 508, in importSubmodules
    vd.importModule(pkgname + '.' + module.name)
  File "/Users/zb/workspace/uv/.venv/lib/python3.12/site-packages/visidata/settings.py", line 491, in importModule
    r = importlib.import_module(pkgname)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zb/.local/share/uv/python/cpython-3.12.6-macos-aarch64-none/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zb/workspace/uv/.venv/lib/python3.12/site-packages/visidata/features/errors_guide.py", line 1, in <module>
    from visidata import GuideSheet, vd
ImportError: cannot import name 'GuideSheet' from partially initialized module 'visidata' (most likely due to a circular import) (/Users/zb/workspace/uv/.venv/lib/python3.12/site-packages/visidata/__init__.py)
```

**Comment by zanieb** [comment]
Seems like https://github.com/saulpw/visidata/issues/2561 https://github.com/saulpw/visidata/issues/2562

**Comment by reagle** [comment]
Weird coincidence that visidata updated to 3.1 (with a problem) the day I try to experiment with uvx. Closing!
