### ISSUE TITLE
`uv pip compile` generates requirements for faulty dependencies

### ISSUE THREAD

**Issue by alphavector** [astral-sh/uv#8372]
Just for fun, I created a script that generates requirements.txt c using `uv` and `pip-compile` for the `577,502` dependencies that exist in pypi. 

I'm not quite sure if this is a bug, but I can generate requirements for modules that I then can't install because of the bug

`pip-compile` doesn't allow me to do this right away, at the requirements.txt generation stage

> disclaimer: I am not the author of the installed dependencies, install them at your own risk, preferably in an isolated environment

```sh
/# uv --version
uv 0.4.24
/# uv pip compile -v <(echo "10daysweb<=0.1.3")
DEBUG uv 0.4.24
DEBUG Starting Python discovery for a default Python
DEBUG Looking for exact match for request a default Python
DEBUG Searching for default Python interpreter in managed installations or system path
DEBUG Searching for managed installations at `/root/.local/share/uv/python`
DEBUG Found `cpython-3.12.7-linux-x86_64-gnu` at `/usr/local/bin/python` (search path)
DEBUG Using Python 3.12.7 interpreter at /usr/local/bin/python for builds
DEBUG Using request timeout of 30s
DEBUG Solving with installed Python version: 3.12.7
DEBUG Solving with target Python version: >=3.12.7
DEBUG Adding direct dependency: 10daysweb<=0.1.3
DEBUG Found stale response for: https://pypi.org/simple/10daysweb/
DEBUG Sending revalidation request for: https://pypi.org/simple/10daysweb/
DEBUG Found not-modified response for: https://pypi.org/simple/10daysweb/
DEBUG Searching for a compatible version of 10daysweb (<=0.1.3)
DEBUG Acquired lock for `/root/.cache/uv/sdists-v4/pypi/10daysweb/0.1.3`
DEBUG Found fresh response for: https://files.pythonhosted.org/packages/cd/f4/0da767e9a78143cdb40f5bc763fbfdbe016cc5832d5b7fddfd04a4689504/10daysweb-0.1.3.tar.gz
DEBUG No static `pyproject.toml` available for: 10daysweb==0.1.3 (MissingPyprojectToml)
DEBUG No static `PKG-INFO` available for: 10daysweb==0.1.3 (PkgInfo(UnsupportedMetadataVersion("1.2")))
DEBUG Found static `egg-info` for: 10daysweb==0.1.3
DEBUG Released lock at `/root/.cache/uv/sdists-v4/pypi/10daysweb/0.1.3/.lock`
DEBUG Selecting: 10daysweb==0.1.3 [compatible] (10daysweb-0.1.3.tar.gz)
DEBUG Adding transitive dependency for 10daysweb==0.1.3: httptools*
DEBUG Found stale response for: https://pypi.org/simple/httptools/
DEBUG Sending revalidation request for: https://pypi.org/simple/httptools/
DEBUG Found not-modified response for: https://pypi.org/simple/httptools/
DEBUG Searching for a compatible version of httptools (*)
DEBUG Selecting: httptools==0.6.4 [compatible] (httptools-0.6.4-cp312-cp312-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl)
DEBUG Found fresh response for: https://files.pythonhosted.org/packages/f7/d8/b644c44acc1368938317d76ac991c9bba1166311880bcc0ac297cb9d6bd7/httptools-0.6.4-cp312-cp312-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata
DEBUG Tried 2 versions: 10daysweb 1, httptools 1
DEBUG Split specific environment resolution took 0.042s
Resolved 2 packages in 48ms
# This file was autogenerated by uv via the following command:
#    uv pip compile /dev/fd/63
10daysweb==0.1.3
    # via -r dev/fd/63
httptools==0.6.4
    # via 10daysweb
/# uv pip install --system -v -r <(echo "10daysweb<=0.1.3")
DEBUG uv 0.4.24
DEBUG Searching for default Python interpreter in system path
DEBUG Found `cpython-3.12.7-linux-x86_64-gnu` at `/usr/local/bin/python` (search path)
Using Python 3.12.7 environment at /usr/local
DEBUG Acquired lock for `/usr/local`
DEBUG At least one requirement is not satisfied: 10daysweb<=0.1.3
DEBUG Using request timeout of 30s
DEBUG Solving with installed Python version: 3.12.7
DEBUG Solving with target Python version: >=3.12.7
DEBUG Adding direct dependency: 10daysweb<=0.1.3
DEBUG Found fresh response for: https://pypi.org/simple/10daysweb/
DEBUG Searching for a compatible version of 10daysweb (<=0.1.3)
DEBUG Selecting: 10daysweb==0.1.3 [compatible] (10daysweb-0.1.3.tar.gz)
DEBUG Acquired lock for `/root/.cache/uv/sdists-v4/pypi/10daysweb/0.1.3`
DEBUG Found fresh response for: https://files.pythonhosted.org/packages/cd/f4/0da767e9a78143cdb40f5bc763fbfdbe016cc5832d5b7fddfd04a4689504/10daysweb-0.1.3.tar.gz
DEBUG No static `pyproject.toml` available for: 10daysweb==0.1.3 (MissingPyprojectToml)
DEBUG No static `PKG-INFO` available for: 10daysweb==0.1.3 (PkgInfo(UnsupportedMetadataVersion("1.2")))
DEBUG Found static `egg-info` for: 10daysweb==0.1.3
DEBUG Released lock at `/root/.cache/uv/sdists-v4/pypi/10daysweb/0.1.3/.lock`
DEBUG Adding transitive dependency for 10daysweb==0.1.3: httptools*
DEBUG Found fresh response for: https://pypi.org/simple/httptools/
DEBUG Searching for a compatible version of httptools (*)
DEBUG Selecting: httptools==0.6.4 [compatible] (httptools-0.6.4-cp312-cp312-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl)
DEBUG Found fresh response for: https://files.pythonhosted.org/packages/f7/d8/b644c44acc1368938317d76ac991c9bba1166311880bcc0ac297cb9d6bd7/httptools-0.6.4-cp312-cp312-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata
DEBUG Tried 2 versions: 10daysweb 1, httptools 1
DEBUG Split specific environment resolution took 0.007s
Resolved 2 packages in 8ms
DEBUG Identified uncached distribution: 10daysweb==0.1.3
DEBUG Requirement already cached: httptools==0.6.4
DEBUG Unnecessary package: build==1.2.2.post1
DEBUG Unnecessary package: click==8.1.7
DEBUG Unnecessary package: packaging==24.1
DEBUG Preserving seed package: pip==24.2
DEBUG Unnecessary package: pip-tools==7.4.1
DEBUG Unnecessary package: pyproject-hooks==1.2.0
DEBUG Preserving seed package: setuptools==75.2.0
DEBUG Preserving seed package: wheel==0.44.0
DEBUG Acquired lock for `/root/.cache/uv/sdists-v4/pypi/10daysweb/0.1.3`
DEBUG Found fresh response for: https://files.pythonhosted.org/packages/cd/f4/0da767e9a78143cdb40f5bc763fbfdbe016cc5832d5b7fddfd04a4689504/10daysweb-0.1.3.tar.gz
DEBUG Building: 10daysweb==0.1.3
DEBUG Ignoring empty directory
DEBUG Resolving build requirements
DEBUG Solving with installed Python version: 3.12.7
DEBUG Solving with target Python version: >=3.12.7
DEBUG Adding direct dependency: setuptools>=40.8.0
DEBUG Found fresh response for: https://pypi.org/simple/setuptools/
DEBUG Searching for a compatible version of setuptools (>=40.8.0)
DEBUG Selecting: setuptools==75.2.0 [compatible] (setuptools-75.2.0-py3-none-any.whl)
DEBUG Found fresh response for: https://files.pythonhosted.org/packages/31/2d/90165d51ecd38f9a02c6832198c13a4e48652485e2ccf863ebb942c531b6/setuptools-75.2.0-py3-none-any.whl.metadata
DEBUG Tried 1 versions: setuptools 1
DEBUG Split specific environment resolution took 0.004s
DEBUG Installing in setuptools==75.2.0 in /root/.cache/uv/builds-v0/.tmp0P8klW
DEBUG Requirement already cached: setuptools==75.2.0
DEBUG Installing build requirement: setuptools==75.2.0
DEBUG Creating PEP 517 build environment
DEBUG Calling `setuptools.build_meta:__legacy__.get_requires_for_build_wheel()`
DEBUG Traceback (most recent call last):
DEBUG   File "<string>", line 14, in <module>
DEBUG   File "/root/.cache/uv/builds-v0/.tmp0P8klW/lib/python3.12/site-packages/setuptools/build_meta.py", line 332, in get_requires_for_build_wheel
DEBUG     return self._get_build_requires(config_settings, requirements=[])
DEBUG            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
DEBUG   File "/root/.cache/uv/builds-v0/.tmp0P8klW/lib/python3.12/site-packages/setuptools/build_meta.py", line 302, in _get_build_requires
DEBUG     self.run_setup()
DEBUG   File "/root/.cache/uv/builds-v0/.tmp0P8klW/lib/python3.12/site-packages/setuptools/build_meta.py", line 516, in run_setup
DEBUG     super().run_setup(setup_script=setup_script)
DEBUG   File "/root/.cache/uv/builds-v0/.tmp0P8klW/lib/python3.12/site-packages/setuptools/build_meta.py", line 318, in run_setup
DEBUG     exec(code, locals())
DEBUG   File "<string>", line 10, in <module>
DEBUG   File "<frozen codecs>", line 918, in open
DEBUG FileNotFoundError: [Errno 2] No such file or directory: '/root/.cache/uv/sdists-v4/pypi/10daysweb/0.1.3/OUxfaHy9DJ-vovkC1YVHz/10daysweb-0.1.3.tar.gz/readme.md'
DEBUG Released lock at `/root/.cache/uv/sdists-v4/pypi/10daysweb/0.1.3/.lock`
DEBUG Released lock at `/tmp/uv-1b696e695b7c17a7.lock`
error: Failed to prepare distributions
  Caused by: Failed to download and build `10daysweb==0.1.3`
  Caused by: Build backend failed to determine requirements with `build_wheel()` (exit status: 1)

[stderr]
Traceback (most recent call last):
  File "<string>", line 14, in <module>
  File "/root/.cache/uv/builds-v0/.tmp0P8klW/lib/python3.12/site-packages/setuptools/build_meta.py", line 332, in get_requires_for_build_wheel
    return self._get_build_requires(config_settings, requirements=[])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/uv/builds-v0/.tmp0P8klW/lib/python3.12/site-packages/setuptools/build_meta.py", line 302, in _get_build_requires
    self.run_setup()
  File "/root/.cache/uv/builds-v0/.tmp0P8klW/lib/python3.12/site-packages/setuptools/build_meta.py", line 516, in run_setup
    super().run_setup(setup_script=setup_script)
  File "/root/.cache/uv/builds-v0/.tmp0P8klW/lib/python3.12/site-packages/setuptools/build_meta.py", line 318, in run_setup
    exec(code, locals())
  File "<string>", line 10, in <module>
  File "<frozen codecs>", line 918, in open
FileNotFoundError: [Errno 2] No such file or directory: '/root/.cache/uv/sdists-v4/pypi/10daysweb/0.1.3/OUxfaHy9DJ-vovkC1YVHz/10daysweb-0.1.3.tar.gz/readme.md'

```

```sh
/# pip-compile --version
pip-compile, version 7.4.1
/# pip-compile -v -r <(echo "10daysweb<=0.1.3") -o /dev/null
Using indexes:
  https://pypi.org/simple

                          ROUND 1
  Collecting 10daysweb<=0.1.3 (from -r /dev/fd/63 (line 1))
    Using cached 10daysweb-0.1.3.tar.gz (9.2 kB)
    Preparing metadata (setup.py) ... error
    error: subprocess-exited-with-error

    × python setup.py egg_info did not run successfully.
    │ exit code: 1
    ╰─> [8 lines of output]
        Traceback (most recent call last):
          File "<string>", line 2, in <module>
          File "<pip-setuptools-caller>", line 34, in <module>
          File "/tmp/pip-resolve-55x1h_6i/10daysweb_786e9b60557d4eb48a9ac4ef8db40b69/setup.py", line 10, in <module>
            with open(path.join(here, 'readme.md'), encoding='utf-8') as f:
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          File "<frozen codecs>", line 918, in open
        FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-resolve-55x1h_6i/10daysweb_786e9b60557d4eb48a9ac4ef8db40b69/readme.md'
        [end of output]

    note: This error originates from a subprocess, and is likely not a problem with pip.
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/pip/_internal/operations/build/metadata_legacy.py", line 64, in generate_metadata
    call_subprocess(
  File "/usr/local/lib/python3.12/site-packages/pip/_internal/utils/subprocess.py", line 209, in call_subprocess
    raise error
pip._internal.exceptions.InstallationSubprocessError: python setup.py egg_info exited with 1

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/pip-compile", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/usr/local/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/piptools/scripts/compile.py", line 470, in cli
    results = resolver.resolve(max_rounds=max_rounds)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/piptools/resolver.py", line 604, in resolve
    is_resolved = self._do_resolve(
                  ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/piptools/resolver.py", line 636, in _do_resolve
    resolver.resolve(
  File "/usr/local/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 95, in resolve
    result = self._result = resolver.resolve(
                            ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pip/_vendor/resolvelib/resolvers.py", line 546, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pip/_vendor/resolvelib/resolvers.py", line 397, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "/usr/local/lib/python3.12/site-packages/pip/_vendor/resolvelib/resolvers.py", line 173, in _add_to_criteria
    if not criterion.candidates:
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pip/_vendor/resolvelib/structs.py", line 156, in __bool__
    return bool(self._sequence)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 174, in __bool__
    return any(self)
           ^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 162, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
                       ^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 53, in _iter_built
    candidate = func()
                ^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 186, in _make_candidate_from_link
    base: Optional[BaseCandidate] = self._make_base_candidate_from_link(
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 232, in _make_base_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
                                       ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 303, in __init__
    super().__init__(
  File "/usr/local/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 158, in __init__
    self.dist = self._prepare()
                ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 235, in _prepare
    dist = self._prepare_distribution()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 314, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pip/_internal/operations/prepare.py", line 527, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pip/_internal/operations/prepare.py", line 642, in _prepare_linked_requirement
    dist = _get_prepared_distribution(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pip/_internal/operations/prepare.py", line 72, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(
  File "/usr/local/lib/python3.12/site-packages/pip/_internal/distributions/sdist.py", line 69, in prepare_distribution_metadata
    self.req.prepare_metadata()
  File "/usr/local/lib/python3.12/site-packages/pip/_internal/req/req_install.py", line 581, in prepare_metadata
    self.metadata_directory = generate_metadata_legacy(
                              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pip/_internal/operations/build/metadata_legacy.py", line 71, in generate_metadata
    raise MetadataGenerationFailed(package_details=details) from error
pip._internal.exceptions.MetadataGenerationFailed: metadata generation failed
```

**Comment by charliermarsh** [comment]
It's possible to generate a resolution that includes a package that ultimately doesn't build on your machine. Resolution only requires extracting package metadata, but a package could fail to build for other reasons.
