### ISSUE TITLE
A sequence of uv add an uv remove loses a package's __init__.py

### ISSUE THREAD

**Issue by mgedmin** [astral-sh/uv#8562]
Steps to reproduce:

- mkdir /tmp/buggybyg && cd /tmp/buggybug
- uv init
- uv add austin-tui  # if you uv run austin-tui now it complains that austin is missing
- uv add austin   # oops wrong package
- uv add austin-dist  # this is the right one
- uv remove austin  # remove the wrong one
- uv run austin-tui  # this now breaks

Expected: austin-tui works

Actual: 

```
Traceback (most recent call last):
  File "/tmp/buggybug/.venv/bin/austin-tui", line 5, in <module>
    from austin_tui.__main__ import main
  File "/tmp/buggybug/.venv/lib/python3.12/site-packages/austin_tui/__main__.py", line 30, in <module>
    from austin import AustinError
ImportError: cannot import name 'AustinError' from 'austin' (unknown location)
```

`uv sync`  failed to improve the situation.

`uv remove austin-dist && uv add austin-dist` failed to improve the situation

`uv remove austin-tui && uv add austin-tui` fixed it

I think what happened was that multiple unrelated packages were somehow both claiming ownership of .venv/lib/python3.12/site-packages/austin/__init__.py, and removing one of them removed the file.

**Comment by zanieb** [comment]
Unfortunately this might just be a behavior of Python when package modules overlap. I'm not sure if we can do anything about it.
