### ISSUE TITLE
`uv publish` trusted publish integration test fails with 400 (already exists)

### ISSUE THREAD

**Issue by zanieb** [astral-sh/uv#8817]
```
DEBUG Upload error response: {"message": "The server could not comply with the request since it is either malformed or otherwise incorrect.\n\n\nFile already exists ('astral_test_trusted_publishing-0.1.532-py3-none-any.whl', with blake2_256 hash 'd97b4758301f66fcdaea1b956f8175d2619aa12c5016fbbab940a117bbee752d'). See https://test.pypi.org/help/#file-name-reuse for more information.\n\n", "code": "400 File already exists ('astral_test_trusted_publishing-0.1.532-py3-none-any.whl', with blake2_256 hash 'd97b4758301f66fcdaea1b956f8175d2619aa12c5016fbbab940a117bbee752d'). See https://test.pypi.org/help/#file-name-reuse for more information.", "title": "Bad Request"}
error: Failed to publish `dist/astral_test_trusted_publishing-0.1.532-py3-none-any.whl` to https://test.pypi.org/legacy/
  Caused by: Upload failed with status code 400 Bad Request. Server says: 400 File already exists ('astral_test_trusted_publishing-0.1.532-py3-none-any.whl', with blake2_256 hash 'd97b4758301f66fcdaea1b956f8175d2619aa12c5016fbbab940a117bbee752d'). See https://test.pypi.org/help/#file-name-reuse for more information.
Traceback (most recent call last):
  File "/home/runner/work/uv/uv/scripts/publish/test_publish.py", line 422, in <module>
    main()
  File "/home/runner/work/uv/uv/scripts/publish/test_publish.py", line 418, in main
    publish_project(project_name, uv, client)
  File "/home/runner/work/uv/uv/scripts/publish/test_publish.py", line 284, in publish_project
    check_call(args, cwd=project_dir, env=env)
  File "/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/subprocess.py", line 413, in check_call

uv pip compile not updated, missing 2 files for 0.1.1060: `astral-test-token==0.1.1059 --hash=sha256:b724b7fcce920db8313f9715791b537a25ccbca95fb4ef24ad02a82a7ec2866e --hash=sha256:f955569bc2ecebacace657bd9b34aba7153abd59556867548be39f85f91e215d
`, sleeping for 1s: `[https://dl.cloudsmith.io/public/astral-test/astral-test-1/python/simple/`](https://dl.cloudsmith.io/public/astral-test/astral-test-1/python/simple/%60)
uv pip compile not updated, missing 2 files for 0.1.1060: `astral-test-token==0.1.1059 --hash=sha256:b724b7fcce920db8313f9715791b537a25ccbca95fb4ef24ad02a82a7ec2866e --hash=sha256:f955569bc2ecebacace657bd9b34aba7153abd59556867548be39f85f91e215d
`, sleeping for 1s: `[https://dl.cloudsmith.io/public/astral-test/astral-test-1/python/simple/`](https://dl.cloudsmith.io/public/astral-test/astral-test-1/python/simple/%60)

=== 4. Publishing modified astral-test-token 0.1.1060 again with skip existing (error test) ===
uv pip compile not updated, missing 2 files for 0.1.1060: `astral-test-token==0.1.1059 --hash=sha256:b724b7fcce920db8313f9715791b537a25ccbca95fb4ef24ad02a82a7ec2866e --hash=sha256:f955569bc2ecebacace657bd9b34aba7153abd59556867548be39f85f91e215d
`, sleeping for 1s: `[https://dl.cloudsmith.io/public/astral-test/astral-test-1/python/simple/`](https://dl.cloudsmith.io/public/astral-test/astral-test-1/python/simple/%60)
uv pip compile not updated, missing 2 files for 0.1.1060: `astral-test-token==0.1.1059 --hash=sha256:b724b7fcce920db8313f9715791b537a25ccbca95fb4ef24ad02a82a7ec2866e --hash=sha256:f955569bc2ecebacace657bd9b34aba7153abd59556867548be39f85f91e215d
`, sleeping for 1s: `[https://dl.cloudsmith.io/public/astral-test/astral-test-1/python/simple/`](https://dl.cloudsmith.io/public/astral-test/astral-test-1/python/simple/%60)
uv pip compile not updated, missing 2 files for 0.1.1060: `astral-test-token==0.1.1059 --hash=sha256:b724b7fcce920db8313f9715791b537a25ccbca95fb4ef24ad02a82a7ec2866e --hash=sha256:f955569bc2ecebacace657bd9b34aba7153abd59556867548be39f85f91e215d
`, sleeping for 1s: `[https://dl.cloudsmith.io/public/astral-test/astral-test-1/python/simple/`](https://dl.cloudsmith.io/public/astral-test/astral-test-1/python/simple/%60)
uv pip compile not updated, missing 2 files for 0.1.1060: `astral-test-token==0.1.1059 --hash=sha256:b724b7fcce920db8313f9715791b537a25ccbca95fb4ef24ad02a82a7ec2866e --hash=sha256:f955569bc2ecebacace657bd9b34aba7153abd59556867548be39f85f91e215d
`, sleeping for 1s: `[https://dl.cloudsmith.io/public/astral-test/astral-test-1/python/simple/`](https://dl.cloudsmith.io/public/astral-test/astral-test-1/python/simple/%60)
uv pip compile not updated, missing 2 files for 0.1.1060: `astral-test-token==0.1.1059 --hash=sha256:b724b7fcce920db8313f9715791b537a25ccbca95fb4ef24ad02a82a7ec2866e --hash=sha256:f955569bc2ecebacace657bd9b34aba7153abd59556867548be39f85f91e215d
`, sleeping for 1s: `[https://dl.cloudsmith.io/public/astral-test/astral-test-1/python/simple/`](https://dl.cloudsmith.io/public/astral-test/astral-test-1/python/simple/%60)
uv pip compile not updated, missing 2 files for 0.1.1060: `astral-test-token==0.1.1059 --hash=sha256:b724b7fcce920db8313f9715791b537a25ccbca95fb4ef24ad02a82a7ec2866e --hash=sha256:f955569bc2ecebacace657bd9b34aba7153abd59556867548be39f85f91e215d
`, sleeping for 1s: `[https://dl.cloudsmith.io/public/astral-test/astral-test-1/python/simple/`](https://dl.cloudsmith.io/public/astral-test/astral-test-1/python/simple/%60)
uv pip compile not updated, missing 2 files for 0.1.1060: `astral-test-token==0.1.1059 --hash=sha256:b724b7fcce920db8313f9715791b537a25ccbca95fb4ef24ad02a82a7ec2866e --hash=sha256:f955569bc2ecebacace657bd9b34aba7153abd59556867548be39f85f91e215d
`, sleeping for 1s: `[https://dl.cloudsmith.io/public/astral-test/astral-test-1/python/simple/`](https://dl.cloudsmith.io/public/astral-test/astral-test-1/python/simple/%60)
uv pip compile not updated, missing 2 files for 0.1.1060: `astral-test-token==0.1.1059 --hash=sha256:b724b7fcce920db8313f9715791b537a25ccbca95fb4ef24ad02a82a7ec2866e --hash=sha256:f955569bc2ecebacace657bd9b34aba7153abd59556867548be39f85f91e215d
`, sleeping for 1s: `[https://dl.cloudsmith.io/public/astral-test/astral-test-1/python/simple/`](https://dl.cloudsmith.io/public/astral-test/astral-test-1/python/simple/%60)
uv pip compile not updated, missing 2 files for 0.1.1060: `astral-test-token==0.1.1059 --hash=sha256:b724b7fcce920db8313f9715791b537a25ccbca95fb4ef24ad02a82a7ec2866e --hash=sha256:f955569bc2ecebacace657bd9b34aba7153abd59556867548be39f85f91e215d
`, sleeping for 1s: `[https://dl.cloudsmith.io/public/astral-test/astral-test-1/python/simple/`](https://dl.cloudsmith.io/public/astral-test/astral-test-1/python/simple/%60)
uv pip compile not updated, missing 2 files for 0.1.1060: `astral-test-token==0.1.1059 --hash=sha256:b724b7fcce920db8313f9715791b537a25ccbca95fb4ef24ad02a82a7ec2866e --hash=sha256:f955569bc2ecebacace657bd9b34aba7153abd59556867548be39f85f91e215d
`, sleeping for 1s: `[https://dl.cloudsmith.io/public/astral-test/astral-test-1/python/simple/`](https://dl.cloudsmith.io/public/astral-test/astral-test-1/python/simple/%60)

Publish astral-test-trusted-publishing for pypi-trusted-publishing

=== 1. Publishing a new version: astral-test-trusted-publishing 0.1.532 https://test.pypi.org/legacy/ ===
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '[PosixPath('/home/runner/work/uv/uv/uv'), 'publish', '--publish-url', 'https://test.pypi.org/legacy/', '--trusted-publishing', 'always']' returned non-zero exit status 2.
```

https://github.com/astral-sh/uv/actions/runs/11672084476/job/32500017593?pr=8419

**Comment by FauxPrada** [comment]
Hi, we get a similar response using Azure Artifacts with uv 0.4.30. Hard fails on conflict instead of passing to the next build release.

```
DEBUG Response code for https://pkgs.dev.azure.com/Company/Package/_packaging/Feed/pypi/upload/: 409 Conflict
DEBUG Upload error response: {"$id":"1","innerException":null,"message":"The feed 'Feed' already contains file 'package-2.1.0-py3-none-any.whl' in package 'package 2.1.0'.","typeName":"Microsoft.VisualStudio.Services.Packaging.Shared.WebApi.Exceptions.PackageAlreadyExistsException, Microsoft.VisualStudio.Services.Packaging.Shared.WebApi","typeKey":"PackageAlreadyExistsException","errorCode":0,"eventId":3000}
error: Failed to publish `dist\package-2.1.0-py3-none-any.whl` to https://pkgs.dev.azure.com/Company/Package/_packaging/Feed/pypi/upload/
  Caused by: Upload failed with status code 409 Conflict. Server says: {"$id":"1","innerException":null,"message":"The feed 'Feed' already contains file 'package-2.1.0-py3-none-any.whl' in package 'package 2.1.0'.","typeName":"Microsoft.VisualStudio.Services.Packaging.Shared.WebApi.Exceptions.PackageAlreadyExistsException, Microsoft.VisualStudio.Services.Packaging.Shared.WebApi","typeKey":"PackageAlreadyExistsException","errorCode":0,"eventId":3000}
```

Reverting to 0.4.29 (85f9a0d0e) solves the problem. For any Windows users wanting a quick fix:

```
powershell.exe -ExecutionPolicy ByPass -c "irm https://astral.sh/uv/0.4.29/install.ps1 | iex"
```
Cheers!

**Comment by konstin** [comment]
@FauxPrada Hi, we made a change to the `uv publish` interface, from the last release on you need to add `--check-url <index url>` to skip existing files (https://github.com/astral-sh/uv/pull/8531).

**Comment by FauxPrada** [comment]
> @FauxPrada Hi, we made a change to the `uv publish` interface, from the last release on you need to add `--check-url <index url>` to skip existing files (#8531).

Ooooh you're right!! In the case of Artifacts it's the same URL as our `extra-index-url` :)

```
uv publish --username VssSessionToken --check-url https://VssSessionToken@pkgs.dev.azure.com/Company/Package/_packaging/Feed/pypi/simple/
```

Works like a charm, thanks! 👍🏻 

As a FR would it be possible to have this `check-url` available to set in `pyproject.toml`? Saves me trying to remember URLs and enviromentals.

**Comment by konstin** [comment]
Totally with you: https://github.com/astral-sh/uv/issues/8864

**Comment by FauxPrada** [comment]
Ayyy you read my mind

**Comment by konstin** [comment]
Fixed by #10984
