### ISSUE TITLE
Behavior of `uv run` depends on the app name

### ISSUE THREAD

**Issue by fepegar** [astral-sh/uv#9719]
Hello and thanks for this amazing project!

I am trying to use an entry point of a local app from a local library without adding the app as a dependency, i.e., using `--with` or `--with-editable`. However, the flags seemingly make thins fali **depending of the name of the app**. I'm very confused by this behavior and thought I'd report just in case this is not expected.

Am I doing anything obviously wrong?

TLDR of what works or not:

| App name | `--with` | `--with-editable` |
| --- | --- | --- |
| `cli` | ✔️ | ❌ |
| `cli_app` | ❌ | ❌ |
| `cli2` | ✔️ | ✔️ |

Script to reproduce:

```bash
uv --version

app_names=(cli cli_app cli2)
for app_name in ${app_names[@]};
do
    echo
    echo "Testing $app_name"
    lib_name="lib"

    rm -rf $app_name $lib_name

    set -x
    uv init --app --package $app_name
    uv init --lib $lib_name

    uv run --with          ../$app_name --directory $lib_name $app_name
    uv run --with-editable ../$app_name --directory $lib_name $app_name
    set +x
done

```

Output:

```console
$ bash test_uv.sh
uv 0.5.7 (3ca155ddd 2024-12-06)

Testing cli
+ uv init --app --package cli
Initialized project `cli` at `/private/tmp/cli`
+ uv init --lib lib
Initialized project `lib` at `/private/tmp/lib`
+ uv run --with ../cli --directory lib cli
Using CPython 3.13.0
Creating virtual environment at: .venv
   Built lib @ file:///private/tmp/lib
Installed 1 package in 0.91ms
error: Failed to spawn: `cli`
  Caused by: No such file or directory (os error 2)
+ uv run --with-editable ../cli --directory lib cli
Hello from cli!
+ set +x

Testing cli_app
+ uv init --app --package cli_app
Initialized project `cli-app` at `/private/tmp/cli_app`
+ uv init --lib lib
Initialized project `lib` at `/private/tmp/lib`
+ uv run --with ../cli_app --directory lib cli_app
Using CPython 3.13.0
Creating virtual environment at: .venv
   Built lib @ file:///private/tmp/lib
Installed 1 package in 0.88ms
error: Failed to spawn: `cli_app`
  Caused by: No such file or directory (os error 2)
+ uv run --with-editable ../cli_app --directory lib cli_app
error: Failed to spawn: `cli_app`
  Caused by: No such file or directory (os error 2)
+ set +x

Testing cli2
+ uv init --app --package cli2
Initialized project `cli2` at `/private/tmp/cli2`
+ uv init --lib lib
Initialized project `lib` at `/private/tmp/lib`
+ uv run --with ../cli2 --directory lib cli2
Using CPython 3.13.0
Creating virtual environment at: .venv
   Built lib @ file:///private/tmp/lib
Installed 1 package in 0.80ms
Hello from cli2!
+ uv run --with-editable ../cli2 --directory lib cli2
Hello from cli2!
+ set +x
```

**Comment by charliermarsh** [comment]
Unfortunately I can't reproduce this:
```
❯ uv init --app --package cli
Initialized project `cli` at `/Users/crmarsh/workspace/puffin/cli`

❯ uv init --lib lib
Initialized project `lib` at `/Users/crmarsh/workspace/puffin/lib`

❯ uv run --with ../cli --directory lib cli
Using CPython 3.13.0
Creating virtual environment at: .venv
   Built lib @ file:///Users/crmarsh/workspace/puffin/lib
Installed 1 package in 0.86ms
Hello from cli!
```

(I think there almost certainly has to be something else going on here, I don't think we have any code that's sensitive to these names, but of course I could be wrong.)

**Comment by charliermarsh** [comment]
I think the second piece is because the script name uses dashes:

```
❯ uv run --with ../cli --directory lib cli-app
error: Failed to spawn: `cli-app`
  Caused by: No such file or directory (os error 2)

❯ uv run --with ../cli_app --directory lib cli-app
Hello from cli-app!
```

**Comment by charliermarsh** [comment]
That part makes sense, I'm unsure whether we should change it... We're using the canonical package name for the script name.

**Comment by fepegar** [comment]
> Unfortunately I can't reproduce this:
> 
> ```
> ❯ uv init --app --package cli
> Initialized project `cli` at `/Users/crmarsh/workspace/puffin/cli`
> 
> ❯ uv init --lib lib
> Initialized project `lib` at `/Users/crmarsh/workspace/puffin/lib`
> 
> ❯ uv run --with ../cli --directory lib cli
> Using CPython 3.13.0
> Creating virtual environment at: .venv
>    Built lib @ file:///Users/crmarsh/workspace/puffin/lib
> Installed 1 package in 0.86ms
> Hello from cli!
> ```
> 
> (I think there almost certainly has to be something else going on here, I don't think we have any code that's sensitive to these names, but of course I could be wrong.)

In case it helps, that one works when I add `--python 3.10` to the `uv init` commands. It's very mysterious. I'm happy to share more context. These are my pythons:

```console
❯ uv python list
cpython-3.13.1+freethreaded-macos-aarch64-none    <download available>
cpython-3.13.1-macos-aarch64-none                 <download available>
cpython-3.13.0-macos-aarch64-none                 /opt/homebrew/opt/python@3.13/bin/python3.13 -> ../Frameworks/Python.framework/Versions/3.13/bin/python3.13
cpython-3.13.0-macos-aarch64-none                 /Users/fernando/.local/share/uv/python/cpython-3.13.0-macos-aarch64-none/bin/python3.13
cpython-3.12.8-macos-aarch64-none                 <download available>
cpython-3.12.7-macos-aarch64-none                 /opt/homebrew/opt/python@3.12/bin/python3.12 -> ../Frameworks/Python.framework/Versions/3.12/bin/python3.12
cpython-3.12.5-macos-aarch64-none                 /Users/fernando/.local/share/uv/python/cpython-3.12.5-macos-aarch64-none/bin/python3.12
cpython-3.11.11-macos-aarch64-none                <download available>
cpython-3.11.6-macos-aarch64-none                 /opt/homebrew/opt/python@3.11/bin/python3.11 -> ../Frameworks/Python.framework/Versions/3.11/bin/python3.11
cpython-3.10.16-macos-aarch64-none                <download available>
cpython-3.10.15-macos-aarch64-none                /opt/homebrew/opt/python@3.10/bin/python3.10 -> ../Frameworks/Python.framework/Versions/3.10/bin/python3.10
cpython-3.10.15-macos-aarch64-none                /Users/fernando/.local/share/uv/python/cpython-3.10.15-macos-aarch64-none/bin/python3.10
cpython-3.9.21-macos-aarch64-none                 <download available>
cpython-3.9.6-macos-aarch64-none                  /Library/Developer/CommandLineTools/usr/bin/python3 -> ../../Library/Frameworks/Python3.framework/Versions/3.9/bin/python3
cpython-3.8.20-macos-aarch64-none                 /Users/fernando/.local/share/uv/python/cpython-3.8.20-macos-aarch64-none/bin/python3.8
pypy-3.10.14-macos-aarch64-none                   <download available>
pypy-3.9.19-macos-aarch64-none                    <download available>
pypy-3.8.16-macos-aarch64-none                    /Users/fernando/.local/share/uv/python/pypy-3.8.16-macos-aarch64-none/bin/pypy3.8 -> pypy3
```

---

About the underscore vs dash, I guess it makes sense, although it was a bit surprising. Maybe a message mentioning the "_" -> "-" replacement would be nice.

---

My actual problem (which I tried to distill here but I think I've failed) might be related to the underscore/dash situation. I'll see if I can replicate that reliably.

**Comment by fepegar** [comment]
Ok I've created an example that looks more like my actual problem. Basically, `with` and `with-editable` don't work, but `uv add` and then `uv run` does. Happy to open a new issue with a better title if needed.

Hopefully this makes sense:

```shell
set -x

uv --version

lib_name="my-lib"
module_name=${lib_name/-/_}
app_name="app"

rm -rf $lib_name
rm -rf $app_name

uv init --app --package $app_name
uv init --lib --package $lib_name

old_statement="print(\"Hello from $app_name!\")"
new_statement="from $module_name import hello; print(hello)"
sed_input="s/$old_statement/$new_statement/g"
echo "sed_input: $sed_input"
sed -i '' "$sed_input" $app_name/src/$app_name/__init__.py

uv run --with          ../$lib_name --directory $app_name $app_name

uv run --with-editable ../$lib_name --directory $app_name $app_name

uv add ../$lib_name --directory $app_name
uv run --directory $app_name $app_name
```

Output:

```python-traceback
+ uv --version
uv 0.5.7 (3ca155ddd 2024-12-06)
+ lib_name=my-lib
+ module_name=my_lib
+ app_name=app
+ rm -rf my-lib
+ rm -rf app
+ uv init --app --package app
Initialized project `app` at `/private/tmp/app`
+ uv init --lib --package my-lib
Initialized project `my-lib` at `/private/tmp/my-lib`
+ old_statement='print("Hello from app!")'
+ new_statement='from my_lib import hello; print(hello)'
+ sed_input='s/print("Hello from app!")/from my_lib import hello; print(hello)/g'
+ echo 'sed_input: s/print("Hello from app!")/from my_lib import hello; print(hello)/g'
sed_input: s/print("Hello from app!")/from my_lib import hello; print(hello)/g
+ sed -i '' 's/print("Hello from app!")/from my_lib import hello; print(hello)/g' app/src/app/__init__.py
+ uv run --with ../my-lib --directory app app
Using CPython 3.13.0
Creating virtual environment at: .venv
   Built app @ file:///private/tmp/app
Installed 1 package in 1ms
Traceback (most recent call last):
  File "/private/tmp/app/.venv/bin/app", line 8, in <module>
    sys.exit(main())
             ~~~~^^
  File "/private/tmp/app/src/app/__init__.py", line 2, in main
    from my_lib import hello; print(hello)
    ^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'my_lib'
+ uv run --with-editable ../my-lib --directory app app
Traceback (most recent call last):
  File "/private/tmp/app/.venv/bin/app", line 8, in <module>
    sys.exit(main())
             ~~~~^^
  File "/private/tmp/app/src/app/__init__.py", line 2, in main
    from my_lib import hello; print(hello)
    ^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'my_lib'
+ uv add ../my-lib --directory app
Resolved 2 packages in 1ms
   Built app @ file:///private/tmp/app
   Built my-lib @ file:///private/tmp/my-lib
Prepared 2 packages in 182ms
Uninstalled 1 package in 0.49ms
Installed 2 packages in 1ms
 ~ app==0.1.0 (from file:///private/tmp/app)
 + my-lib==0.1.0 (from file:///private/tmp/my-lib)
+ uv run --directory app app
<function hello at 0x100d70d60>
```

**Comment by charliermarsh** [comment]
I think this is an issue with how the environment layering works, but please do open a separate issue since it's unrelated to the dash vs. underscore thing above.

**Comment by charliermarsh** [comment]
I see the problem though not obvious how to fix it.

**Comment by fepegar** [comment]
Thanks for your replies, @charliermarsh. New issue:

- https://github.com/astral-sh/uv/issues/9724

**Comment by fepegar** [comment]
Closing as I can't reproduce on 0.5.21.
