### ISSUE TITLE
`--with` not working with local packages

### ISSUE THREAD

**Issue by fepegar** [astral-sh/uv#9724]
(Originally posted in https://github.com/astral-sh/uv/issues/9719#issuecomment-2526350374)

My local app can't find the local package I'm adding with `--with`:

```bash
set -x

uv --version

# Create the app and the library
uv init --app --package app
uv init --lib --package my-lib

# Import the lib from the app
old_statement="print(\"Hello from app!\")"
new_statement="from my_lib import hello; print(hello)"
sed -i '' "s/$old_statement/$new_statement/g" app/src/app/__init__.py

# This doesn't work
uv run --with ../my-lib --directory app app

# This works
uv add ../my-lib --directory app
uv run --directory app app
```

Output:

```python-traceback
+ uv --version
uv 0.5.7 (3ca155ddd 2024-12-06)
+ uv init --app --package app
Initialized project `app` at `/private/tmp/app`
+ uv init --lib --package my-lib
Initialized project `my-lib` at `/private/tmp/my-lib`
+ old_statement='print("Hello from app!")'
+ new_statement='from my_lib import hello; print(hello)'
+ sed -i '' 's/print("Hello from app!")/from my_lib import hello; print(hello)/g' app/src/app/__init__.py
+ uv run --with ../my-lib --directory app app
Using CPython 3.13.0
Creating virtual environment at: .venv
   Built app @ file:///private/tmp/app
Installed 1 package in 1ms
Traceback (most recent call last):
  File "/private/tmp/app/.venv/bin/app", line 8, in <module>
    sys.exit(main())
             ~~~~^^
  File "/private/tmp/app/src/app/__init__.py", line 2, in main
    from my_lib import hello; print(hello)
    ^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'my_lib'
+ uv add ../my-lib --directory app
Resolved 2 packages in 0.92ms
   Built app @ file:///private/tmp/app
   Built my-lib @ file:///private/tmp/my-lib
Prepared 2 packages in 199ms
Uninstalled 1 package in 0.61ms
Installed 2 packages in 1ms
 ~ app==0.1.0 (from file:///private/tmp/app)
 + my-lib==0.1.0 (from file:///private/tmp/my-lib)
+ uv run --directory app app
<function hello at 0x104e64d60>
```

**Comment by charliermarsh** [comment]
The issue here is that when you execute `app` or another Python executable file, it actually just runs based on the shebang at the top, which points a virtual environment that doesn't have `my_lib` installed. I don't know how to solve it. I guess we'd have to intercept the call prior to going to the shell, and run it with `python ./app` instead? It's a little weird though. If you're building a script that imports a dependency, I'd probably recommend making it a "real" dependency rather than going through `--with`.

**Comment by fepegar** [comment]
> that doesn't have my_lib installed

Doesn't `--with` force the library to be installed ephemerally, during the command execution?

> I'd probably recommend making it a "real" dependency

It's a bit awkward because the library is in a private GitHub repo, so in the CI I've been first setting up SSH keys, then downloading it, then tried to run with `--with`. As that didn't work, I've been adding it before running. Normally, it would be an optional dependency.

**Comment by topher96** [comment]
If the with path was fully qualified rather than relative does it work?   If that's not the issue  - What if you used the full path syntax with the @  shown here 
https://stackoverflow.com/a/77181715/11472527

 --with "my-lib @ file://fully qualified path to my-lib"

**Comment by fepegar** [comment]
Thanks, @topher96. Unfortunately, that didn't help.
