### ISSUE TITLE
Can't run tensorrt_llm with uv

### ISSUE THREAD

**Issue by twmht** [astral-sh/uv#9763]
Hi,

I use uv (from python3.10.12)  to install [tensort_llm](https://nvidia.github.io/TensorRT-LLM/installation/linux.html)

```bash
uv pip install tensorrt_llm
```

and then import tensorrt_llm

```pythom
import tensorrt_llm
```

but it would show

```
Traceback (most recent call last):
  File "/home/shared/WhisperS2T/examples/test_import.py", line 1, in <module>
    import tensorrt_llm
  File "/home/acer/.venv/tensorrt-llm/lib/python3.10/site-packages/tensorrt_llm/__init__.py", line 32, in <module>
    import tensorrt_llm.functional as functional
  File "/home/acer/.venv/tensorrt-llm/lib/python3.10/site-packages/tensorrt_llm/functional.py", line 25, in <module>
    import tensorrt as trt
  File "/home/acer/.venv/tensorrt-llm/lib/python3.10/site-packages/tensorrt/__init__.py", line 18, in <module>
    from tensorrt_bindings import *
ModuleNotFoundError: No module named 'tensorrt_bindings'
```

But if you install it through pip, there will be no problems at all.

Any idea?

**Comment by rohnsha0** [comment]
using `uv add` doesn't help?

**Comment by twmht** [comment]
I didn't try `uv add`, but what is the big difference between it and `uv pip install`?

**Comment by charliermarsh** [comment]
Can you include the `--verbose` logs from `uv pip install`? (Are you sure that you installed from the nvidia index, and that you activated the virtual environment?)

**Comment by konstin** [comment]
Can reproduce in `nvidia/cuda:12.6.3-cudnn-devel-ubuntu24.04`. The pypi packages uses https://github.com/wheel-next/wheel-stub as build backend, maybe @emmatyping-nv knows.

**Comment by emmatyping-nv** [comment]
Does uv inspect the PKG-INFO to decide dependencies or does it build the wheel and look at what the backend generates? `tensorrt_cu12` does a similar thing to wheel-stub to acquire the real wheel via an sdist build, but I don't think it lists it's dependencies in the PKG-INFO.

**Comment by charliermarsh** [comment]
If available for PyPI dependencies, yes, we'll use PKG-INFO. If not, we ask the backend. It's all heuristics so we could probably refine it.

**Comment by melMass** [comment]
I solved this issue by using `--pre`:

```sh
uv add --group trt tensorrt-bindings --pre # I'm using a group, omit it for regular dep
Ignoring existing lockfile due to change in pre-release mode: `if-necessary-or-explicit` vs. `allow`
Resolved 153 packages in 883ms
   Built tensorrt==10.7.0
Prepared 7 packages in 36.67s
Uninstalled 5 packages in 198ms
Installed 8 packages in 207ms
 - beautifulsoup4==4.12.3
 + beautifulsoup4==4.13.0b2
 - cython==3.0.11
 + cython==3.1.0a1
 - omegaconf==2.3.0
 + omegaconf==2.4.0.dev3
 - safetensors==0.4.5
 + safetensors==0.4.6.dev0
 - scipy==1.14.1
 + scipy==1.15.0rc2
 + tensorrt==10.7.0
 + tensorrt-bindings==9.3.0.post12.dev1
 + tensorrt-cu12==10.7.0
```

**Comment by emmatyping-nv** [comment]
Perhaps after resolving dependencies via `PKG-INFO`, after the wheel build you could verify the generated wheel dependencies match the `PKG-INFO`, and backtrack if they disagree. This lets the current behavior continue as a pre-fetch optimization while still ending up with the correct result.

**Comment by konstin** [comment]
There's a number of packages with `PKG-INFO` that doesn't match the final `METADATA`, so i'm afraid we can't dismiss those packages.

**Comment by emmatyping-nv** [comment]
> There's a number of packages with PKG-INFO that doesn't match the final METADATA, so i'm afraid we can't dismiss those packages.

I think if you re-solve dependencies with the new requirements if the PKG-INFO and METADATA do not match, you won't have issues unless information is somehow not captured in the METADATA file that is captured in the PKG-INFO (which should not happen unless a build backend is misbehaving).

To be more precise with what I said above, I'm imagining uv having the following behavior:

1. uv selects an sdist to be installed (say, as part of normal package resolution)
2. you download the dependencies from PKG-INFO, and store the list of those
3. you build the sdist into a wheel
4. you check if the METADATA matches the PKG-INFO *requirements/extras only*. 
5. Then you either
    a. find that they match and continue with the resolution normally
    b. find that they differ and feed this information back to the resolver so that it can take this additional information into account

This way if the requirements listed in METADATA matches PKG-INFO, you get the current speed benefits with a tiny bit of extra checks. If they differ, package installation/resolution will be slower, but still eventually come out with the correct answer.

**Comment by emmatyping-nv** [comment]
@melMass 
> I solved this issue by using --pre

I would recommend instead to [use an index](https://docs.astral.sh/uv/configuration/indexes/#defining-an-index) to point to the official NVIDIA PyPI server and the sub-packages `tensorrt-cu12` points to:

```toml
[project]
dependencies = [
    "tensorrt-cu12-libs", # ref: https://github.com/astral-sh/uv/issues/9763
    "tensorrt-cu12-bindings", # ref: https://github.com/astral-sh/uv/issues/9763
]

[tool.uv.sources]
tensorrt-cu12-libs = { index = "nvidia" }
tensorrt-cu12-bindings = { index = "nvidia" }

[[tool.uv.index]]
name = "nvidia"
url = "https://pypi.nvidia.com/"
```

**Comment by henryzhuhr** [comment]
my `pyproject.toml` is:
```toml
[project]
name = "my project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11, <3.13"
dependencies = [
    "huggingface-hub[cli]>=0.34.3",
    "loguru>=0.7.3",
    "transformers[torch]>=4.54.1",
]
```

When I use the command `uv add tensorrt-llm` to add the dependency, I encounter the following error:
```bash
error: Package `flashinfer` attempted to resolve via URL: git+https://github.com/flashinfer-ai/flashinfer.git@06309c4e. URL dependencies must be expressed as direct requirements or constraints. Consider adding `flashinfer @ git+https://github.com/flashinfer-ai/flashinfer.git@06309c4e` to your dependencies or constraints file.
```

However, when I add with `uv pip install tensorrt-llm`, everything works fine:
```bash
uv pip install tensorrt-llm 
Resolved 141 packages in 127ms
Uninstalled 4 packages in 28ms
Installed 103 packages in 94ms
 + aenum==3.1.16
 + aiohappyeyeballs==2.6.1
 + aiohttp==3.12.15
 + aiosignal==1.4.0
 + annotated-types==0.7.0
 + anyio==4.10.0
 + attrs==25.3.0
 + backoff==2.2.1
 + blake3==1.0.5
 + build==1.3.0
 + click==8.2.1
 + click-option-group==0.5.7
 + colored==2.3.1
 + contourpy==1.3.3
 + cuda-bindings==13.0.0
 + cuda-pathfinder==1.1.0
 + cuda-python==13.0.0
 + cycler==0.12.1
 + datasets==3.1.0
 + diffusers==0.34.0
 + dill==0.3.8
 + distro==1.9.0
 + einops==0.8.1
 + etcd3==0.12.0
 + evaluate==0.4.5
 + fastapi==0.115.4
 + flashinfer-python==0.2.5
 + fonttools==4.59.0
 + frozenlist==1.7.0
 - fsspec==2025.7.0
 + fsspec==2024.9.0
 + grpcio==1.74.0
 + h11==0.16.0
 + h5py==3.12.1
 + httpcore==1.0.9
 + httpx==0.28.1
 + importlib-metadata==8.7.0
 + jiter==0.10.0
 + kiwisolver==1.4.8
 + lark==1.2.2
 + llguidance==0.7.29
 + markdown-it-py==3.0.0
 + matplotlib==3.10.5
 + mdurl==0.1.2
 + meson==1.8.3
 + mpi4py==4.1.0
 + multidict==6.6.3
 + multiprocess==0.70.16
 + ninja==1.11.1.4
 - numpy==2.3.2
 + numpy==1.26.4
 + nvidia-ml-py==12.575.51
 + nvidia-modelopt==0.31.0
 + nvidia-modelopt-core==0.31.0
 + nvtx==0.2.13
 + onnx==1.18.0
 + onnx-graphsurgeon==0.5.8
 + openai==1.99.4
 + opencv-python-headless==4.11.0.86
 + optimum==1.27.0
 + ordered-set==4.1.0
 + pandas==2.3.1
 + peft==0.17.0
 + pillow==10.3.0
 + polygraphy==0.49.26
 + propcache==0.3.2
 + protobuf==6.31.1
 + pulp==3.2.2
 + pyarrow==21.0.0
 + pydantic==2.11.7
 + pydantic-core==2.33.2
 + pygments==2.19.2
 + pynvml==12.0.0
 + pyparsing==3.2.3
 + pyproject-hooks==1.2.0
 + python-dateutil==2.9.0.post0
 + pytz==2025.2
 + pyzmq==27.0.1
 + rich==14.1.0
 + scipy==1.16.1
 + sentencepiece==0.2.0
 - setuptools==80.9.0
 + setuptools==79.0.1
 + six==1.17.0
 + sniffio==1.3.1
 + starlette==0.41.3
 + strenum==0.4.15
 + tenacity==9.1.2
 + tensorrt==10.11.0.33
 + tensorrt-cu12==10.11.0.33
 + tensorrt-cu12-bindings==10.11.0.33
 + tensorrt-cu12-libs==10.11.0.33
 + tensorrt-llm==0.21.0
 + tiktoken==0.10.0
 + torchprofile==0.0.4
 + torchvision==0.22.1
 + tornado==6.5.1
 - transformers==4.54.1
 + transformers==4.51.3
 + typing-inspection==0.4.1
 + tzdata==2025.2
 + uvicorn==0.35.0
 + wheel==0.45.1
 + xgrammar==0.1.18
 + xxhash==3.5.0
 + yarl==1.20.1
 + zipp==3.23.0
```

**Comment by henryzhuhr** [comment]
my `pyproject.toml` is:
```toml
[project]
name = "my project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11, <3.13"
dependencies = [
    "huggingface-hub[cli]>=0.34.3",
    "loguru>=0.7.3",
    "transformers[torch]>=4.54.1",
]
```

When I use the command `uv add tensorrt-llm` to add the dependency, I encounter the following error:
```bash
error: Package `flashinfer` attempted to resolve via URL: git+https://github.com/flashinfer-ai/flashinfer.git@06309c4e. URL dependencies must be expressed as direct requirements or constraints. Consider adding `flashinfer @ git+https://github.com/flashinfer-ai/flashinfer.git@06309c4e` to your dependencies or constraints file.
```

However, when I add with `uv pip install tensorrt-llm`, everything works fine.
