### ISSUE TITLE
Building fails if you use README.org vs README.md

### ISSUE THREAD

**Issue by vikigenius** [astral-sh/uv#9821]
`uv sync` fails if you use a README.org file instead of README.md

Change in pyproject.toml
`readme = "README.org"`

Error

```
  ╰─▶ Build backend failed to build editable through `build_editable` (exit status: 1)

      [stderr]
      Traceback (most recent call last):
        File "<string>", line 11, in <module>
        File "/home/void/.cache/uv/builds-v0/.tmpdjshSM/lib/python3.12/site-packages/hatchling/build.py", line 83, in build_editable
          return os.path.basename(next(builder.build(directory=wheel_directory, versions=['editable'])))
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/void/.cache/uv/builds-v0/.tmpdjshSM/lib/python3.12/site-packages/hatchling/builders/plugin/interface.py", line 90, in build
          self.metadata.validate_fields()
        File "/home/void/.cache/uv/builds-v0/.tmpdjshSM/lib/python3.12/site-packages/hatchling/metadata/core.py", line 266, in validate_fields
          self.core.validate_fields()
        File "/home/void/.cache/uv/builds-v0/.tmpdjshSM/lib/python3.12/site-packages/hatchling/metadata/core.py", line 1366, in validate_fields
          getattr(self, attribute)
        File "/home/void/.cache/uv/builds-v0/.tmpdjshSM/lib/python3.12/site-packages/hatchling/metadata/core.py", line 526, in readme
          raise TypeError(message)
      TypeError: Unable to determine the content-type based on the extension of readme file: README.org
```

**Comment by charliermarsh** [comment]
This isn't a uv issue -- notice that the error comes from hatchling.

**Comment by notatallshaw-gts** [comment]
For other reasons, I happen to have been just looking at the hatcling docs for this: https://hatch.pypa.io/latest/config/metadata/#readme 

Must be a md, rst, or txt.
