### ISSUE TITLE
Bug: ModuleNotFoundError related to venv uv_cache.json

### ISSUE THREAD

**Issue by cvanea** [astral-sh/uv#9902]
### Description

`uv run` fails with a `ModuleNotFoundError` when the venv `uv_cache.json` is present. This doesn’t happen on an earlier macOS version.

### Environment

- uv version: uv 0.5.9 (0652800cb 2024-12-13)
- OS: macOS 15.1.1 (bug present)
- Also tested on: macOS 14.3.1 (bug not present)

### Minimal Reproduction Steps

```bash
uv init --package foo
cd foo
uv run foo
```

### Bug Description

`uv run foo` correctly prints `Hello from foo!` for a few seconds. Then running it results in:

```bash
ModuleNotFoundError: No module named 'foo'
```

### Additional Information

1. Deleting the cache file resolves the issue temporarily:

```bash
rm .venv/lib/python3.13/site-packages/foo-0.1.0.dist-info/uv_cache.json
```

1. Setting the environment variable `UV_NO_INSTALLER_METADATA=1 uv run foo` prevents the issue.

### Debug Information

<details>
<summary>Debug Logs - Failed Run (with cache)</summary>

```
DEBUG uv 0.5.9 (0652800cb 2024-12-13)
DEBUG Found project root: `/Users/user/Documents/code/py/foo`
DEBUG No workspace root found, using project root
DEBUG Discovered project `foo` at: /Users/user/Documents/code/py/foo
DEBUG Reading Python requests from version file at `/Users/user/Documents/code/py/foo/.python-version`
DEBUG Using Python request `3.13` from version file at `.python-version`
TRACE Cached interpreter info for Python 3.13.1, skipping probing: .venv/bin/python3
DEBUG The virtual environment's Python version satisfies `3.13`
DEBUG Using request timeout of 30s
DEBUG Found static `pyproject.toml` for: foo @ file:///Users/user/Documents/code/py/foo
DEBUG No workspace root found, using project root
DEBUG Existing `uv.lock` satisfies workspace requirements
DEBUG Using request timeout of 30s
TRACE Comparing installed with source: Url(InstalledDirectUrlDist { name: PackageName("foo"), version: "0.1.0", direct_url: LocalDirectory { url: "file:///Users/user/Documents/code/py/foo", dir_info: DirInfo { editable: Some(true) } }, url: Url { scheme: "file", cannot_be_a_base: false, username: "", password: None, host: None, port: None, path: "/Users/user/Documents/code/py/foo", query: None, fragment: None }, editable: true, path: "/Users/user/Documents/code/py/foo/.venv/lib/python3.13/site-packages/foo-0.1.0.dist-info", cache_info: Some(CacheInfo { timestamp: Some(Timestamp(SystemTime { tv_sec: 1734188435, tv_nsec: 526620830 })), commit: None, tags: None }) }) Directory { install_path: "/Users/user/Documents/code/py/foo", editable: true, virtual: false, url: VerbatimUrl { url: Url { scheme: "file", cannot_be_a_base: false, username: "", password: None, host: None, port: None, path: "/Users/user/Documents/code/py/foo", query: None, fragment: None }, given: None } }
DEBUG Requirement already installed: foo==0.1.0 (from file:///Users/user/Documents/code/py/foo)
DEBUG Using Python 3.13.1 interpreter at: /Users/user/Documents/code/py/foo/.venv/bin/python3
DEBUG Running `foo`
Traceback (most recent call last):
  File "/Users/user/Documents/code/py/foo/.venv/bin/foo", line 5, in <module>
    from foo import main
ModuleNotFoundError: No module named 'foo'
DEBUG Command exited with code: 1
```

</details>
<details>
<summary>Debug Logs - Successful Run (after removing cache)</summary>

```
DEBUG uv 0.5.9 (0652800cb 2024-12-13)
DEBUG Found project root: `/Users/user/Documents/code/py/foo`
DEBUG No workspace root found, using project root
DEBUG Discovered project `foo` at: /Users/user/Documents/code/py/foo
DEBUG Reading Python requests from version file at `/Users/user/Documents/code/py/foo/.python-version`
DEBUG Using Python request `3.13` from version file at `.python-version`
TRACE Cached interpreter info for Python 3.13.1, skipping probing: .venv/bin/python3
DEBUG The virtual environment's Python version satisfies `3.13`
DEBUG Using request timeout of 30s
DEBUG Found static `pyproject.toml` for: foo @ file:///Users/user/Documents/code/py/foo
DEBUG No workspace root found, using project root
DEBUG Existing `uv.lock` satisfies workspace requirements
DEBUG Using request timeout of 30s
TRACE Comparing installed with source: Url(InstalledDirectUrlDist { name: PackageName("foo"), version: "0.1.0", direct_url: LocalDirectory { url: "file:///Users/user/Documents/code/py/foo", dir_info: DirInfo { editable: Some(true) } }, url: Url { scheme: "file", cannot_be_a_base: false, username: "", password: None, host: None, port: None, path: "/Users/user/Documents/code/py/foo", query: None, fragment: None }, editable: true, path: "/Users/user/Documents/code/py/foo/.venv/lib/python3.13/site-packages/foo-0.1.0.dist-info", cache_info: None }) Directory { install_path: "/Users/user/Documents/code/py/foo", editable: true, virtual: false, url: VerbatimUrl { url: Url { scheme: "file", cannot_be_a_base: false, username: "", password: None, host: None, port: None, path: "/Users/user/Documents/code/py/foo", query: None, fragment: None }, given: None } }
DEBUG Requirement installed, but not fresh: foo==0.1.0 (from file:///Users/user/Documents/code/py/foo)
DEBUG Directory source requirement already cached: foo==0.1.0 (from file:///Users/user/Documents/code/py/foo)
[File removal logs...]
DEBUG Uninstalled foo (9 files, 1 directory)
Uninstalled 1 package in 1ms
[Installation logs...]
Installed 1 package in 3ms
DEBUG Using Python 3.13.1 interpreter at: /Users/user/Documents/code/py/foo/.venv/bin/python3
DEBUG Running `foo`
Hello from foo!
DEBUG Command exited with code: 0
```

</details>

**Comment by charliermarsh** [comment]
I think I would need to see a full reproduction in order to help (like, an example project that reproduces the bug along with a series of commands). From the logs, it looks like removing the cache file is just invalidating the cache?

**Comment by cvanea** [comment]
Hi Charlie, thanks for taking a look at this!

I figured out the source of the issue. If the uv project is in an iCloud synced directory then this error happens reliably. I don't fully understand it but it seems related to the way macOS treats the file paths of synced directories. The cache says the documents are here:

`/Users/user/Documents/code/py/foo`

But in reality they're here: 

`/Users/user/Library/Mobile Documents/com~apple~CloudDocs/Documents/code/py/foo`

This also explains the timing nature of the bug due to the sync schedule.

## Full Reproduction Steps

1. Enable iCloud sync for Documents
2. `cd Documents`
3. `uv init --package foo`
4. `cd foo`
5. `uv run foo`
6. Wait 10 seconds
7. Repeat `uv run foo` until `ModuleNotFoundError`

This is reproducible across macOS versions (macOS 15.1.1, 14.3.1, 13.5).

Very silly to have this in an iCloud syncing directory! New computer 😅 However a few people had this same issue at an Anthropic hackathon I went to recently.

**Comment by cjim8889** [comment]
+1

**Comment by ceeeeej** [comment]
Glad I found this, I was able to observe the same behavior on an iCloud based project. I thought I was insane as I couldn't get workspaces to work in a monorepo.

This is a nice to have as it would allow the directories to be synced across Macs. I don't think I have ever run into problems with storing code / git repos in iCloud until this.

Would the fix just to be resolving the path or using a relative path?

**Comment by huntermatthews** [comment]
@charliermarsh -- ping

I'm hitting this as well. 
Please note: I *think* this is a uv bug, *but* freely acknowledge it could be a python bug.
Please let me know if I can provide any other information.

macOS 15.5 (24F74)
uv 0.7.20 (Homebrew 2025-07-09).  installed via Homebrew 4.5.9

I've created a simple hello world repo at https://github.com/huntermatthews/helllo_world. -- the only change from 
uv init --app hello_world is to move the main function into a package, forcing package resolution.

If I move the project directory outside of iCloud (both a simple copy and via symlink) I do not hit problem.

I reproduced this with python 3.8, 3.10, and 3.12. The hello_world repo is currently at 3.8.



```shell
hunter@ed ~/p/helllo_world (main)> uv run hw
Using CPython 3.10.18
Creating virtual environment at: .venv
      Built hw @ file:///Users/hunter/Documents/projects/helllo_world
Installed 1 package in 2ms
Hello from hello-world!
hunter@ed ~/p/helllo_world (main)> uv run hw ; date
Traceback (most recent call last):
  File "/Users/hunter/Documents/projects/helllo_world/.venv/bin/hw", line 4, in <module>
    from hw.cli import main
ModuleNotFoundError: No module named 'hw'
Thu Jul 10 23:44:59 EDT 2025
hunter@ed ~/p/helllo_world (main)> rm -rf .venv/
hunter@ed ~/p/helllo_world (main)> uv run hw ; date
Using CPython 3.10.18
Creating virtual environment at: .venv
Installed 1 package in 8ms
Hello from hello-world!
Fri Jul 11 00:11:47 EDT 2025
hunter@ed ~/p/helllo_world (main)> uv run hw ; date
Hello from hello-world!
Fri Jul 11 00:11:48 EDT 2025
hunter@ed ~/p/helllo_world (main)> uv run hw ; date
Hello from hello-world!
Fri Jul 11 00:11:49 EDT 2025
hunter@ed ~/p/helllo_world (main)> uv run hw ; date
Hello from hello-world!
Fri Jul 11 00:11:51 EDT 2025
hunter@ed ~/p/helllo_world (main)> uv run hw ; date
Traceback (most recent call last):
  File "/Users/hunter/Documents/projects/helllo_world/.venv/bin/hw", line 4, in <module>
    from hw.cli import main
ModuleNotFoundError: No module named 'hw'
Fri Jul 11 00:11:52 EDT 2025
hunter@ed ~/p/helllo_world (main)>
```

Reproduction with --verbose:
```shell
hunter@ed ~/p/helllo_world (main)> rm -rf .venv
hunter@ed ~/p/helllo_world (main)> date ; uv  run --verbose hw
Fri Jul 11 00:20:57 EDT 2025
DEBUG uv 0.7.20 (Homebrew 2025-07-09)
DEBUG Found project root: `/Users/hunter/Documents/projects/helllo_world`
DEBUG No workspace root found, using project root
DEBUG Discovered project `hw` at: /Users/hunter/Documents/projects/helllo_world
DEBUG Acquired lock for `/Users/hunter/Documents/projects/helllo_world`
DEBUG Reading Python requests from version file at `/Users/hunter/Documents/projects/helllo_world/.python-version`
DEBUG Using Python request `3.10` from version file at `.python-version`
DEBUG Checking for Python environment at `.venv`
DEBUG Searching for Python 3.10 in managed installations or search path
DEBUG Searching for managed installations at `/Users/hunter/.local/share/uv/python`
DEBUG Found managed installation `cpython-3.10.18-macos-aarch64-none`
DEBUG Found `cpython-3.10.18-macos-aarch64-none` at `/Users/hunter/.local/share/uv/python/cpython-3.10.18-macos-aarch64-none/bin/python3.10` (managed installations)
Using CPython 3.10.18
Creating virtual environment at: .venv
DEBUG Assessing Python executable as base candidate: /Users/hunter/.local/share/uv/python/cpython-3.10.18-macos-aarch64-none/bin/python3.10
DEBUG Using base executable for virtual environment: /Users/hunter/.local/share/uv/python/cpython-3.10.18-macos-aarch64-none/bin/python3.10
DEBUG Released lock at `/var/folders/qv/t8pt14356h50k_lpgd2rhvg40000gn/T/uv-4d4b934068286181.lock`
DEBUG Acquired lock for `.venv`
DEBUG Using request timeout of 30s
DEBUG Found static `pyproject.toml` for: hw @ file:///Users/hunter/Documents/projects/helllo_world
DEBUG No workspace root found, using project root
DEBUG Existing `uv.lock` satisfies workspace requirements
Resolved 1 package in 0.93ms
DEBUG Using request timeout of 30s
DEBUG Computed cache info: Some(Timestamp(SystemTime { tv_sec: 1752205162, tv_nsec: 273578285 })), None, None, {}, {"src": Some(Timestamp(Timestamp(SystemTime { tv_sec: 1752199360, tv_nsec: 22408246 })))}
DEBUG Directory source requirement already cached: hw==0.1.0 (from file:///Users/hunter/Documents/projects/helllo_world)
Installed 1 package in 4ms
 + hw==0.1.0 (from file:///Users/hunter/Documents/projects/helllo_world)
DEBUG Released lock at `/Users/hunter/Documents/projects/helllo_world/.venv/.lock`
DEBUG Using Python 3.10.18 interpreter at: /Users/hunter/Documents/projects/helllo_world/.venv/bin/python
DEBUG Running `hw`
DEBUG Spawned child 24446 in process group 24445
Hello from hello-world!
DEBUG Command exited with code: 0
hunter@ed ~/p/helllo_world (main)> date ; uv  run --verbose hw
Fri Jul 11 00:21:00 EDT 2025
DEBUG uv 0.7.20 (Homebrew 2025-07-09)
DEBUG Found project root: `/Users/hunter/Documents/projects/helllo_world`
DEBUG No workspace root found, using project root
DEBUG Discovered project `hw` at: /Users/hunter/Documents/projects/helllo_world
DEBUG Acquired lock for `/Users/hunter/Documents/projects/helllo_world`
DEBUG Reading Python requests from version file at `/Users/hunter/Documents/projects/helllo_world/.python-version`
DEBUG Using Python request `3.10` from version file at `.python-version`
DEBUG Checking for Python environment at `.venv`
DEBUG The project environment's Python version satisfies the request: `Python 3.10`
DEBUG Released lock at `/var/folders/qv/t8pt14356h50k_lpgd2rhvg40000gn/T/uv-4d4b934068286181.lock`
DEBUG Acquired lock for `.venv`
DEBUG Using request timeout of 30s
DEBUG Found static `pyproject.toml` for: hw @ file:///Users/hunter/Documents/projects/helllo_world
DEBUG No workspace root found, using project root
DEBUG Existing `uv.lock` satisfies workspace requirements
Resolved 1 package in 0.99ms
DEBUG Using request timeout of 30s
DEBUG Computed cache info: Some(Timestamp(SystemTime { tv_sec: 1752205162, tv_nsec: 273578285 })), None, None, {}, {"src": Some(Timestamp(Timestamp(SystemTime { tv_sec: 1752199360, tv_nsec: 22408246 })))}
DEBUG Requirement already installed: hw==0.1.0 (from file:///Users/hunter/Documents/projects/helllo_world)
Audited 1 package in 0.15ms
DEBUG Released lock at `/Users/hunter/Documents/projects/helllo_world/.venv/.lock`
DEBUG Using Python 3.10.18 interpreter at: /Users/hunter/Documents/projects/helllo_world/.venv/bin/python3
DEBUG Running `hw`
DEBUG Spawned child 24454 in process group 24453
Hello from hello-world!
DEBUG Command exited with code: 0
hunter@ed ~/p/helllo_world (main)> date ; uv  run --verbose hw
Fri Jul 11 00:21:03 EDT 2025
DEBUG uv 0.7.20 (Homebrew 2025-07-09)
DEBUG Found project root: `/Users/hunter/Documents/projects/helllo_world`
DEBUG No workspace root found, using project root
DEBUG Discovered project `hw` at: /Users/hunter/Documents/projects/helllo_world
DEBUG Acquired lock for `/Users/hunter/Documents/projects/helllo_world`
DEBUG Reading Python requests from version file at `/Users/hunter/Documents/projects/helllo_world/.python-version`
DEBUG Using Python request `3.10` from version file at `.python-version`
DEBUG Checking for Python environment at `.venv`
DEBUG The project environment's Python version satisfies the request: `Python 3.10`
DEBUG Released lock at `/var/folders/qv/t8pt14356h50k_lpgd2rhvg40000gn/T/uv-4d4b934068286181.lock`
DEBUG Acquired lock for `.venv`
DEBUG Using request timeout of 30s
DEBUG Found static `pyproject.toml` for: hw @ file:///Users/hunter/Documents/projects/helllo_world
DEBUG No workspace root found, using project root
DEBUG Existing `uv.lock` satisfies workspace requirements
Resolved 1 package in 1ms
DEBUG Using request timeout of 30s
DEBUG Computed cache info: Some(Timestamp(SystemTime { tv_sec: 1752205162, tv_nsec: 273578285 })), None, None, {}, {"src": Some(Timestamp(Timestamp(SystemTime { tv_sec: 1752199360, tv_nsec: 22408246 })))}
DEBUG Requirement already installed: hw==0.1.0 (from file:///Users/hunter/Documents/projects/helllo_world)
Audited 1 package in 0.14ms
DEBUG Released lock at `/Users/hunter/Documents/projects/helllo_world/.venv/.lock`
DEBUG Using Python 3.10.18 interpreter at: /Users/hunter/Documents/projects/helllo_world/.venv/bin/python3
DEBUG Running `hw`
DEBUG Spawned child 24462 in process group 24461
Traceback (most recent call last):
  File "/Users/hunter/Documents/projects/helllo_world/.venv/bin/hw", line 4, in <module>
    from hw.cli import main
ModuleNotFoundError: No module named 'hw'
DEBUG Command exited with code: 1
```

**Comment by huntermatthews** [comment]
Oh - and I would ask the bug be renamed to include "iCloud" somewhere - this was the devil to find.

**Comment by matthewsht** [comment]
I've just had a chance to test this on the work laptop - using OneDrive ( MS icloud knock-off) I can't reproduce the problem:

### System info:
```
❯ uv --version
uv 0.7.21 (Homebrew 2025-07-14)
❯ sw_vers
ProductName:		macOS
ProductVersion:		15.5
BuildVersion:		24F74
```

### Run:
```
❯ cd ~/Documents/proj_test/
❯ git clone git@github.com:huntermatthews/helllo_world.git
Cloning into 'helllo_world'...
remote: Enumerating objects: 13, done.
remote: Counting objects: 100% (13/13), done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 13 (delta 0), reused 10 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (13/13), done.
❯ cd helllo_world/
❯ uv sync
Using CPython 3.10.18 interpreter at: /opt/homebrew/opt/python@3.10/bin/python3.10
Creating virtual environment at: .venv
Resolved 1 package in 20ms
      Built hw @ file:///Users/matthewsht/Library/CloudStorage/OneDrive-WORK_NAME_HERE/Documents/proj_test/helllo_world
Prepared 1 package in 1.28s
Installed 1 package in 8ms
 + hw==0.1.0 (from file:///Users/matthewsht/Library/CloudStorage/OneDrive-WORK_NAME_HERE/Documents/proj_test/helllo_world)
❯ uv run hw
Hello from hello-world!
```

Also, Ive just noticed I spelled hello wrong. Sigh.

**Comment by docj3k** [comment]
I hit this and can offer a root cause + reproduction. The bug is not in `uv_cache.json` itself — it's an interaction between **iCloud Drive** and **Python 3.13's hidden-`.pth` security check**, and both reported workarounds only mask it.

## Root cause

1. When a project lives in an iCloud-synced folder (Desktop/Documents with "Desktop & Documents Folders" sync, or iCloud Drive), the iCloud sync daemon recursively sets the macOS `UF_HIDDEN` file flag on dot-directories **and all of their contents** — including everything under `.venv`. This happens asynchronously, typically within minutes of file creation. Observed on macOS 26.5.2; the original report here saw it appear moving from macOS 14 → 15, which matches.
2. Python 3.13's `site.py addpackage()` **silently skips `.pth` files that carry `UF_HIDDEN`** (deliberate security measure, python/cpython#113659).
3. The project's editable install lives in site-packages as a `.pth` file (`_editable_impl_<name>.pth` with hatchling, `<name>.pth` with uv_build). Once the daemon flags it, the package silently vanishes from `sys.path` → `ModuleNotFoundError`.

## Why the known workarounds "work"

Both force uv to reinstall, which rewrites the `.pth` fresh (unflagged) — winning a race against the daemon until it re-flags a few minutes later:

- deleting `uv_cache.json` → cache miss → reinstall
- `UV_NO_INSTALLER_METADATA=1` → reinstall on every run

This also explains the maddening intermittency: `uv sync` fixes it, and it breaks again minutes later with no further uv activity.

## Diagnosis / verification on an affected machine

```console
$ ls -lO .venv/lib/python3.13/site-packages/*.pth
-rw-r--r--@ 1 user staff hidden 42 ... _editable_impl_myproj.pth   # ← "hidden"
$ find .venv -flags +hidden | wc -l
    1826        # every entry in the venv
$ chflags nohidden .venv/lib/python3.13/site-packages/*.pth
$ uv run python -c "import myproj"   # works — until the daemon re-flags it
```

Control: the identical project outside any iCloud-synced path never gets flagged (0 hidden entries).

## Reproduction

1. macOS with "Desktop & Documents Folders" iCloud sync enabled, Python ≥ 3.13.
2. `uv init --lib myproj` inside `~/Desktop` (or `~/Documents`), `uv sync`.
3. `uv run python -c "import myproj"` — works.
4. Wait for iCloud to process the tree (minutes; `ls -lO` on the `.pth` until it shows `hidden`).
5. `uv run python -c "import myproj"` → `ModuleNotFoundError`.

## User-side fix

Put the venv outside the synced tree: `UV_PROJECT_ENVIRONMENT=~/.venvs/myproj`.

## What uv could do

- **Detect and warn**: on sync, if the created/existing environment is under an iCloud-synced path (or if a just-written `.pth` carries `UF_HIDDEN`), warn that Python ≥ 3.13 will silently ignore it.
- **Actively clear the flag**: `chflags nohidden` (i.e. clear `UF_HIDDEN` in `st_flags`) on `.pth` files uv writes — cheap, though the daemon can re-flag later, so detection/warning is the more durable help.
- Docs note under the macOS/troubleshooting section.

Happy to provide more details from the affected machine.
